### ISSUE TITLE
ChoETL CSVWriter is not handling double quotes correctly.

### ISSUE THREAD

**Issue by OxEMoron** [Cinchoo/ChoETL#1]
When a string has a Double Quote Char it needs to be doubled up...

```
class EmployeeRecSimple
{
    public int Id { get; set; }
    public string Name { get; set; }
}

static void Main(string[] args)
{
    List<EmployeeRecSimple> objs = new List<EmployeeRecSimple>()
    {
        new EmployeeRecSimple() { Id = 20, Name = "John Smith" },
        new EmployeeRecSimple() { Id = 21, Name = "Jack in \"Da Box" }
    };
    Console.WriteLine(ChoCSVWriter.ToText(objs));
    Console.ReadLine();
}

```
the output is: 

```
20,John Smith
21,Jack in "Da Box

```
the second line needs to be change to... 

`21,"Jack in ""Da Box"`

**Comment by Cinchoo** [comment]
Will be taking care of in next release.

**Comment by Cinchoo** [comment]
Fix applied, please take the latest.

**Comment by TM458** [comment]
I am having the same issue in the latest version
`            Dim lst As New List(Of EmployeeRecSimple)
            lst.Add(New EmployeeRecSimple With {.ID = 1, .Name = "13"" Test"})
            Console.WriteLine(ChoCSVWriter.ToText(lst(0)))
            Console.ReadKey()
`
Output:
`ID,Name
1,13" Test`

**Comment by OxEMoron** [comment]
That is an interesting Issue... two double quotes in the CSS file = add
double quote to string, and keep reading.  This should somehow "escape" out
this double double quote as """".

**Comment by TM458** [comment]
walking thru the code it is getting skipped because QuoteField is set to False instead of Null.

**Comment by TM458** [comment]
> walking thru the code it is getting skipped because QuoteField is set to False instead of Null.

If I define the configuration 
`            Dim config As New ChoCSVRecordConfiguration()
            config.FileHeaderConfiguration.HasHeaderRecord = True
            config.CSVRecordFieldConfigurations.Add(New ChoCSVRecordFieldConfiguration("ID", 1) With {.FieldName = "Id"})
            config.CSVRecordFieldConfigurations.Add(New ChoCSVRecordFieldConfiguration("Name", 2))
`
Instead of instead of the POCO object it works
`<ChoCSVFileHeader()>
<ChoCSVRecordObject(",")>
Public Class EmployeeRecSimple
    <ChoCSVRecordField(1)>
    Property ID As Integer
    <ChoCSVRecordField(2)>
    Property Name As String

End Class`

**Comment by TM458** [comment]
Any time frame of getting this fixed? Looks like the issues come from the Validate functions
                if (QuoteField == null)
                    QuoteField = config.QuoteAllFields;
This will always set QuotedFields to False and not allow them to be auto detected

**Comment by Cinchoo** [comment]
I'm seeing expected result. 

```
        public class EmployeeRecSimple
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        static void QuotesIssue()
        {
            List<EmployeeRecSimple> objs = new List<EmployeeRecSimple>()
            {
                new EmployeeRecSimple() { Id = 20, Name = "John Smith" },
                new EmployeeRecSimple() { Id = 21, Name = "Jack in \"Da Box" }
            };
            Console.WriteLine(ChoCSVWriter<EmployeeRecSimple>.ToTextAll(objs));
        }
```

Output:
```

20,John Smith
21,"Jack in ""Da Box"
```

Am I missing something?

**Comment by TM458** [comment]
Try this
`
    [ChoCSVFileHeader()]
    [ChoCSVRecordObject(",")]
    public partial class EmployeeRecSimple
    {
        [ChoCSVRecordField(1)]
        public int Id { get; set; }
        [ChoCSVRecordField(2)]
        public string Name { get; set; }
    }
        static void QuotesIssue()
        {
            List<EmployeeRecSimple> objs = new List<EmployeeRecSimple>()
            {
                new EmployeeRecSimple() { Id = 20, Name = "John Smith" },
                new EmployeeRecSimple() { Id = 21, Name = "Jack in ,Da Box" }
            };
            Console.WriteLine(ChoCSVWriter<EmployeeRecSimple>.ToTextAll(objs));
        }
`

**Comment by Cinchoo** [comment]
Whats wrong with this exercise? The framework is outputting csv file as expected.

```
20,John Smith
21,"Jack in ,Da Box"
```
Can you elaborate the issue you are facing?

**Comment by TM458** [comment]
This is  what I am getting
`
20,John Smith
21,Jack in ,Da Box
`

**Comment by Cinchoo** [comment]
Yes, I can produce it. I'm putting fix shortly.

**Comment by Cinchoo** [comment]
applied the fix, pushed to github.

Nuget will be pushed by end of this week.

**Comment by Cinchoo** [comment]
@TM458 , can you please confirm the fix is working or not. let me know so I can close this ticket.

**Comment by OxEMoron** [comment]
No, I just submitted the ticket.

**Comment by liamvinova** [comment]
@Cinchoo I have issue with "," inside """, could you please to help me?
I have value: 
```
Vessel,VoyNo,Category,Seq,Remark,Last Update Gmt,User
Affinity V,14,1,9,"TCE 7,814 pnl correct.",2020-11-02T18:00:16,william.bennett
```
but when I parse data, `"TCE 7,814 pnl correct."` understand as two columns.
My version use is 1.2.1.1.

**Comment by Cinchoo** [comment]
U must use `QuoteAllFields()` when loading csv file

```
            using (var r = ChoCSVReader.LoadText(csv)
                .QuoteAllFields()
                .WithFirstLineHeader()
                )
            {
                foreach (var rec in r)
                    Console.WriteLine(rec.Dump());
            }
```

**Comment by liamvinova** [comment]
Yeah, it work for me, thank you!
