### ISSUE TITLE
How to use LoadText with ChoJsonReader

### ISSUE THREAD

**Issue by janelett** [Cinchoo/ChoETL#100]
Hi @Cinchoo 

i want to transformer a json from an api to csv but i have no file.
In the test files of ChoETL i saw the function LoadText that does this but when i try to use it i get the error "ChoJsonReader" contains no definition for "LoadText".
Im new to C#, so i would be happy for a little guidance thank you

For example:

    using (var p = ChoJSONReader.LoadText(json))

does not work

**Comment by Cinchoo** [comment]
Can u pls be more specific with sample? What value `json` variable is holding?

FYI, `LoadText` helper method used to parse json text value. If you want to open json file, you must use one of the ChoJSONReader constructor (`new ChoJSONReader(@"c:\temp\sample.json")`)

**Comment by janelett** [comment]
@Cinchoo 
ar s = ChoCSVReader.LoadText(json); -> works !!
var p =ChoJSONReader .LoadText(json) -> LoadText is not definied

json variable is a string, but that should not matter since my IDE tells me that LoadText is not definied for ChoJSONReader but for ChoCSVReader it works.

**Comment by Cinchoo** [comment]
Hard to believe `ChoJSONReader` is internal class as you pointed out. Are you sure you have right source to begin with?

Are you using nuget package / working with source?

**Comment by janelett** [comment]
@Cinchoo 
now when i create a new project whole ChoJSONReader is not definied lol. But CSVReader works.

i do the following in visual studio community 2019 edition
- create new project (Console App(.NET Framework))
- then in nuget package manager console "Install-Package ChoETL"
- then i get the error "CS0234	The type or namespace name 'ChoJSONReader' does not exist in the namespace 'ChoETL' (are you missing an assembly reference?)"


 the code looks the following:

using System;
using ChoETL;


namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var s = ChoETL.ChoCSVReader.LoadText("");
            var a = ChoETL.ChoJSONReader.LoadText("");


            Console.WriteLine("Hello World!");
        }
    }
}

**Comment by Cinchoo** [comment]
You need to install `ChoETL.JSON` nuget package instead of `ChoETL`. Let me know.

**Comment by janelett** [comment]
thanks that worked!
