### ISSUE TITLE
Values bigger than max integer value leaving columns out of output file 

### ISSUE THREAD

**Issue by JoelJuntunen** [Cinchoo/ChoETL#104]
I am running into an issue where I have a JSON with a large amount of columns and the output file only reads the first 46 headers, leaving the rest out of the CSV file.

I am using the following code to write the file
            using (var r = new ChoJSONReader(jsonPath))
            {
                using (var w = new ChoCSVWriter(csvFilePath).WithFirstLineHeader())
                {
                    w.Write(r);
                }
            }

**Comment by Cinchoo** [comment]
Is there any error reported?

Turn on trace mode, to capture any failure. Put this line at Main() method.

`ChoETLFrxBootstrap.TraceLevel = System.Diagnostics.TraceLevel.Verbose;`

**Comment by JoelJuntunen** [comment]
No error reported to console by trace mode.

Just the (what I'm assuming is the) regular output:
Determining 'C:\projects\redacted\JSONTEST.json' file encoding...
Found 'System.Text.UTF8Encoding+UTF8EncodingSealed' encoding in 'C:\projects\redacted\JSONTEST.json' file.
Loading node [1]...
Writing [1] object...
Loading node [2]...
Writing [2] object...
etc.
@Cinchoo

**Comment by JoelJuntunen** [comment]
Upon further inspection into the issue it turns out that it is not about the number of columns but the value stored in the JSON.
It seems that when encountering a value bigger than an integer can store, the writer skips any columns after that column that held the value.

Example:
Source:
`[{
"column_one": "value",
"column_two": 200,
"column_three": 3000000000,
"column_four": "value_2"
}]`
Output:
`column_one;column_two
value;200`

In this example since the value of column_three is more than the integer max value, column three and four would not end up in the CSV output file at all.

Is there a workaround for this? @Cinchoo

**Comment by Cinchoo** [comment]
Workaround is handle the field value explicitly using callback machanism.

```
            string json = @"[{ ""column_one"": ""value"", ""column_two"": 200, ""column_three"": 3000000000, ""column_four"": ""value_2"" }]";

            StringBuilder csv = new StringBuilder();
            using (var r = ChoJSONReader.LoadText(json)
                .Setup(s => s.BeforeRecordFieldLoad += (o, e) =>
                {
                    if (e.PropertyName == "column_three")
                    {
                        e.Source = (long)((JValue)e.Source).Value;
                    }
                })
                )
            {
                using (var w = new ChoCSVWriter(csv).WithFirstLineHeader())
                {
                    w.Write(r);
                }
            }

            Console.WriteLine(csv.ToString());
```

On the next release, will be handling all whole number as `long` type.
