### ISSUE TITLE
CSVReader errors on windows when CSV has Unix line endings

### ISSUE THREAD

**Issue by jwomackgsa** [Cinchoo/ChoETL#107]
My console app using the ETL library in dotnet core 3.1.  I have recently run into an issue when the console app is running on windows platform and the CSV file comes in with Unix line endings (LF).  When that happens it blows up on the header line read.  When I bring this app over to my mac, I can run through both Unix(LF) and Windows (CRLF) line endings on the CSV with no issues.  Is this a possible bug or do I need to some pre-validation on the input CSV for its line endings when running on windows to ensure the file comes in with Windows EOLs?

**Comment by Cinchoo** [comment]
Use `WithEOLDelimiter` if you want to override the standard line delimiter.

**Comment by jwomackgsa** [comment]
Ok so I will need to detect line endings on the incoming file and then use that config handle the Unix EOLS if that happens.
Thanks
