### ISSUE TITLE
Use WithColumns to fix Duplicate Column Names in CSV ?

### ISSUE THREAD

**Issue by drmcclelland** [Cinchoo/ChoETL#110]
I was reading the **excellent** article [Cinchoo ETL - CSV Reader](https://www.codeproject.com/Articles/1145337/Cinchoo-ETL-CSV-Reader) and came across the FAQ 22.7. How to handle duplicate CSV columns? 

It mentions a method `WithColumns` that does not seem to be in the current codebase:

> Alternatively, you can provide column name overrides via configuration as below to access them by name

```
using (var parser = new ChoCSVReader("emp.csv").WithFirstLineHeader(true)
     .WithColumns("Id,Date,Account,Amount,Subcategory,Memo,Memo1"))
{
    foreach (var t in parser)
    {
        Console.WriteLine(t.Memo);
        Console.WriteLine(t.Memo1);
    }
}
```

Has the `WithColumns` method been renamed, or is there another approach that I should use?  I'm just trying to read the CSV file straight into a DataTable without using a POCO.

**Comment by Cinchoo** [comment]
Yes, it is obsolete. I'll correct the article.

Use as below

```
using (var parser = new ChoCSVReader("emp.csv").WithFirstLineHeader(true)
     .WithColumns("Id","Date","Account","Amount","Subcategory","Memo","Memo1"))
{
    foreach (var t in parser)
    {
        Console.WriteLine(t.Memo);
        Console.WriteLine(t.Memo1);
    }
}
```

**Comment by drmcclelland** [comment]
Thanks, that works!
