### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Cinchoo/ChoETL#112]
I was about to try this with a .net standard project that will run on multiple platforms but noticed it requires a few dependencies that are Windows specific, is the .net Standard edition compatible with the Linux platform? (I'm looking at converting a JArray to a CSV file)

**Comment by Cinchoo** [comment]
Use

`Install-Package ChoETL.JSON.NETStandard -Version 1.2.1.2`

**Comment by WhatFreshHellIsThis** [comment]
Awesome, thank you!

**Comment by WhatFreshHellIsThis** [comment]
Have confirmed, works in Docker Alpine Linux vm with  .net standard 5 rc2, no issues.  Thank you again @Cinchoo
