### ISSUE TITLE
JArray to CSV?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Cinchoo/ChoETL#113]
I need to convert various JArray collections to CSV.   

I tried directly using ChoCSVWriter to Write the JArray but even though it compiled there were numerous errors and crashes at runtime so I instead tried converting the JArray to an array of dynamic objects via JsonConvert.DeserializeObject<System.Dynamic.ExpandoObject> and then passing that to ChoCSVWriter and that worked very well and produced clean csv however it adds overhead doing the conversion this way with the extra step to an list of dynamic.

Is there a simpler way to directly generate CSV from any JArray?

**Comment by Cinchoo** [comment]
Library can't take JArray to output CSV.

Instead use `ChoJSONReader` to load the JSON and pass it to CSV.

Pls post sample if you can.

**Comment by Cinchoo** [comment]
sample

```
string json = @"[
{
""column_a"": 1,
""column_b"": 2,
""column_c"": 3
},
{
""column_a"": 11,
""column_b"": 21,
""column_c"": 31
}
]";

StringBuilder csv = new StringBuilder();
using (var r = ChoJSONReader.LoadText(json))
{
    using (var w = new ChoCSVWriter(csv)
        .WithFirstLineHeader()
        )
        w.Write(w);
}
```

**Comment by WhatFreshHellIsThis** [comment]
ChoJSONReader parses text only though as far as I can tell.  I'm not working with raw text JSON, it's exported from business object collections as a JArray of objects so I would need to output it back to text from the JArray to use the ChoJSONReader which would introduce another step in the conversion.

Is this correct?

**Comment by Cinchoo** [comment]
ChoJSONReader works with Text / File / JTokens.

But I'm afraid there is no straight way to do it. Best you can do as below

```
        StringBuilder csv = new StringBuilder();
        using (var w = new ChoCSVWriter(csv)
            .WithFirstLineHeader()
            )
            w.Write(JArray.Parse(json).ToObject<List<ExpandoObject>>());
```

**Comment by WhatFreshHellIsThis** [comment]
Ok, thank you!

**Comment by Cinchoo** [comment]
Here is another way of doing it just in case

```
string json = @"[
{
""column_a"": 1,
""column_b"": 2,
""column_c"": 3
},
{
""column_a"": 11,
""column_b"": 21,
""column_c"": 31
}
]";

StringBuilder csv = new StringBuilder();
using (var r = ChoJSONReader.LoadJTokens(JArray.Parse(json)))
{
    using (var w = new ChoCSVWriter(csv)
        .WithFirstLineHeader()
        )
        w.Write(r);
}

Console.WriteLine(csv.ToString());
```
