### ISSUE TITLE
Not all columns are displayed.

### ISSUE THREAD

**Issue by oleg-snt** [Cinchoo/ChoETL#114]
Good afternoon. I have a problem processing this library. Version 1.2.1.1

`
[{"DigiKeyPartNumber":"296-19853-1-ND","Packaging":"Tape & Reel (TR)","Part_Status":"Active","Type":"Transceiver","Protocol":"RS232","Number_of_Drivers_Receivers":"2/2","Duplex":"Full","Receiver_Hysteresis":"300mV","Data_Rate":"250kbps","Voltage_Supply":"3V ~ 5.5V","Operating_Temperature":"-40°C ~ 85°C","Mounting_Type":"Surface Mount","Package_Case":"16-SSOP (0.209\", 5.30mm Width)","Supplier_Device_Package":"16-SSOP","Base_Part_Number":"MAX323"},{"DigiKeyPartNumber":"495-77678-ND","Packaging":"Bulk","Part_Status":"Active","Capacitance":"47000µF","Tolerance":"±20%","Voltage_Rated":"40V","ESR_Equivalent_Series_Resistance_":"12mOhm @ 100Hz","Lifetime_Temp_":"12000 Hrs @ 85°C","Operating_Temperature":"-40°C ~ 85°C","Polarization":"Polar","Ratings":"-","Applications":"General Purpose","Ripple_Current_Low_Frequency":"13A @ 100Hz","Impedance":"10 mOhms","Lead_Spacing":"0.874\" (22.20mm)","Size_Dimension":"2.032\" Dia (51.60mm)","Height_Seated_Max_":"3.177\" (80.70mm)","Surface_Mount_Land_Size":"-","Mounting_Type":"Chassis Mount","Package_Case":"Radial, Can - Screw Terminals"}]
`

Such code C #

`

string json = "";

using (var r = ChoJSONReader.LoadText(json))
{
    using (var w = new ChoCSVWriter("sample.csv").WithFirstLineHeader())
    {
        w.Write(r);
    }
};

`

The code receives csv with the following columns:
`

DigiKeyPartNumber
Packaging
Part_Status
Type
Protocol
Number_of_Drivers_Receivers
Duplex
Receiver_Hysteresis
Data_Rate
Voltage_Supply
Operating_Temperature
Mounting_Type
Package_Case
Supplier_Device_Package
Base_Part_Number

`
The other columns are missing.
The total number of columns and their names in Json are unknown.

**Comment by Cinchoo** [comment]
In order to all fields from each JSON node, you should use JSONSerialization on the reader end, turn off the error on missing field on the writer end. Here is the sample how to do it


```
StringBuilder csv = new StringBuilder();
using (var r = ChoJSONReader.LoadText(json)
    .UseJsonSerialization()
)
{
    using (var w = new ChoCSVWriter(csv)
        .WithFirstLineHeader()
        .ThrowAndStopOnMissingField(false)
        .WithMaxScanRows(2)
        )
        w.Write(r);
}

Console.WriteLine(csv.ToString());

```

**Comment by oleg-snt** [comment]
Works great. Thank you.
