### ISSUE TITLE
Moving data from SQL  / CSV to MongoDB collections

### ISSUE THREAD

**Issue by papyr** [Cinchoo/ChoETL#116]
Since mongoDb is a schemaless, it would be nice if the Cinchoo could target MongoDB as a source instead of a table

Besides CSV, I found its powerful to move the data from one DB side to the other DB just by adding the correct drivers.

**Comment by Cinchoo** [comment]
This framework exposes ways to parse the data to DataTable / DataReader for integrating with various databases. 
You can take them along with database driver to export / import data.

**Comment by papyr** [comment]
Is there a way to add a _plug-in_  or something to change the source and sink targets for the data.
