### ISSUE TITLE
Two contradicting license files

### ISSUE THREAD

**Issue by guylevy** [Cinchoo/ChoETL#12]
Hi,

I noticed that there are two license files in the repo with different license terms:

1. https://github.com/Cinchoo/ChoETL/blob/master/License.txt (seems like a more recent one)
2. https://github.com/Cinchoo/ChoETL/blob/master/LICENSE (seems old and outdated)

NuGet Org points to the 2nd. Would be great if you can remove the old one and update the NuGet org link.

Cheers,
Guy

**Comment by Cinchoo** [comment]
Fixed it. Thanks for reporting.

**Comment by Cinchoo** [comment]
Pls close it if all good.

**Comment by guylevy** [comment]
Looks perfect, thanks!
