### ISSUE TITLE
CSV to Json help

### ISSUE THREAD

**Issue by modera70** [Cinchoo/ChoETL#121]
Hello everyone,

I'm trying to convert a CSV string to Json with the following code:

`string csv = @"id,personal_information/name
                             1,Edd";

            StringBuilder json = new StringBuilder();
            using (var w = new ChoJSONWriter(json))
            {
                using (var r = ChoCSVReader.LoadText(csv).WithFirstLineHeader()
                    .Configure(c => c.NestedColumnSeparator = '/')

                    )
                    w.Write(r);
            }
            Console.WriteLine(json.ToString());`

When I run my code I get the following result:

`[
  {
    "id": "1",
    "personal_information": {
      "name": "Edd"
    }
  }
]`

I'm looking for a way to get the **id** property as a numeric value, something like this:

`[
  {
    "id": 1,
    "personal_information": {
      "name": "Edd"
    }
  }
]`

Do you know if there is a way to get the id property as a number? 

Regards.

**Note**:I'm using the package ChoETL.JSON v1.2.1.4.

**Comment by Cinchoo** [comment]
Use `WithMaxScanRows` to determine fieldtype automatically by the framework.

```
            StringBuilder json = new StringBuilder();
            using (var w = new ChoJSONWriter(json))
            {
                using (var r = ChoCSVReader.LoadText(csv).WithFirstLineHeader()
                    .Configure(c => c.NestedColumnSeparator = '/')
                    .WithMaxScanRows(1)
                    )
                    w.Write(r);
            }
            Console.WriteLine(json.ToString());
```

**Comment by modera70** [comment]
Thank you so much for your answer, it worked!!
