### ISSUE TITLE
Adding a Flush method on Parquet Writer

### ISSUE THREAD

**Issue by cesarguinovart** [Cinchoo/ChoETL#122]
I would like to add the following code to the ChoParquetWriter:
        public void Flush()
        {
            if (_streamWriter != null)
                _streamWriter.Flush();
        }

Not sure if this will achieve the flushing to the stream of all the data written, however my problem currently is that until i Dispose/Close the ChoParquetWriter, the data is not written to the stream, and the length of the stream is always 0 until Close is called.
This makes it hard to use if in the constructor i had passed a MemoryStream (instead of a File Stream)

once i dispose the object the data is all written but at that point i cant use my stream anymore .

**Comment by Cinchoo** [comment]
added and pushed to v1.0.1.1 package
