### ISSUE TITLE
can not read CSV file with header and empty field

### ISSUE THREAD

**Issue by Nithyananda-KanTime** [Cinchoo/ChoETL#123]
Hi
Sample file
ERROR_CODE|ERROR_DESCRIPTION|IS_FILE_ERROR|ERROR_SEVERITY|FILE_NAME|
F1004|File is a duplicate|TRUE|ERROR|TEST_VISITS_IA_270084601_20201202192520.csv|

This file will be downloaded from SFTP as stream so code convert is 

 public static JToken ConvertCsvStream(Stream stream)
        {
           
            using (StreamReader reader = new StreamReader(stream))
            {
                using (var csv=new ChoCSVReader(stream).QuoteAllFields().WithFirstLineHeader(false).WithDelimiter("|"))
                {
                    return JToken.FromObject(csv);
               }
            }
        }

Error I am getting is
Atleast one of the field header is empty. Please check the field headers at [6].

**Comment by Cinchoo** [comment]
Because line ends with '|' delimiter, considers field after. In order to handle `.Configure(c => c.FileHeaderConfiguration.IgnoreColumnsWithEmptyHeader = true)` to process file successfully.

Here is working sample


```
string csv = @"ERROR_CODE|ERROR_DESCRIPTION|IS_FILE_ERROR|ERROR_SEVERITY|FILE_NAME|
F1004|File is a duplicate|TRUE|ERROR|TEST_VISITS_IA_270084601_20201202192520.csv|";

using (var r = ChoCSVReader.LoadText(csv)
    .QuoteAllFields().WithFirstLineHeader(false).WithDelimiter("|")
    .Configure(c => c.FileHeaderConfiguration.IgnoreColumnsWithEmptyHeader = true)
    )
{
    foreach (var rec in r)
    {
        rec.Remove("_Column1");
        Console.WriteLine(rec.Dump());
    }
}
```

**Comment by Nithyananda-KanTime** [comment]
Thank You,

This change worked for us
