### ISSUE TITLE
[Newbie question] How to read an object list as a subnode?

### ISSUE THREAD

**Issue by YannZeRookie** [Cinchoo/ChoETL#124]
Hello,
(foreword: please note that I am a beginner with C# and the ChoETL YAML, so be forgiving)

[Extending example 22.6](https://www.codeproject.com/Articles/5272376/Cinchoo-ETL-Yaml-Reader#22.6.HowtoloadselectivenodesfromYaml67), I am trying to read a subnode which is an array of `UserScore` objects rather than a list of simple integers:

```
    public class UserScore
    {
        public int id { get; set; }
        public int value { get; set; }
    }

    public class UserInfo
    {
        public string name { get; set; }
        public string teamname { get; set; }
        public string email { get; set; }
        public int[] players { get; set; }
        public UserScore[] scores { get; set; }
    }

static void SelectiveNodeTest()
                string yaml = @"
users:
    - name: 1
      teamname: Tom
      email: tom@gmail.com
      players: [1, 2]
      scores:
        - id: 1
          value: 100
        - id: 2
          value: 200
";
                using (var r = ChoYamlReader<UserInfo>.LoadText(yaml)
                    .WithYamlPath("$.users[*]")
                )
                {
                    foreach (var rec in r)
                        Console.WriteLine(rec.Dump());
                }
            }
        }
}
```
The `players` array fills up properly but the `scores` remains empty:
```
	name: 1
	teamname: Tom
	email: tom@gmail.com
	players: 
		[Count: 2]
		1
		2

	scores: [NULL]
```
What am I doing wrong?
Thanks in advance!

**Comment by Cinchoo** [comment]
It is bug. Will be putting a fix shortly. 

Thanks for reporting it.

**Comment by Cinchoo** [comment]
v1.0.0.7 pushed with fixes. Please take the latest and try it. Thanks.

**Comment by YannZeRookie** [comment]
It works, this is very cool, thanks so much for your speed!

Keep up the great lighting-fast work!
