### ISSUE TITLE
Documentation Suggestions

### ISSUE THREAD

**Issue by YannZeRookie** [Cinchoo/ChoETL#127]
Hello there,

I made great progress with the YAML reader, and I am very happy with the results! So thanks again for all this hard work and again, for your responsiveness.

As a C# and ChoETL beginner, I stumbled on a few (basic?) questions, so I thought I would write down the documentation pieces that would have helped me at the time. Feel free to add/edit/ignore them to the FAQ at https://www.codeproject.com/Articles/5272376/Cinchoo-ETL-Yaml-Reader 

At least these will show you where my difficulties were :)

Hoping this helps, and keep the great work!
Cheers,
-Yann

-----

### 22.15 Reading an entire file - Using a simple data structure

Often you need to read the entire content of a file, so using a YAML Path filter does not help. What you want to do is to map your YAML file to a data structure that you can use directly:

```
class PersonData
{
    public DateTime Creation { get; set; }
    public string Firstname { get; set; }
    public string Lastname { get; set; }
    public int Age { get; set; }
}

static void ReadEntireFile1()
{
    string yaml = @"
creation: 2020-12-26
firstname: John
lastname: Doe
age: 35";
    using (var parser = ChoYamlReader<PersonData>.LoadText(yaml))
    {
        foreach (var e in parser)
        {
            Console.WriteLine(e.Firstname); // John
            Console.WriteLine(e.Lastname);  // Doe
        }
    }
```

### 22.16 Reading an entire file - Using Mulitple Lists

Often you have a file that contain multiple lists. These are simply defined using arrays of different structures.

```
    class ChildData
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public DateTime Dob { get; set; }
    }
    class AddressData
    {
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
    }
    class ParentData
    {
        public DateTime Creation { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }
        public ChildData[] Children  { get; set; }
        public AddressData[] Addresses  { get; set; }
    }

    static void ReadEntireFile2()
    {
        string yaml = @"
creation: 2020-12-26
firstname: John
lastname: Doe
age: 35
children:
- firstname: Emmanuel
  lastname: Doe
  dob: 1990-01-02
- firstname: Elise
  lastname: Doe
  dob: 1996-10-02
addresses:
- street: 1234 California Ave
  city: San Francisco
  state: CA
  zip: 98765
  country: USA
- street: 666 Midtown Ct
  city: Palo Alto
  zip: 94444
  state: CA
  country: USA
";
        using (var parser = ChoYamlReader<ParentData>.LoadText(yaml))
        {
            foreach (var e in parser)
            {
                Console.WriteLine(e.Firstname); // John
                Console.WriteLine(e.Lastname);  // Doe
                Console.WriteLine(e.Children[0].Firstname); // Emmanuel
                Console.WriteLine(e.Addresses[0].Street);   // 1234 California Ave
            }
        }
    }
```

### 22.17 Using generic data structures (IDictionnary)

Even though it is more cumbersome and will probably not be used except in some very specific cases (see FAQ 22.19), it is useful to understand the logic of the ChoYamlReader and how it deals with what it reads. Here is the same content as in 12.15, but without assuming anything on the file. Note the ugly casts and manual work that you have to perform to get to the values.

```
    static void ReadEntireFileAnonymous()
    {
        string yaml = @"
creation: 2020-12-26
firstname: John
lastname: Doe
age: 35";
        using (var parser = ChoYamlReader<IDictionary<string, object>>.LoadText(yaml))
        {
            foreach (var e in parser)
            {
                string firstname = (string) e["firstname"];                     // John
                DateTime creation = DateTime.Parse((string) e["creation"]);     // 2020-12-26
                int age = (int) e["age"];                                       // 35
                Console.WriteLine(e.Dump());
            }
        }
    }

```

### 22.18 Using generic data lists (IList)

Under the same idea, you can read lists of anonymous data. Here again, this example is just here to explain how it works under the hood, the use of arrays as described in 22.16 is safer and more convenient.

```
    class ChildrenData
    {
        public IList<object> Children { get; set; }
    }
    
    static void ReadAnonymousLists()
    {
        string yaml = @"
children:
- firstname: Emmanuel
  lastname: Doe
  dob: 1990-01-02
- firstname: Elise
  lastname: Doe
  dob: 1996-10-02
";
        using (var parser = ChoYamlReader<ChildrenData>.LoadText(yaml))
        {
            foreach (var e in parser)
            {
                IDictionary<object, object> firstChild = (IDictionary<object, object>) e.Children[0];
                string firstname = (string) firstChild["firstname"];	// Emmanuel
                Console.WriteLine(e.Dump());
            }
        }
    }
```

### 22.19 Reading an entire file - Dynamic structures

Sometimes, the file format can vary greatly and contains non-homogeneous data at the same level. We won't go into the debate of whether this is good practise or not, but here are some realities of computer science at times.

For example, here we have a list of possessions that have a `type` field and attributes that depend on the type of object. Combining 22.17 and 22.18, this gives:

```
    class OwnerData
    {
        public PossessionData[] Possessions { get; set; }
    }

    class PossessionData
    {
        public string Type { get; set; }
        public IDictionary<string, object> Description  { get; set; }
    }

    static void ReadDynamicData()
    {
        string yaml = @"
possessions:
- type: car
  description:
    color: blue
    doors: 4
- type: computer
  description:
    disk: 1 TB
    memory: 16 MB
";
        using (var parser = ChoYamlReader<OwnerData>.LoadText(yaml))
        {
            foreach (var e in parser)
            {
                string carColor = (string) e.Possessions[0].Description["color"];   // blue
                foreach (var p in e.Possessions)
                {
                    Console.WriteLine(p.Description.Dump());
                }
            }
        }
    }

```

**Comment by Cinchoo** [comment]
Thanks for the suggestion and input. Gladly update the article with your info. Thx again.

**Comment by Cinchoo** [comment]
Updated the article. Check it out. Thx again for your help.

**Comment by YannZeRookie** [comment]
Wow that was fast! :-)
Just one thing I noticed: inside the YAML strings, the starting spaces (indentation) were lost in the copy/paste process. You want to fix this, otherwise they samples won't make sense (and won't work either).

**Comment by Cinchoo** [comment]
Corrected, Let me know.

**Comment by YannZeRookie** [comment]
Looks great, thanks!
