### ISSUE TITLE
Reading CSV into POCO with configuration doesn't load

### ISSUE THREAD

**Issue by jwomackgsa** [Cinchoo/ChoETL#13]
When I use the following code, the CSV doesn't load into the POCO.  After removing the the configuration parameter on the ChoCSVReader call on the Reader it loads just fine into the POCO.

```
            ChoCSVRecordConfiguration etlConfig = new ChoCSVRecordConfiguration();
            etlConfig.MayContainEOLInData = true; //Handling for multi-line values in CSV
            etlConfig.IsDynamicObject= false;
            var reader = new ChoCSVReader<SF1150>(csvData,etlConfig).WithFirstLineHeader();
            foreach (var e in reader)
            {            
                Console.WriteLine(String.Format("Id: {0}", e.Name));
                Console.WriteLine(String.Format("Name: {0}", e.Type));
                Console.WriteLine(String.Format("Name: {0}", e.BLOCK_CURR));
            }
```

If I remove etlconfig from the reader it loads into the object just fine.  Is this a bug or am I doing something wrong with the preconfiguration.  The intent is to use field attributes against my POCO properties to match the csv headers that are being loaded.

**Comment by Cinchoo** [comment]
Fixed, please pull the latest package. Thanks for reporting it.

**Comment by jwomackgsa** [comment]
Ok, pulled down ChoETL.NETStandard Version=1.0.1.7.  Now I am getting an error that it doesn't seem to be mapping fieldname attributes.  Here is code I am using.

`
        [ChoCSVRecordField(1, FieldName = "NAME")] 
        public string Name {get; set;}

        [ChoCSVRecordField(2, FieldName = "SSN")]
        public string SSN {get; set;}

        [ChoCSVRecordField(3, FieldName = "BLOCK_CURR")]
        public string AgencyUse {get; set;}

ChoCSVRecordConfiguration etlConfig = new ChoCSVRecordConfiguration();
etlConfig.MayContainEOLInData = true; //Handling for multi-line values in CSV        
var reader = new ChoCSVReader<SF1150>(csvData,etlConfig).WithFirstLineHeader();
`

CSV Data
`
"NAME","SSN","BLOCK_CURR"
"PARKER, PETER A","111-22-3333","OM121"
"PARKER, PETER A","111-22-3333","OM121"
`

Error thrown
`1) Exception Information
*********************************************
Exception Type: ChoETL.ChoMissingRecordFieldException
Message: Missing 'NAME' property in pdffillerdncore.SF1150 type.
Data: System.Collections.ListDictionaryInternal
TargetSite: Boolean FillRecord(System.Object, System.Tuple`2[System.Int64,System.String])
HelpLink: NULL
Source: ChoETL.Core
HResult: -2146232832
`

**Comment by Cinchoo** [comment]
Found the issue, fixed it. Pushed the binary to Nuget. Get the latest. Let me know.

Thanks again for reporting it.

**Comment by Cinchoo** [comment]
Pls close it if all good.

**Comment by jwomackgsa** [comment]
Thanks for the quick fixes.  Seems to all be working!
