### ISSUE TITLE
cannot read French chars

### ISSUE THREAD

**Issue by hulin99** [Cinchoo/ChoETL#132]
I tried to read a csv file with french chars.
I set up encoding as windows-1254.
ChoEtl failed to identify french chars.
This csv can be read correctly with csvhelper
I also read it with PS , encoding.default.
However ChoEtl failed when i directly used filename as parameter

But It's working when i use stream instead
 using var s = new StreamReader("test.csv" , Encoding.GetEncoding("windows-1254"));
 using var p = new ChoCSVReader(s).WithFirstLineHeader().WithDelimiter(";");
return p.AsDataTable();

**Comment by Cinchoo** [comment]
are you facing in .NET framework / .NET core?

**Comment by hulin99** [comment]
i am using DotNet5
It's not working when i set up encoding after ChoCSVReader object is created like sample in codeproject
using var p = new ChoCSVReader("test.csv" ).WithFirstLineHeader().WithDelimiter(";");
p.Configuration.Encoding = Encoding.GetEncoding("windows-1254");
return p.AsDataTable();

however  it's ok when encoding is used as parameter in Constructor.
like 
using var p = new ChoCSVReader("test.csv", new ChoCSVRecordConfiguration { Encoding = Encoding.GetEncoding("windows-1254") }).WithFirstLineHeader().WithDelimiter(";");
return p.AsDataTable();


I guess that file is opened when this ChoCSVReader object is created.Thus, new encoding setting is useless afterwards.

**Comment by Cinchoo** [comment]
Put a fix for it. Released new package v1.2.1.10

**Comment by hulin99** [comment]
It is fixed.thanks
