### ISSUE TITLE
Missing close square bracket in JSON string when using ChoJSONWriter and StringBuilder

### ISSUE THREAD

**Issue by sebastianluo** [Cinchoo/ChoETL#133]
The following code generates a JSON string without closing bracket:

            List<ExpandoObject> objs = new List<ExpandoObject>();
            dynamic rec1 = new ExpandoObject();
            rec1.Id = 1;
            rec1.Name = "Mark";
            objs.Add(rec1);

            dynamic rec2 = new ExpandoObject();
            rec2.Id = 2;
            rec2.Name = "Jason";
            objs.Add(rec2);

            StringBuilder sb1 = new StringBuilder();
            using (var wtr = new ChoJSONWriter(sb1))
            {
                wtr.Write(objs);
                var json_missing_closing_square_bracket = sb1.ToString();
            }

![image](https://user-images.githubusercontent.com/5547110/109562852-c8a57580-7a93-11eb-8502-3bbc4c7eff64.png)

**Comment by Cinchoo** [comment]
`ToString()` must be outside of JSONWriter scope.

Here is working sample

```
        using (var wtr = new ChoJSONWriter(sb1))
        {
            wtr.Write(objs);
        }

            var json_missing_closing_square_bracket = sb1.ToString();

```

**Comment by sebastianluo** [comment]
Fantastic!

Thank you
