### ISSUE TITLE
CSV writing adds double quotes to serialized field

### ISSUE THREAD

**Issue by MarcolinoPT** [Cinchoo/ChoETL#134]
Hi,

I'm using v1.2.1.11 to write a collection of objects to a CSV file.
One of these fields is a string, a Dictionary<string, object> type serialized to JSON that when saved to a CSV file gets double quotes added to the keys, e.g. `{""AGE"":""24""}`.
My current configuration is
```csharp
using (var csv = new ChoCSVWriter<T>(streamWriter))
{
    csv.WithDelimiter(";")
       .QuoteAllFields(flag: false)
       .Write(rows);
}
```

Is there a way to alter the configuration so the end result of the serialized field does not get changed and results in `{"AGE":"24"}`?
My use case: the CSV is copied into a database and then the content of that field needs to be deserialized back but due to extra double quoting it throws an exception.

Thanks in advance!

**Comment by Cinchoo** [comment]
I'm sorry, can't follow you. 

1. What is <T> in ChoCSVWriter<T>?
2. Were you trying to convert JSON to CSV?
3. What is the source data? JSON / CSV?
4. What is the expected output?

**Comment by MarcolinoPT** [comment]
1. T is 
```csharp
class MyClass{
 public long A
public long B
public long C
public string Data
}
```
2. No, a list of MyClass to CSV
3. A list of objects, e.g. List<MyClass>
4. 1, 2, 3, { "key": "value"}
The problem is the output is 1, 2, 3, { ""key"": ""value""}

**Comment by Cinchoo** [comment]
Got it, here is how to do it

```
            StringBuilder csv = new StringBuilder();

            using (var w = new ChoCSVWriter<MyClass>(csv)
                .WithFirstLineHeader()
                .QuoteAllFields(false)
                .Configure(c => c.QuoteChar = '`')
                )
            {
                w.Write(new MyClass
                {
                    A = 1,
                    B = 2,
                    C = 3,
                    Data = @"{ ""key"": ""value""}"
                });
            }

            Console.WriteLine(csv.ToString());
```

**Comment by MarcolinoPT** [comment]
Works like a charm! Thank you very much! :)
