### ISSUE TITLE
ChoFixedLengthReader always return exception: TextReader is null

### ISSUE THREAD

**Issue by ASCSolution** [Cinchoo/ChoETL#137]
It's worked on v1.1.0.2 but when I update to latest version (v1.2.1.12), ChoFixedLengthReader always return exception: TextReader is null. Please advise.
I have used sample from here for testing: https://www.codeproject.com/Articles/1166802/Cinchoo-ETL-FixedLengthReader

**Comment by Cinchoo** [comment]
Applied fix, released v1.2.1.14
