### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by ben18mk** [Cinchoo/ChoETL#140]
`System.IO.FileNotFoundException: 'Could not load file or assembly 'ChoETL.JSON.Core, Version=1.2.1.14, Culture=neutral, PublicKeyToken=04a575066740f857' or one of its dependencies. The system cannot find the file specified.'`

I am getting this exception when I am trying to call the a function from another project that works with ChoETL API.
It can not find ChoETL.JSON.CORE file? Nu-Get only installs ChoETL.JSON and that's it, not more.

I have installed ChoETL and ChoETL.JSON and I am using the .NET Framework.

How should I solve this error?

**Comment by Cinchoo** [comment]
Are you sure you are using .NET framework? Pls create new project, install just

`install-package ChoETL.JSON`

try and let me know

**Comment by ben18mk** [comment]
I opened a new project and it is ok there. Seams like my library that I called the function from was not .NET framework
