### ISSUE TITLE
Yaml reader: Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '', line 1, position 1.'

### ISSUE THREAD

**Issue by klaritan** [Cinchoo/ChoETL#142]
I'm getting this weird error for YAML ONLY deserializing.

Error: Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '', line 1, position 1.'

    [ChoYamlRecordObject]
    public class Root
    {
        [ChoYamlRecordField(FieldName = "config")]
        public Config Config { get; set; }
     }

    [ChoYamlRecordObject]
    public class Config 
    {
        [ChoYamlRecordField(FieldName = "enable")]
        public string TurnOnModel { get; set; }
    }

Here is the yaml file:

```
config:
    #  model.one or model.five
    enable: model.five
```

This is the source:

            ChoYamlRecordConfiguration config = new ChoYamlRecordConfiguration();
            config.ErrorMode = ChoErrorMode.ReportAndContinue;
            config.Encoding = Encoding.UTF8;

            using (var parser = new ChoYamlReader<Root>(scriptPath, config))
            {
                foreach (var e in parser) // ERROR HAPPENS HERE!
                {
                    return e;
                }
            }

The yaml file has been validated over 3 different validators.

Why is it throwing json-related error when my program doesn't even use them?
How would I fix this?

**Comment by klaritan** [comment]
It looks like this is a bug. Object (classes) members inside a class doesn't seem to parse at all?
Does this not support this...?

**Comment by Cinchoo** [comment]
Yes, it is bug. Applied fix, pushed new version v1.0.0.13

Grab it and let me know.

**Comment by klaritan** [comment]
Tried "Install-Package ChoETL.Yaml -Version 1.0.0.13".

No difference. Still getting same errors. Same yaml file is properly being deserialized with YamlDotNet or SharpYaml.

**Comment by Cinchoo** [comment]
Pls try to uninstall completely and reinstall the package.

Better try with new solution and see it works.

**Comment by klaritan** [comment]
We take measures to ensure latest package has been well installed.
That said, testing fresh new projects (.NET Core 3.1 or .Net 5.0) still has the exact same error.

**Comment by Cinchoo** [comment]
What is the error? 

I'm not able to reproduce it.


```
        [ChoYamlRecordObject]
        public class Root
        {
            [ChoYamlRecordField(FieldName = "config")]
            public Config Config { get; set; }
        }


        public class Config
        {
            [ChoYamlRecordField(FieldName = "enable")]
            public string TurnOnModel { get; set; }
        }

        static void Issue142()
        {
            string yaml = @"
config:
    #  model.one or model.five
    enable: model.five
";
            ChoYamlRecordConfiguration config = new ChoYamlRecordConfiguration();
            config.ErrorMode = ChoErrorMode.ReportAndContinue;
            config.Encoding = Encoding.UTF8;

            using (var parser = ChoYamlReader<Root>.LoadText(yaml, config))
            {
                foreach (var e in parser) // ERROR HAPPENS HERE!
                {
                    Console.WriteLine(e.Dump());
                }
            }
        }

```

**Output:**
```
-- ConsoleApp5.Program+Root State --
        Config:
                -- ConsoleApp5.Program+Config State --
                        TurnOnModel: model.five
```

Here are the library version / dependencies, you must have after refresh in your project

ChoETL.Core v1.2.1.17
ChoETL.JSON.Core v1.2.1.17
ChoETL.Yaml v1.0.0.13

**Comment by klaritan** [comment]
It seems to work for single member.
If we put more members in the Root class like this:

            [ChoYamlRecordField(FieldName = "config2")]
            public Config Config2 { get; set; }

They become NULL.

If we put another member (a container class that contains bool, double, TimeSpan (which we have converter set for), List<double>, Dictionary<string, string>, but nothing else), then the original Error: Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '', line 1, position 1.' pops up.

It seems the Yaml driver in this library has not been battle tested except for flat records.
We've been using YamlDotNet, but we go through a lot of hoops to validate the text. ChoETL seems to do this a lot better, but we're unable to get this to work at all. We're at least very willing to help you test it.

**Comment by Cinchoo** [comment]
Well, thx for your update.

`
        [ChoYamlRecordObject]
        public class Root142
        {
            [ChoYamlRecordField(FieldName = "config")]
            public Config Config { get; set; }
            [ChoYamlRecordField(FieldName = "config2")]
            public Config Config2 { get; set; }
        }
`
this works. 

Will I'll try container class contains various types. Will provide update.

Appreciate your help in testing this library for various scenarios. Your input always welcome.

**Comment by Cinchoo** [comment]
Here is comprehensive test of all possible types tested with

```
        [ChoYamlRecordObject]
        public class Root
        {
            [ChoYamlRecordField(FieldName = "config")]
            public Config Config { get; set; }
            [ChoYamlRecordField(FieldName = "config2")]
            public Config Config2 { get; set; }
            [ChoYamlRecordField(FieldName = "settings")]
            public Settings Settings { get; set; }
        }

        public class Settings
        {
            public bool TurnOn { get; set; }
            public double Price { get; set; }
            public TimeSpan Period { get; set; }
            [DisplayName("allNames")]
            public List<string> Names { get; set; }
            [DisplayName("cityMap")]
            public Dictionary<string, string> CityZipMap { get; set; }
        }

        public class Config
        {
            [ChoYamlRecordField(FieldName = "enable")]
            public string TurnOnModel { get; set; }
        }

        static void Issue142()
        {
            string yaml = @"
config:
    #  model.one or model.five
    enable: model.five
config2:
    #  model.one or model.five
    enable: model.six
settings:
    turnOn: true
    price: 102.211
    period: 00:00:20
    allnames: ['Tom', 'Mark' ]
    cityMap: 
        New York: 10010
";
            ChoYamlRecordConfiguration config = new ChoYamlRecordConfiguration();
            config.ErrorMode = ChoErrorMode.ReportAndContinue;
            config.Encoding = Encoding.UTF8;

            using (var parser = ChoYamlReader<Root>.LoadText(yaml, config))
            {
                foreach (var e in parser) // ERROR HAPPENS HERE!
                {
                    Console.WriteLine(e.Dump());
                }
            }
        }

```

All parsed and loaded fine.

Pls share your object model, how to reproduce the error. Thanks.

**Comment by klaritan** [comment]
```
using ChoETL;
using System.Text;
using System.Windows;

namespace Test
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            ChoYamlRecordConfiguration config = new ChoYamlRecordConfiguration();
            config.ErrorMode = ChoErrorMode.ReportAndContinue;
            config.Encoding = Encoding.UTF8;
            config.IgnoreFieldValueMode = ChoIgnoreFieldValueMode.Any;


            using (var parser = new ChoYamlReader<Root>("file.yaml", config))
            {
                foreach (var e in parser)
                {
                    MessageBox.Show(e.Dump() + "\n");
                }
            }


        }
    }

    [ChoYamlRecordObject]
    public class Root
    {
        [ChoYamlRecordField(FieldName = "version")]
        public string Version { get; set; }

        [ChoYamlRecordField(FieldName = "config")]
        public Config Exas { get; set; }

        [ChoYamlRecordField(FieldName = "test")]
        public Tester test { get; set; }

        [ChoYamlRecordField(FieldName = "test2")]
        public Tester test2 { get; set; }

    }

    public class Tester
    {
        [ChoYamlRecordField(FieldName = "cnf.assit")]
        public string Assit { get; set; }

        [ChoYamlRecordField(FieldName = "cnf.language")]
        public string Lang { get; set; } = "English";

        [ChoYamlRecordField(FieldName = "cnf.enable")]
        public string Layout { get; set; } = "model.two";

    }

    public class Config
    {
        [ChoYamlRecordField(FieldName = "cnf.assit")]
        public string Assit { get; set; }

        [ChoYamlRecordField(FieldName = "cnf.language")]
        public string Lang { get; set; } = "English";

        [ChoYamlRecordField(FieldName = "cnf.enable")]
        public string Model { get; set; } = "model.five";

    }
}
```

file contents:
```
version: 1.00

test:
    cnf.assit: Test1
    cnf.language: English1
    cnf.enable: Default1

tes2t:
    cnf.assit: Test2
    cnf.language: English2
    cnf.enable: Default2

config:
    cnf.assit: CCC
    cnf.language: English
    cnf.enable: Default
```

You just run that and it will throw "Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '', line 1, position 1.'"

**Comment by Cinchoo** [comment]
Found an issue, applied fix. Take v1.2.1.18 and try.

Let me know.
