### ISSUE TITLE
Question: How to handle empty strings when converting CSV to JSON?

### ISSUE THREAD

**Issue by ma9mwah** [Cinchoo/ChoETL#146]
I'm trying to convert 
`"col1","col2","col3"`
`"","2","3"`
`"","b","c"`
`"1","2","3"`
`"a","b","c"`

into json, but for the cells with no data it ignores them on the output

`[
  {
    "col2": "2",
    "col3": "3"
  },
  {
    "col2": "b",
    "col3": "c"
  },
  {
    "col1": "1",
    "col2": "2",
    "col3": "3"
  },
  {
    "col1": "a",
    "col2": "b",
    "col3": "c"
  }
`

For example, I would like it to have `"col1": "",  `

Currently the only config i'm using is `QuoteAllFields = true`, i've tried using NullValueHandling and NullValue but they don't seem to do anything for me. (which is probably me using the wrong syntax)

**Comment by Cinchoo** [comment]
Pls visit the below issue for the answer

CSV to Json - Empty fields not appearing #143

**Comment by ma9mwah** [comment]
thank you! that's perfect :)
