### ISSUE TITLE
CSV Reader makes empty space fields as DBNull

### ISSUE THREAD

**Issue by marius-stanescu** [Cinchoo/ChoETL#15]
I am trying to read a .csv file and passing it AsDataReader to a SqlBulkCopy command, but I get the error that a certain column doesn't allow DBNull values. But I checked the .csv file and the values for that column are ' ' (a white space).
Why does the reader convert it to null? How can I fix that?

**Comment by Cinchoo** [comment]
This is the default behavior. You can turn off this by setting IgnoreFieldValueMode to 'None'

Found a bug in the library not recognizing this flag. Fixed it, take the latest lib from nuget.

```
            var dr = ChoCSVReader.LoadText(csv)
                .WithFirstLineHeader()
                .Configure(c => c.IgnoreFieldValueMode = ChoIgnoreFieldValueMode.None)
                .AsDataReader();
```

**Comment by marius-stanescu** [comment]
Hello, I tried using that option, but it didn't work.

I work on a .NET Core application. so I'm using the ChoETL.NETStandard NuGet package. There are no updates for that one. Could you please fix this also in this package?

Thank you.

**Comment by Cinchoo** [comment]
Out on vacation. Will apply the fix on oct 15.

**Comment by Cinchoo** [comment]
Fix applied to ChoETL.NETStandard NuGet package. Take the copy, try it.

**Comment by Cinchoo** [comment]
Pls close the ticket if fix works

**Comment by marius-stanescu** [comment]
In the meantime, I used a different package for reading .csv files.
If I get the time, I'll try the update you made later today and close the issue if it works.

**Comment by marius-stanescu** [comment]
It seems to work correctly. Thank you.
