### ISSUE TITLE
Convert Dynamic Nested & complex JSON to CSV, nested json get as row value insted of seprate columns of all properties . 

### ISSUE THREAD

**Issue by bhuvanikul** [Cinchoo/ChoETL#150]
Hi There,

Thanks for developing such a flexible tool for reading & write CSV easily. 

I want to dump data Dynamic Nested & complex JSON into CSV from the different dynamic API calls. Refer below provide sample JSON in CSV columns we need Tags & friends columns as JSON format and another field we need as columns. This is just sample JSON it will change by API. 

`[
  {
    "_id": "6114a68e117ee5f37573caf3",
    "index": 0,
    "guid": "8e1d0c6f-bb0a-431d-a863-ecdde131745f",
    "isActive": true,
    "balance": "$3,950.56",
    "picture": "http://placehold.it/32x32",
    "age": 26,
    "eyeColor": "green",
    "tags": [
      "adipisicing",
      "duis",
      "adipisicing",
      "commodo",
      "ad",
      "do",
      "Lorem"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Small Whitfield"
      },
      {
        "id": 1,
        "name": "Hewitt Morris"
      },
      {
        "id": 2,
        "name": "Christian Schultz"
      }
    ]
  },
  {
    "_id": "6114a68e9ccb5579368ba3e1",
    "index": 1,
    "guid": "8a2a3561-84ed-4b1f-ad7d-74639fdee823",
    "isActive": false,
    "balance": "$2,652.53",
    "picture": "http://placehold.it/32x32",
    "age": 39,
    "eyeColor": "green",
    "tags": [
      "pariatur",
      "ad",
      "fugiat",
      "veniam",
      "esse",
      "culpa",
      "in"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Ingram Boyd"
      },
      {
        "id": 1,
        "name": "Cooke Morrison"
      },
      {
        "id": 2,
        "name": "Susie Lee"
      }
    ]
  },
  {
    "_id": "6114a68e2d387e89aa729327",
    "index": 2,
    "guid": "f084612d-1a17-4b1a-95a6-2d9a3fadb500",
    "isActive": false,
    "balance": "$3,235.98",
    "picture": "http://placehold.it/32x32",
    "age": 36,
    "eyeColor": "green",
    "tags": [
      "nulla",
      "est",
      "reprehenderit",
      "amet",
      "tempor",
      "nisi",
      "deserunt"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Winifred Haney"
      },
      {
        "id": 1,
        "name": "Darcy Chapman"
      },
      {
        "id": 2,
        "name": "Roth Witt"
      }
    ]
  }
]`

Expected Outcome:
![image](https://user-images.githubusercontent.com/22784161/129139712-3e651622-5c3d-4160-beec-660dd721540e.png)

Thank you!

**Comment by Cinchoo** [comment]
use the code below

```
StringBuilder csv = new StringBuilder();
using (var r = new ChoJSONReader("*** Your JSON file path ***"))
{
    using (var w = new ChoCSVWriter(csv)
        .WithFirstLineHeader()
        )
        w.Write(r);
}

Console.WriteLine(csv.ToString());
```

**Output:**

```
_id,index,guid,isActive,balance,picture,age,eyeColor,tags_0,tags_1,tags_2,tags_3,tags_4,tags_5,tags_6,friends_0_id,friends_0_name,friends_1_id,friends_1_name,friends_2_id,friends_2_name
6114a68e117ee5f37573caf3,0,8e1d0c6f-bb0a-431d-a863-ecdde131745f,True,"$3,950.56",http://placehold.it/32x32,26,green,adipisicing,duis,adipisicing,commodo,ad,do,Lorem,0,Small Whitfield,1,Hewitt Morris,2,Christian Schultz
6114a68e9ccb5579368ba3e1,1,8a2a3561-84ed-4b1f-ad7d-74639fdee823,False,"$2,652.53",http://placehold.it/32x32,39,green,pariatur,ad,fugiat,veniam,esse,culpa,in,0,Ingram Boyd,1,Cooke Morrison,2,Susie Lee
6114a68e2d387e89aa729327,2,f084612d-1a17-4b1a-95a6-2d9a3fadb500,False,"$3,235.98",http://placehold.it/32x32,36,green,nulla,est,reprehenderit,amet,tempor,nisi,deserunt,0,Winifred Haney,1,Darcy Chapman,2,Roth Witt
```

**Comment by bhuvanikul** [comment]
Thank you for your quick reply & guidence.

I have been thorugh your provided documention but our requiment is bit diffrent then above provided example. 

Diffrent is nested json array coming output as a seprate columns, but we need as JSON as it as please review above & below provided output format. 
![image](https://user-images.githubusercontent.com/22784161/129277798-f70f3f86-4dd9-4c5b-a404-b436e54d9018.png)


I appreciate your help & guidence.

Thanks

**Comment by Cinchoo** [comment]
Well, this call for custom serialization. One way to handle this is to apply value converter on those fields. Downside is, this will be specific to each json (can't generalize it for all json)

```
StringBuilder csv = new StringBuilder();
using (var r = new ChoJSONReader("Issue150.json")
    .WithField("_id")
    .WithField("index")
    .WithField("guid")
    .WithField("isActive")
    .WithField("balance")
    .WithField("picture")
    .WithField("age")
    .WithField("eyecolor")
    .WithField("tags", fieldType: typeof(JObject), valueConverter: o => JsonConvert.SerializeObject(((JToken[])o).First()))
    .WithField("friends", fieldType: typeof(JObject), valueConverter: o => JsonConvert.SerializeObject(((JToken[])o).First()))
    )
{
    using (var w = new ChoCSVWriter(csv)
        .WithFirstLineHeader()
        .Configure(c => c.QuoteChar = '\'')
        )
        w.Write(r);
}

Console.WriteLine(csv.ToString());
```

**Output:**

```
_id,index,guid,isActive,balance,picture,age,eyecolor,tags,friends
6114a68e117ee5f37573caf3,0,8e1d0c6f-bb0a-431d-a863-ecdde131745f,True,'$3,950.56',http://placehold.it/32x32,26,green,'["adipisicing","duis","adipisicing","commodo","ad","do","Lorem"]','[{"id":0,"name":"Small Whitfield"},{"id":1,"name":"Hewitt Morris"},{"id":2,"name":"Christian Schultz"}]'
6114a68e9ccb5579368ba3e1,1,8a2a3561-84ed-4b1f-ad7d-74639fdee823,False,'$2,652.53',http://placehold.it/32x32,39,green,'["pariatur","ad","fugiat","veniam","esse","culpa","in"]','[{"id":0,"name":"Ingram Boyd"},{"id":1,"name":"Cooke Morrison"},{"id":2,"name":"Susie Lee"}]'
6114a68e2d387e89aa729327,2,f084612d-1a17-4b1a-95a6-2d9a3fadb500,False,'$3,235.98',http://placehold.it/32x32,36,green,'["nulla","est","reprehenderit","amet","tempor","nisi","deserunt"]','[{"id":0,"name":"Winifred Haney"},{"id":1,"name":"Darcy Chapman"},{"id":2,"name":"Roth Witt"}]'
```

**Comment by bhuvanikul** [comment]
But problem is that we don't have strong type object because of many api all are dynamic JSON. So can not fix "WithField" and "Type"

**Comment by Cinchoo** [comment]
Here you go, the closest, more generic way to convert them

```
StringBuilder csv = new StringBuilder();
using (var r = new ChoJSONReader("Issue150.json")
    )
{
    using (var w = new ChoCSVWriter(csv)
        .WithFirstLineHeader()
        .Configure(c => c.QuoteChar = '\'')
        )
        w.Write(r.Select(r1 =>
        {
            IDictionary<string, object> dict = r1 as IDictionary<string, object>;
            foreach (var key in dict.Keys)
            {
                Type mt = r1.GetMemberType(key);
                if (mt != null && mt.IsSimple())
                {

                }
                else
                {
                    r1[key] = JsonConvert.SerializeObject(r1[key]);
                }
            }

            return r1;
        }));
}

Console.WriteLine(csv.ToString());
```

**Comment by bhuvanikul** [comment]
Thank you for your solutions.
