### ISSUE TITLE
ChoXmlReader Error At Version 1.2.1.23

### ISSUE THREAD

**Issue by wuming123057** [Cinchoo/ChoETL#153]
ChoXmlReader Error At version 1.2.1.23 
```
foreach (dynamic e in new ChoXmlReader("Emp.xml"))
    Console.WriteLine("Id: " + e.Id + " Name: " + e.Name);
```
Result:
`
Name is Not defined in ChoETL.ChoDynamicObject 
`

But ChoXmlReader  At version 1.2.1.11，is OK.

I used .NET Framework 4.7.4.

**Comment by Cinchoo** [comment]
Bug, applied fix. pushed new version v1.2.1.24.

Thanks for reporting it.

**Comment by wuming123057** [comment]
Thanks!
