### ISSUE TITLE
Error reading a Quoted CSV Field

### ISSUE THREAD

**Issue by BillEisenman** [Cinchoo/ChoETL#157]
Given:  "Av. Lázaro Cárdenas 1010 Residencial San Agustín, San Pedro Garza García. N.L. C.P. 66260"
Issue:  Data parser yields : \"Av. Lázaro Cárdenas 1010 Residencial San Agustín
when it should yield:  \"Av. Lázaro Cárdenas 1010 Residencial San Agustín, San Pedro Garza García. N.L. C.P. 66260\" as a Single Data Field
[[DL-20211009_30430951] apple_standard_fulfillment_2021-10-09 - Copy.csv](https://github.com/Cinchoo/ChoETL/files/7316259/DL-20211009_30430951.apple_standard_fulfillment_2021-10-09.-.Copy.csv)

**Comment by Cinchoo** [comment]
Use `QuoteAllFields` on CSVReader to handle this.

```
using (var r = new ChoCSVReader("*** YOUR CSV FILEPATH ***").QuoteAllFields())
{
}
```
