### ISSUE TITLE
XmlElement with attributes to dynamic object, how to access attribute as property?

### ISSUE THREAD

**Issue by 767267** [Cinchoo/ChoETL#16]
I have xml element with attributes
<Diagnostics>
<Diagnosis ID="1" EpisodeID="2" />  I am converting that to dynamic using the following code:
</Diagnostics>
using(ChoXmlReader<dynamic> reader = new ChoXmlReader("some.xml").WithXPath("Diagnostics"))
{
       foreach(dynamic record in reader)
       {
         //trying to access record.<property>
       }
}
I get an error when accessing "record.EpisodeID" but it fails. Any idea how I can make this work?

![image](https://user-images.githubusercontent.com/13524673/47770633-2976e480-dd06-11e8-9813-ee7714a7ce4e.png)

**Comment by Cinchoo** [comment]
FYI, key names are case sensitive. looking at the quick watch screenshot image, there are 25 keys present in the dynamic object. You can expand 'Keys' and check to see the field exists or not.

If you need more help, please post xml snippet.

**Comment by Cinchoo** [comment]
Pls close if all good.
