### ISSUE TITLE
Merge different CSV files into a single larger CSV file

### ISSUE THREAD

**Issue by elvaro** [Cinchoo/ChoETL#160]
Hi

I was wondering whether the ChoETL library can help with the following problem? I have multiple incoming csv files. They are not guaranteed to be of the same structure, as in the column count might vary. 

For example:
Cvs1:
col1, col2, col3
val1, val2, val3

Cvs2:
col1, col3
val4, val5

Cvs3:
col1, col4
val6, val7

And the expected output should be:
col1, col2, col3, col4
val1, val2, val3,
val4, , val5,
val6, , , val7

Is this possible?

**Comment by Cinchoo** [comment]
Yes, it is possible.

Pls see attached sample 

https://dotnetfiddle.net/0QnhyK

**Comment by Cinchoo** [comment]
Here is one another approach to merge large CSV files

https://dotnetfiddle.net/bPy7z7

Hope these samples help.

**Comment by elvaro** [comment]
Thanks for the help but what if there is not always a fixed amount of incoming files? Then I probably would somehow have to read in the files recursively, right?

**Comment by Cinchoo** [comment]
Yes, you need to take this approach and generalize it however you want it.

**Comment by elvaro** [comment]
For those interested here is a working example on how this might work in a more generalized approach:
```
public  class RecursiveCVSPrint
{
        List<ChoCSVReader<dynamic>> readersList = new List<ChoCSVReader<dynamic>>();
        public void printCSV(Stack<string> responses)
        {
            if (responses.Count > 1)
            {
                var response = responses.Pop();
                var cvsReader = ChoCSVReader.LoadText(response);
                using (cvsReader.WithFirstLineHeader().WithDelimiter(","))
                {
                    readersList.Add(cvsReader);
                    printCSV(responses);
                }
            }
            else
            {
                var response = responses.Pop();
                var cvsReader = ChoCSVReader.LoadText(response);
                using (cvsReader.WithFirstLineHeader().WithDelimiter(","))
                {
                    using (var w = new ChoCSVWriter(Console.Out)
                           .WithFirstLineHeader()
                           .WithDelimiter(",")
                           .WithMaxScanRows(10)
                           .ThrowAndStopOnMissingField(false)
                          )
                    {
                        w.Write(readersList.SelectMany(x => x).Concat(cvsReader));
                    }
                }
            }
        }
    }
```
Thanks for the assistance in this @Cinchoo
