### ISSUE TITLE
ChoETL.Parquet Method not found ChoETL.ChoFileRecordConfiguration.get_RecordSelector()

### ISSUE THREAD

**Issue by otebos** [Cinchoo/ChoETL#166]
Hi,

I'm using:
ChoETL.Parquet 1.0.1.12
ChoETL.NETStandard 1.2.1.28
Parquet.Net 3.9.1
.NET 5

While using plain Parquet.Net I'm able to open and navigate through my parquet file, when using ChoETL I get an exception as follows:
Method not found: 
```
'System.Func`2<System.Object,System.Type> ChoETL.ChoFileRecordConfiguration.get_RecordSelector()'.
   at ChoETL.ChoParquetRecordReader.<AsEnumerable>d__17.MoveNext()
   at ChoETL.ChoParquetRecordReader.<AsEnumerable>d__13.MoveNext()
   at ChoETL.ChoParquetReader`1.<>c__DisplayClass35_0.<GetEnumerator>b__0()
   at ChoETL.ChoEnumeratorWrapper.<BuildEnumerable>d__0`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 ```
I tried loop approach but not even one field can be read.
I tried to add a ChoParquetRecordConfiguration with implementation of RecordTypeSelector but method is not called, still the same exception is thrown.

My code:
```
public void Read2()
{
    var conf = new ChoParquetRecordConfiguration
    {
        RecordTypeSelector = RecordTypeSelector
    };
    var parquet = new ChoParquetReader("c:\\test.parquet", conf);
    var list = parquet.Select(x => x).ToList();
}

private Type RecordTypeSelector(object arg)
{
    throw new NotImplementedException();
}
```

**Comment by Cinchoo** [comment]
duplicate issue: #164

**Comment by otebos** [comment]
Yup, downgrading to ChoETL 1.2.1.21 fixed the issue.

**Comment by Cinchoo** [comment]
Latest release synced up all plug-ins. Take the latest and give it try.
