### ISSUE TITLE
MayContainEOLInData not working as expected?

### ISSUE THREAD

**Issue by atorres16** [Cinchoo/ChoETL#168]
Take this example:

```
"Header1","Header2","Header3"
"Value1","Val
ue2","Value3"
```
(Notepad++ screenshot)
![image](https://user-images.githubusercontent.com/19210281/146599568-c4930872-4698-4b2f-b9c1-0e216df2dbe7.png)

* All headers and values are quoted
* There's a line break in "Value2"

I've been playing with CHOETL options, but I can't get it to work:

```csharp
   foreach (dynamic e in new
                ChoCSVReader(@"test.csv")
                .WithFirstLineHeader()
                .MayContainEOLInData(true)
                .MayHaveQuotedFields()

                //been playing with these too
                //.QuoteAllFields()
                // .ConfigureHeader(c => c.IgnoreColumnsWithEmptyHeader = true)
                //.AutoIncrementDuplicateColumnNames()
                //.ConfigureHeader(c => c.QuoteAllHeaders = true)
                //.IgnoreEmptyLine()

                )
            {
                System.Console.WriteLine(e["Header1"]);
            }
```

This fails with:

```
Missing 'Header2' field value in CSV file
```
The error varies depending on the reader configuration

What is the correct configuration to read this text?

**Comment by Cinchoo** [comment]
It is bug, applied fix. Take the ChoETL.NETStandard.1.2.1.35-beta1 package and give it a try.

**Comment by Cinchoo** [comment]
Sample fiddle: https://dotnetfiddle.net/kF5bPO

**Comment by atorres16** [comment]
Thanks!
