### ISSUE TITLE
Versions after Nov26 1.2.1.30 failed when I upgraded

### ISSUE THREAD

**Issue by kevinj2016** [Cinchoo/ChoETL#169]
I upgraded the package to 1.2.1.34, and it failed to generate any content in my class object. My code has been working for many months and I didn't change anything else. When I reverted to v 1.2.1.30 Nov26, my code started loading XML files correctly again. I don't do anything fancy - I use a plain old class object with the code shown below. The same error occurred on more than a dozen different class objects in a dozen modules, so I'm pretty sure the issue is not in something I changed. <ConfigItem> is the name of the class object. Thank you.

 try {
      items = new ChoXmlReader<ConfigItem>(configPath).ToList();
    }
    catch (Exception ex) {
      var msg = $"{me} XML file read failed. '{configPath}'";
      LogMan.SendError(msg);
      msg = $"{me} '{ex.Message}'";
      LogMan.SendError(msg);
      return false;
    }

**Comment by Cinchoo** [comment]
Thanks for reporting, there was bug introduced after 1.2.1.30 causing it to fail. Applied fix. Pushed 1.2.1.35

Try and let me know.

**Comment by kevinj2016** [comment]
Thank you for fixing the bug so fast!
