### ISSUE TITLE
Unable to process large json file with nested or deep arrays with tonnes of (sensor) data.

### ISSUE THREAD

**Issue by r04drunn3r** [Cinchoo/ChoETL#170]
I have a large json file (around 16Gb) with the following structure:

```
{
"ControlJob": 
	{
		"Keys": 
		{ 
			"CtrJobID": "KE-CJ0000000409",
			"EquipmentID": "TEST01" 
		},
		"Attributes": 
		{
			"FileType": "SensorData",
			"JsonSchemaVersion": "Draft",
			"SensorDescriptions": 
			[
				{
					"SensorID": "1723007",
					"SVID": "1723007",
					"Group": "Temp",
					"SensorType": "Actual_01",
					"Name": "U",
					"DataType": "Double",
					"Units": "degC"
				},
				{
					"SensorID": "2424009",
					"SVID": "2424009",
					"Group": "Press",
					"SensorType": "Actual_VG03_1Hz",
					"Name": "VG03",
					"DataType": "Double",
					"Units": "Pa"
				}
			]
		},
		"RecipeSteps": 
		[
		{"Keys": {
				"RecipeStepID": "START",
				"StepResult": "NormalEnd"
			},
			"SensorData":
			[
				{
					"Keys": {"SensorID": "1723007"},
					"Measurements": 
					[
						{
							"DateTime": "2021-11-16 21:18:37.000",
							"Value": 540.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.100",
							"Value": 539.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.200",
							"Value": 540.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.300",
							"Value": 540.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.400",
							"Value": 540.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.500",
							"Value": 540.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.600",
							"Value": 540.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.700",
							"Value": 538.0
						},
						{
							"DateTime": "2021-11-16 21:18:37.800",
							"Value": 540.0
						}						
					]
				},
				{
					"Keys": {"SensorID": "2424009"},
					"Measurements": 
					[
						{
							"DateTime": "2021-11-16 21:18:37.000",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.100",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.200",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.300",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.400",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.500",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.600",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.700",
							"Value": 1333.22
						},
						{
							"DateTime": "2021-11-16 21:18:37.800",
							"Value": 1333.22
						}						
					]
				}
			]
		}
		  
		]


	}
}
```
The file also has a lot of other fields which are not relevant for me and I do not wish to process. There is no way I can load the whole document to the memory and process it. So, the strategy I am trying to follow is this:

**Step 1:**  The properties "Keys" and "Attributes" is common factor for all the elements in the "RecipeSteps" Array. So, I will parse them and write it to a new file.

**Step 2:**  I will now Try to split the file based on each element in the array "RecipeSteps". The new split files will have the "Keys" and "Attributes" properties since they are common metadata to all these files. At the end of this step, each split file will have the common data(Keys, Attributes) and "RecipeSteps" array with one element.

**Step 3:** I will further split these files based on each element in the array "SensorData". At the end of this step each file will have have the common data(Keys, Attributes) and "RecipeSteps" array with one element and that one element will have SensorData array with one element.

**Step 4:** Now I will iterate through all these files and do the comparison with the reference data I have and post the results.

Note that I have posted only the relevant properties to my requirements. There are so many other elements in the file which I want to ignore completely to make the processing faster.

I saw this article and tried it: https://www.codeproject.com/Tips/5315195/Cinchoo-ETL-Parsing-Huge-JSON-File-as-Stream

But this essentially tries to load the whole object into the memory. I skimmed through the documentation also with no luck.

What would you suggest I do to process this file in the most efficient manner? 
I can share the actual 16Gb file, if you want a clearer picture of my problem.

**Comment by Cinchoo** [comment]
You can use JSONPath to cherry pick elements from your file, process it. 

May I ask you what will be the output files looks like? (May be outline sufficient)

**Comment by Cinchoo** [comment]
Based on your input, drafted basic code to give you direction to accomplish your needs. Try and let me know.

https://dotnetfiddle.net/I7z4tp

**Comment by r04drunn3r** [comment]
The code you drafted works and gets me the desirable output. However, my file has a large array  that has to be split and when it encounters that, it takes forever to split. I have modified the above code for parsing the file in hand.

```
using System;
using ChoETL;
using System.Linq;

public class Program
{
    public static void Main()
    {
        dynamic keys = null;
        dynamic attributes = null;

        var json = @"path to\largetestdata.json";

        //Capture Keys
        using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.Keys"))
        {
            keys = r.FirstOrDefault();
        }

        //Capture attributes
        using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.Attributes"))
        {
            attributes = r.FirstOrDefault();
        }

        int index = 0;
        //Loop thro ReceipeSteps, write to individual files
        using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs"))
        {
            foreach (var rec in r)
            {
                using (var w = new ChoJSONWriter(Console.Out))
                {
                    w.Write(new { FileNo = ++index, Keys = keys, Attributes = attributes, RecipeSteps = rec });
                }
                "".Print();
            }
        }
    }


    
}
```
When it reaches the line 
` using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs"))`
the application just tries to load the humungous array into the memory and becomes unresponsive.

I am also attaching the link to the actual 16Gb file if you want to have a look at it:
https://drive.google.com/file/d/1_e3qBecQhH8sDIrHPZAND2zjnvzmwkDt/view?usp=sharing

**Comment by Cinchoo** [comment]
Can't open the file due to password protected.

Well, here is how you need to approach. Any node with large array must be opened separately using ChoJSONReader with JsonPath and break/write them to multiple files. 

I don't see `ProcessJobs` node in your original message. This may be something you missed from original question.

**Comment by r04drunn3r** [comment]
Thank you so much for the response! I am really sorry for posting a password protected zip. I have added the correct zip now:
https://drive.google.com/file/d/1JbFVgK-lLLYF0iNpM9szJe5IxCL01v-a/view?usp=sharing

And yes, I did not mention ProcessJobs in the original message.  I did not want to complicate the question further. 
The thing is,  ProcessJobs array consists of the major chunk of the data. The path gets complicated too:
ControlJob.ProcessJobs[0].ProcessRecipes[0].RecipeSteps[0].SensorData[0].Measurements[0].Value. 
My requirement  requires me to split the files based on each of these arrays,

I did try your suggestion of "large array must be opened separately using ChoJSONReader with JsonPath and break/write them to multiple files". 

`using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs.length()"))`

used the above statement to get the length and get each and every element of ProcessJobs using ChoJSONReader  with respective JSONPath. However when I try to execute this:

`using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs.length()"))`

or

`using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs[0].ProcessRecipes))`

I am getting the following exception:

1) Exception Information
*********************************************
Exception Type: Newtonsoft.Json.JsonException
TargetSite: Boolean MoveNext()
Message: Complex JSON path not supported.
Data: System.Collections.ListDictionaryInternal
HelpLink: NULL
Source: ChoETL.JSON.Core
HResult: -2146233088

StackTrace Information
*********************************************
   at ChoETL.ChoJSONRecordReader.ReadJObjects(JsonTextReader sr)+MoveNext()
   at ChoETL.ChoJSONRecordReader.FlattenNodeIfOn(IEnumerable`1 jObjects)+MoveNext()
   at ChoETL.ChoJSONRecordReader.AsEnumerable(IEnumerable`1 jObjects, TraceSwitch traceSwitch, Func`2 filterFunc)+MoveNext()
   at ChoETL.ChoJSONRecordReader.AsEnumerable(Object source, Func`2 filterFunc)+MoveNext()
   at ChoETL.ChoJSONReader`1.<>c__DisplayClass46_0.<GetEnumerator>b__0()
   at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
   at ChoETL.ChoEnumeratorWrapper.BuildEnumerable[T](Func`1 moveNext, Func`1 current, Action dispose)+MoveNext()
   at Program.Main() in C:\Users\mural\source\repos\Test\Test\Program.cs:line 31
_______________________________________________

Is there something I am not doing right? What do you suggest?

**Comment by Cinchoo** [comment]
FYI, complex JSONPath can be used in ChoJSONReader as below

`using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs[0].ProcessRecipes", true))`

But the downside is, it loads entire file into the memory, which we must avoid.

ChoJSONReader can be best suited with simple JSONPath to iterate over nested child elements only, Because it pull the data in enumerable way. less memory used.

If you want to find number of elements in a particular node level, you can so so as below (using Linq)

```
using (var r = new ChoJSONReader(json).WithJSONPath("$..ControlJob.ProcessJobs"))
{
     var count = r.Count();
}
```

PS: Got your file, give me sometime to take a look at it.

**Comment by r04drunn3r** [comment]
Is there any way to use complex JSONPath without loading the entire file into the memory? I guess that would solve the problem. 

Thank you so much again for taking a look at the file. Please let me know if you can see a way to crack this.

**Comment by Cinchoo** [comment]
Well, finally had chance to download and look into the file. Was quite challenging to load with the current version. (blowing up with OOM exception!)

After number of attempts, came up with solution to cater your needs (also quite useful for others as well if they need to do...).

In the new approach, users can hook up to the loader with the callback, by which you can direct the output to a file (instead of loading to memory). 

Sample fiddle: https://dotnetfiddle.net/I7z4tp

**Comment by r04drunn3r** [comment]
Thank you so much! This actually works! 

Before we close this thread, I just have one more query. Is there a way to increase the processing speed in this case? Is there a way I can allocate more memory for this task to get through this faster?

**Comment by Cinchoo** [comment]
Afraid not, as it is serial / forward only processing.
