### ISSUE TITLE
Receiving "ChoParserException" 'Invalid data passed.' when running documentation example.

### ISSUE THREAD

**Issue by damienspivak** [Cinchoo/ChoETL#171]
public void TestChoETL()
    {
        var writer = new ChoCSVWriter<EmployeeRec>("Emp.csv");

        EmployeeRec rec1 = new EmployeeRec();
        rec1.Id = 10;
        rec1.Name = "Mark";

        writer.Write(rec1);

        EmployeeRec rec2 = new EmployeeRec();
        rec1.Id = 11;
        rec1.Name = "Top";

        writer.Write(rec2);
    }

**Comment by Cinchoo** [comment]
Thanks for reporting it. it was a bug with the latest package. Applied fix, pushed v1.2.1.40. Try it. Thanks.

**Comment by damienspivak** [comment]
Thanks, for fixing this so quickly.  You're awesome.   
  By the way, is there a way of preserving the number of columns when writing to a csv file when the leading columns are null or blank?  I can't seem to find anything in the documentation. e.g. 

  First Name, Last Name, Address, Zip Code 
  , , 9 Elm St, 07024
  
  The first two commas are deleted.

**Comment by damienspivak** [comment]
Apologies if I missed it.

**Comment by damienspivak** [comment]
Nevermind, it looks like it's something I accidentally configured.  Thanks again for fixing the issue so quickly.
