### ISSUE TITLE
Leading Delimiters are omitted when using ChoCSVRecordField Attributes

### ISSUE THREAD

**Issue by damienspivak** [Cinchoo/ChoETL#172]
If I include attributes on my POCO object, the leading delimiters are omitted if all fields are blank and columns are left shifted.  For example:

public class EmployeeRec
{
    [ChoCSVRecordField(1, FieldName = "First")]
    public string First { get; set; }
    [ChoCSVRecordField(2, FieldName = "Last")]
    public string Last { get; set; }
    [ChoCSVRecordField(3, FieldName = "Id")]
    public int Id { get; set; }
    [ChoCSVRecordField(4, FieldName = "Name")]
    public string Name { get; set; }
}

        List<EmployeeRec> objs = new List<EmployeeRec>();
        var writer = new ChoCSVWriter<EmployeeRec>("Emp.txt").WithFirstLineHeader().WithDelimiter(",");

        EmployeeRec rec1 = new EmployeeRec();
        rec1.Id = 10;
        rec1.Name = "Mark";
        objs.Add(rec1);
        //writer.Write(rec1);

        EmployeeRec rec2 = new EmployeeRec();
        rec2.Id = 11;
        rec2.Name = "Top";

        //writer.Write(rec2);
        objs.Add(rec2);

        writer.Write(new[] { rec1, rec2 });

**Comment by Cinchoo** [comment]
It is bug, will put fix shortly, In the mean time, you can overcome this by having the POCO class as below

```
        public class EmployeeRec
        {
            [ChoCSVRecordField(1, FieldName = "First", IgnoreFieldValueMode = ChoIgnoreFieldValueMode.None)]
            public string First { get; set; }
            [ChoCSVRecordField(2, FieldName = "Last", IgnoreFieldValueMode = ChoIgnoreFieldValueMode.None)]
            public string Last { get; set; }
            [ChoCSVRecordField(3, FieldName = "Id", IgnoreFieldValueMode = ChoIgnoreFieldValueMode.None)]
            public int Id { get; set; }
            [ChoCSVRecordField(4, FieldName = "Name", IgnoreFieldValueMode = ChoIgnoreFieldValueMode.None)]
            public string Name { get; set; }
        }
```

Thanks for reporting it. Will update the fix once pushed.
