### ISSUE TITLE
Append 

### ISSUE THREAD

**Issue by Ahamad17** [Cinchoo/ChoETL#18]
How to open a file and write data without overwriting the already saved data using ChoJSONWriter

**Comment by Cinchoo** [comment]
You have open the file stream in append mode, pass it to ChoJSONWriter.

Sample below

            using (var file = new FileStream("output.json", FileMode.Append))
            {
                using (var w = new ChoJSONWriter(file))
                {

                }
            }

**Comment by Ahamad17** [comment]
Thank you it worked!
