### ISSUE TITLE
Multiple Json strings to CSV

### ISSUE THREAD

**Issue by sarvpk** [Cinchoo/ChoETL#185]
` private static void Main(string[] args) 
{
    List<string> temp = new List<string>();
    temp.Add("{\"col1\":\"123\",\"col2\":{\"col21\":\"aaaa\"},\"col3\":null,\"col6\":\"zzzz\"}");
    temp.Add("{\"col1\":\"456\",\"col2\":null,\"col3\":{\"col4\":\"bbbb\",\"col5\":\"cccc\"}");

    using (var w = new ChoETL.ChoCSVWriter(Console.Out))
    {
        int i = 0;
        foreach (var item in temp)
        {
            using (var r = ChoETL.ChoJSONReader.LoadText(item))
            {
                if (i == 0)
                    w.WithFirstLineHeader();
                i++;
                w.Write(r);
            }
        }
    }
} `

![image](https://user-images.githubusercontent.com/35501291/157133934-54c0d8d6-ee75-4925-9707-300945397faa.png)

What am I doing wrong here ?

**Comment by Cinchoo** [comment]
What is your source json? pls paste here. Also post expected CSV file.

**Comment by sarvpk** [comment]
> What is your source json? pls paste here. Also post expected CSV file.

In the sample code above the list of strings (temp) is the source. The expected output is merge of the two json

**Comment by Cinchoo** [comment]
Got it.  FYI, your input JSONs are not well formed. Corrected them. 
More over, the json are in different format. Likely you can combine to one single CSV.

Closest you can achieve as below

```
List<string> temp = new List<string>();
temp.Add(@"{""col1"":""123"",""col2"":{""col21"":""aaaa""},""col3"":null,""col6"":""zzzz""}");
temp.Add(@"{""col1"":""456"",""col2"":null,""col3"":{""col4"":""bbbb"",""col5"":""cccc""}}");

using (var w = new ChoETL.ChoCSVWriter(Console.Out)
			 .WithFirstLineHeader()
			 .WithMaxScanRows(3)
			 .ThrowAndStopOnMissingField(false)
			 .ErrorMode(ChoErrorMode.IgnoreAndContinue)
			)
{
	foreach (var item in temp)
	{
		using (var r = ChoETL.ChoJSONReader.LoadText(item))
		{
			w.Write(r);
		}
	}
}
```
		
Sample fiddle: https://dotnetfiddle.net/sOuwe8

**Comment by sarvpk** [comment]
> Got it. FYI, your input JSONs are not well formed. Corrected them. More over, the json are in different format. Likely you can combine to one single CSV.
> 
> Closest you can achieve as below
> 
> ```
> List<string> temp = new List<string>();
> temp.Add(@"{""col1"":""123"",""col2"":{""col21"":""aaaa""},""col3"":null,""col6"":""zzzz""}");
> temp.Add(@"{""col1"":""456"",""col2"":null,""col3"":{""col4"":""bbbb"",""col5"":""cccc""}}");
> 
> using (var w = new ChoETL.ChoCSVWriter(Console.Out)
> 			 .WithFirstLineHeader()
> 			 .WithMaxScanRows(3)
> 			 .ThrowAndStopOnMissingField(false)
> 			 .ErrorMode(ChoErrorMode.IgnoreAndContinue)
> 			)
> {
> 	foreach (var item in temp)
> 	{
> 		using (var r = ChoETL.ChoJSONReader.LoadText(item))
> 		{
> 			w.Write(r);
> 		}
> 	}
> }
> ```
> 
> Sample fiddle: https://dotnetfiddle.net/sOuwe8

did you mean "combine to one single JSON" ?

**Comment by Cinchoo** [comment]
No, combine to one CSV with all json nodes. 

Here is another approach: https://dotnetfiddle.net/sOuwe8

**Comment by sarvpk** [comment]
Great work and thanks for quick reply

**Comment by sarvpk** [comment]
One final question here, what if the json is part of a class ?

`public class Student
    {
        public string code { get; set; }
        public string country { get; set; }

        public string data { get; set; }
    }

var x = new Student
            {
                code = "test1Code",
                country = " test1Message",
                data = @"{""col1"":""123"",""col2"":{""col21"":""aaaa""},""col3"":null,""col6"":""zzzz""}"
            };

            var y = new Student
            {
                code = "test2Code",
                country = " test2Message",
                data = @"{""col1"":""456"",""col2"":null,""col3"":{""col4"":""bbbb"",""col5"":""cccc""}}"
            };

            var xy = new List<Student> { x, y };


            using (var w = new ChoETL.ChoCSVWriter(Console.Out)
                .WithFirstLineHeader()
                .WithMaxScanRows(3)
                .ThrowAndStopOnMissingField(false)
                .ErrorMode(ChoETL.ChoErrorMode.IgnoreAndContinue)
               )
            {
                w.Write(ParseJSONs(xy));
            }

public static IEnumerable<dynamic> ParseJSONs(List<Student> studentJson)
        {
            foreach (var item in studentJson)
            {
                using (var r = ChoETL.ChoJSONReader.LoadText(item.data))
                {
                    foreach (var rec in r)
                        yield return rec;

                    //yield return item.code;

                    //yield return item.message;
                }
            }
        }
`

**Comment by Cinchoo** [comment]
Here u go : https://dotnetfiddle.net/x8EagT

**Comment by Cinchoo** [comment]
if code, country to come before other fields, here is how you can do so

https://dotnetfiddle.net/x8EagT
