### ISSUE TITLE
Can't create a CSV file based on a nested object (Only dumps the headers) 

### ISSUE THREAD

**Issue by Igor03** [Cinchoo/ChoETL#186]
Hello, everybody! I recently started using this package to write csv files and this question may be very simple, but I looked everywhere and didn't ended up with satisfying solution. Here's the problem:
I Have an object similiar to this one

    [ChoCSVFileHeader]
    [ChoCSVRecordObject(HasExcelSeparator = true)]
    public class PlayerModel
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("first_name")]
        public string? FirstName { get; set; }

        [JsonProperty("last_name")]
        public string? LastName { get; set; }

        [JsonProperty("height_feet")]
        public int? HeightFeet { get; set; }

        [JsonProperty("height_inches")]
        public int? HeightInches { get; set; }

        [JsonProperty("position")]
        public string? Position { get; set; }

        [JsonProperty("weight_pounds")]
        public int? WeightInPounds { get; set; }

        [JsonProperty("team")]
        public TeamModel Team { get; set; }
    }

    [ChoCSVFileHeader]
    [ChoCSVRecordObject(HasExcelSeparator = true)]
    public class TeamModel
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("abbreviation")]
        public string? Abbreviation { get; set; }

        [JsonProperty("city")]
        public string? City  { get; set; }

        [JsonProperty("conference")]
        public string? Conference  { get; set; }

        [JsonProperty("division")]
        public string? Division { get; set; }

        [JsonProperty("full_name")]
        public string? FullName { get; set; }

        [JsonProperty("name")]
        public string? Name { get; set; }
    }

and, once I have a list of this kind of object, I run this line

```
using (var parser = new ChoCSVWriter<PlayerModel>(@"PATH/file.csv"))
{
    parser.Write(players);
}
```

and it creates a csv file within the correct directory, but only with the headers, like this

```
sep=;
Id;FirstName;LastName;HeightFeet;HeightInches;Position;WeightInPounds;Team.Id;Team.Abbreviation;Team.City;Team.Conference;Team.Division;Team.FullName;Team.Name
```

At first, I thought that it was because it could only map flat or non-nested objects but it identified the inner object in the headers (Team.Id, Team.Conference...).

If you guys can help me, it'd be great.

**I'm using .NET6**

**Comment by Igor03** [comment]
If I create the POCO with the `[ChoCSVRecordField(_position)]` property it actually writes stuff, but only from the root object.

        [ChoCSVRecordField(1)]
        [JsonProperty("id")]
        public int Id { get; set; }

        [ChoCSVRecordField(2)]
        [JsonProperty("first_name")]
        public string? FirstName { get; set; }

        [ChoCSVRecordField(3)]
        [JsonProperty("last_name")]
        public string? LastName { get; set; }
        ...
So I end up with something like this:

```
sep=;
Id;FirstName;LastName;HeightFeet;HeightInches;Position;WeightInPounds
14;Ike;Anigbogu;;;C;
25;Ron;Baker;;;G;
47;Jabari;Bird;;;G;
67;MarShon;Brooks;;;G;
71;Lorenzo;Brown;;;G;
90;Omri;Casspi;;;F; 
```

I tried to decorate the fields of the inner object with this same property but it did not worked. It kept dumping values from the root object only.

**Comment by Cinchoo** [comment]
use the beta package v1.2.1.43-beta10. (latest package has this issue)

`Install-Package ChoETL.JSON.NETStandard -Version 1.2.1.43-beta10`

Sample fiddle: https://dotnetfiddle.net/Ewi2Ow

**Comment by Igor03** [comment]
apparently it worked. I was able to dump the whole object. But then I stumble into another issue. If we try to customize the field name using this ``` [ChoCSVRecordField(FieldName ="MyField")]``` it falls back into the same problem. It only dumps the root object.

**Comment by Cinchoo** [comment]
Got it, it look like it is breaking at it. Instead use DisplayNameAttribute as below.

```
		[JsonProperty("team")]
		[System.ComponentModel.DisplayName("MyField")]
		public TeamModel Team { get; set; }

```

Sample fiddle: https://dotnetfiddle.net/Ewi2Ow

**Comment by Igor03** [comment]
Now it's working just fine! Thank you guys.
