### ISSUE TITLE
StackOverflowException flattening large JSON

### ISSUE THREAD

**Issue by gjvanvuuren** [Cinchoo/ChoETL#187]
I'm attempting to create a table from a fairly large json. The table has 286 columns and 13 rows. I'm using the dynamic model approach.

Here's my sample fiddle: https://dotnetfiddle.net/XxO0Py

The problem is that my application crashes with a StackOverflowException. When I randomly comment out a certain number of properties in the anonymous class, the table structure is created for the remaining properties. It doesn't seem to matter which properties, which leads me to assume that the anonymous class could be too large.

I'm not aware of any limitations on the number of properties allowed in an anonymous class. Is there an alternative approach to doing this?

**Comment by Cinchoo** [comment]
I'm not about to reproduce it, your sample works fine on my local. 

Can u try commenting out `dt.Print()` and see the problem occurs or not. Let me know.

**Comment by gjvanvuuren** [comment]
Strange that it works on your local. Fiddle also exits with a signal 9 error.

The problem disappears when `dt.Print()` is removed, but any kind of iteration over the results throws `System.StackOverflowException: 'Exception of type 'System.StackOverflowException' was thrown.'`

**Comment by Cinchoo** [comment]
Found a workaround, instead of anonymous type, define and use dynamic object for your needs.

Here is the working sample: https://dotnetfiddle.net/1oJwRU

**Comment by gjvanvuuren** [comment]
Such a simple solution! Thanks 👍
