### ISSUE TITLE
Disabling RuntimeBinderExceptions on missing properties in JSON

### ISSUE THREAD

**Issue by gjvanvuuren** [Cinchoo/ChoETL#188]
I'm trying to prevent getting the exception `'ChoETL.ChoDynamicObject' does not contain a definition for '...'`. The json files that I process aren't guaranteed to always have all the (dynamically) declared fields.

I had a look at the code in `ChoJSONRecordReader`, and it appears that `ThrowExceptionIfPropNotExists` is set to `true` by default whenever a `ChoDynamicObject` is created. Is there a way to override this behaviour? I tried setting `ThrowAndStopOnMissingField = false` in `ChoJSONRecordConfiguration`, but I'm still getting the exception.

Using part of your provided example (https://dotnetfiddle.net/1oJwRU), if I remove some input json property, for example `TimestampLocal`, then calling `root.TimestampLocal` in the following code will throw the exception:

```
  using (var r = ChoJSONReader.LoadText(json, conf))
  {
    var dt = r.SelectMany(root => 
      ((IList)root.Outputs.Items).Cast<dynamic>()
      .Select(item => 
      {
        dynamic o = new ChoDynamicObject();
    
        o.TimestampGlobal = root.TimestampGlobal;
        o.TimestampLocal = root.TimestampLocal;

        ...
        return o;
      }
  }
```
My expectation is that the `ChoDynamicObject` would return null if a key is not available.

**Comment by gjvanvuuren** [comment]
I've found something interesting: The issue only applies to keys in the the **root** instance of `ChoDynamicObject`, not to the child instances. So if I remove a json field further down the hierarchy, then looking at the object in the debugger, `ThrowAndStopOnMissingField` is set to `false`, and no binding exception is thrown.

**Comment by gjvanvuuren** [comment]
It gets complicated - from a certain level down, the nodes aren't instances of `ChoDynamicObject` anymore, but rather `ExpandoObject` instances. In the following abbreviated json structure, everything on level 3 and down (`Sr`, and `Vr`) are just `ExpandoObject`s. So removing `Version` for example causes a Binding Exception.

```
{
    "Message": "MessageX",
    "TimestampLocal": "2022-02-26T13:43:12.8888004+01:00",
    "TimestampGlobal": "2022-02-26T12:41:08.087723Z",
    "Machine": {
        "Nr": 1,
        "Name": "R/FE MAS",
        "MachineId": "S2254SR",
        "Location": "2254",
        "Length": 7560
    },
    "Computers": {
        "Sr": {
            "Name": "S2254SR1",
            "Version": "8.1.3.0",
            "Dlls": {
                "dbexpint.DLL": "7.0.2.113",
                "dbxadapter30.DLL": "11.0.2902.10471"
            },
            "Exes": {
                "Ausauns.Exe": "9.02",
                "paaeit.exe": null
            }
        },
        "Vr": {
            "Name": "S2254MR1",
            "Version": "9.0.3.0",
            "Info": "",
            "Dlls": {
                "Ra70.bpl": "1.0.2.0",
                "REx70.bpl": "9.0.2.0"
            }
        }
    }
}
```

So it would seem, depending on the level on which a key-value pair is missing, either a binding exception is thrown, or not.

**Comment by Cinchoo** [comment]
Yes, you are right, Only the root object is `ChoDynamicObject`, rest are `ExpandoObject`.
If you want to have all of them `ExpandoObject`, use `.UseJsonSerialization()`.

Hope it helps. 

PS: Will look into the `ThrowExceptionIfPropNotExists` issue.

**Comment by gjvanvuuren** [comment]
Thanks. Actually, I want all nodes to be `ChoDynamicObject`s, because of the ability to ignore missing dynamic properties.

**Comment by Cinchoo** [comment]
Will look into it.

**Comment by Cinchoo** [comment]
put a fix, to extract all nodes as `ChoDynamicObject` with the release [v1.2.1.43-beta11](https://www.nuget.org/packages/ChoETL.JSON.NETStandard/1.2.1.43-beta11)

Added `ChoJSONRecordConfiguration.ThrowExceptionIfDynamicPropNotExists` to control the behavior.

**Comment by gjvanvuuren** [comment]
Great! It works well, and makes more sense to be dealing with `ChoDynamicObject`s instead of the hybrid approach.

Just one issue I discovered. If a key contains a dot, like `filename.ext`, then the key-value is ignored.

**Example**:
```
var json = @"
{
	    ""Name"": ""S2254SR1"",
	    ""Version"": ""8.1.3.0"",
	    ""Info"": ""WinCorpX.Exe 28.05.2021 12:47:38"",
	    ""Dlls"": {
	        ""dbexpint.dll"": ""7.0.2.113"",
	        ""dbxadapter30.dll"": ""11.0.2902.10471""
		}
}";

using (var r = ChoJSONReader.LoadText(json))
{
	r.Print();
}
```

**Output**:

```
Key: Name [Type: String]
Value: S2254SR1 [Type: String]
Key: Version [Type: String]
Value: 8.1.3.0 [Type: String]
Key: Info [Type: String]
Value: WinCorpX.Exe 28.05.2021 12:47:38 [Type: String]
Key: Dlls [Type: String]
Value:  [Type: ChoDynamicObject]
```

In the above example, once the ***.dll** endings are removed, the output is correct:

```
Key: Name [Type: String]
Value: S2254SR1 [Type: String]
Key: Version [Type: String]
Value: 8.1.3.0 [Type: String]
Key: Info [Type: String]
Value: WinCorpX.Exe 28.05.2021 12:47:38 [Type: String]
Key: Dlls [Type: String]
Value: [Count: 2]
Key: dbexpint [Type: String]
Value: 7.0.2.113 [Type: String]
Key: dbxadapter30 [Type: String]
Value: 11.0.2902.10471 [Type: String]
```

**Comment by Cinchoo** [comment]
Pls set `ChoETLSettings.KeySeparator = ChoCharEx.Escape;` at the main() to turn this nested property handling feature.

**Comment by gjvanvuuren** [comment]
That did the trick, thanks!
