### ISSUE TITLE
Getting ArgumentOutOfRangeException when using NestedColumnSeparator

### ISSUE THREAD

**Issue by sarvpk** [Cinchoo/ChoETL#189]
I have a piece of C# code working just fine but when I add this single line NestedColumnSeparator('.') I get the below error. Not sure where the bug is ! The input/json is the same and it works fine if I remove this method call go with the default separator.

I followed the sample you provided in https://dotnetfiddle.net/x8EagT

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ChoETL.ChoType.GetDeclaringRecord(Object src, String propName, Nullable`1 arrayIndex, List`1 nestedArrayIndex, Boolean leaf)
   at ChoETL.ChoCSVRecordWriter.ToText(Int64 index, Object rec, String& recText)
   at ChoETL.ChoCSVRecordWriter.WriteTo(Object writer, IEnumerable`1 records, Func`2 predicate)+MoveNext()
   at ChoETL.ChoUtility.Loop(IEnumerable e, Action preActionCallback, Action`1 postActionCallback)
   at ChoETL.ChoCSVWriter`1.Write(IEnumerable`1 records)

**Comment by Cinchoo** [comment]
works fine for me. Modified your fiddle. What I'm missing?

sample fiddle: https://dotnetfiddle.net/x8EagT

**Comment by sarvpk** [comment]
When I am using the release version 1.2.1.42 of ChoETL.JSON.NETStandard, I get the error. Switched to 1.2.1.43-beta11 and it is working fine. Thanks for looking into this ! When can I expect a release version ?

**Comment by Cinchoo** [comment]
preparing, will update.

**Comment by sarvpk** [comment]
is there an option to prepend the header columns with some static text ? (ex: app)

**app**.code,**app**.country,**app**.col1,**app**.col2.col21,**app**.col3.col4,**app**.col3.col5,**app**.col6
A123456,USA,123,aaaa,,,zzzz
B123456,India,456,,bbbb,cccc,

**Comment by Cinchoo** [comment]
> When I am using the release version 1.2.1.42 of ChoETL.JSON.NETStandard, I get the error. Switched to 1.2.1.43-beta11 and it is working fine. Thanks for looking into this ! When can I expect a release version ?

Release new version. Give it a try.

**Comment by Cinchoo** [comment]
> is there an option to prepend/prefix the header columns with some static text ? (ex: app)
> 
> **app**.code,**app**.country,**app**.col1,**app**.col2.col21,**app**.col3.col4,**app**.col3.col5,**app**.col6 A123456,USA,123,aaaa,,,zzzz B123456,India,456,,bbbb,cccc,
> 
> I tried this (from above fiddle) and it works. Any other clean way ?
> 
> Dictionary<string, object> dict = new Dictionary<string, object>(); dict.Add("app", result); dynamic final = new ChoETL.ChoDynamicObject(dict); yield return final;

```
dynamic final = new ChoDynamicObject();
final.app = result;
yield return final;
```

**Comment by Cinchoo** [comment]
> > When I am using the release version 1.2.1.42 of ChoETL.JSON.NETStandard, I get the error. Switched to 1.2.1.43-beta11 and it is working fine. Thanks for looking into this ! When can I expect a release version ?
> 
> Release new version. Give it a try.

Release new version 1.2.1.44. Give it a try.

**Comment by sarvpk** [comment]
Thank you
