### ISSUE TITLE
CSV to Sql Table 

### ISSUE THREAD

**Issue by papyr** [Cinchoo/ChoETL#19]
Hi can the parser read/parse CSV and create/copy to a new SQL table.

The csv header is not know before hand.
Can I simple insert based on the header from the CSV table
Can I create C# Ienumerable entity at runtime without knowing whats inthe csv file.

**Comment by Cinchoo** [comment]
Yes, you can. Use CSVReader helper methods AsDataTable / AsDataReader.

Here is the sample

```
string connectionstring = @"#YOUR DB ConnectionString#";
using (SqlBulkCopy bcp = new SqlBulkCopy(connectionstring))
{
    using (var p = new ChoCSVReader("#YOUR CSV FILE#"))
    {
        bcp.DestinationTableName = "#TABLENAME#";
        bcp.EnableStreaming = true;
        bcp.BatchSize = 10000;
        bcp.BulkCopyTimeout = 0;
        bcp.NotifyAfter = 100;
        bcp.SqlRowsCopied += delegate (object sender, SqlRowsCopiedEventArgs e)
        {
            Console.WriteLine(e.RowsCopied.ToString("#,##0") + " rows copied.");
        };
        bcp.WriteToServer(p.AsDataReader());
    }
}
```

**Comment by papyr** [comment]
Hi, this is very close to what i need, awesome and hi five ✋ 

one issue, when I put #TableName it fails, is there a way to get the error msg, also is there a safe way to proceed and handle that?

during the copy phase, will it also create the new table.
