### ISSUE TITLE
Field is not transformed to null when using the ChoCSVReader LiteParser

### ISSUE THREAD

**Issue by WolfAlvein** [Cinchoo/ChoETL#190]
Hi Cinchoo, first of all thank you for making this ETL framework, it has made my recent work in a project quite a lot easier.

I just wanted to let you know that in a project that I'm working based on the framework .Net Core 2.2, I have downloaded your packages: choetl.netstandard\1.2.1.42 and choetl.json.netstandard\1.2.1.42, where I'm reading a CSV file from a string after extracting it from a .zip file, I have activated the LiteParser on the CSVReader so that it can process the big files I have to read a bit faster, I'm using the code:

  ```
StringBuilder jsonData = new StringBuilder();
  using (var csvParser = ChoCSVReader.LoadText(header + Environment.NewLine + _csvData)
                                                   .WithFirstLineHeader()
                                                   .ThrowAndStopOnMissingField(false)
                                                   .Configure(c => c.LiteParsing = true)
                                                   .Configure(c => c.NestedColumnSeparator = '/')
                                                   .Configure(c => c.NullValue = "^MISSING_VALUE$")
                                                   .Configure(c => c.NullValueHandling = ChoNullValueHandling.Null)
                                                   .Configure(c => c.FieldValueTrimOption = ChoFieldValueTrimOption.None))
                {
                    ChoJSONRecordConfiguration jsonConfig = new ChoJSONRecordConfiguration();
                    jsonConfig.LiteParsing = true;
                    jsonConfig.IgnoreFieldValueMode = ChoIgnoreFieldValueMode.Any;
                    jsonConfig.FieldValueTrimOption = ChoFieldValueTrimOption.None;
                   
                    using (var jsonParser = new ChoJSONWriter(jsonData, jsonConfig))
                    {
                        jsonParser.Write(csvParser);
                    }
                }
```

So when this code is executed I get all the data written into the stringBuilder and then transform it into my POCO classes using the `JsonConvert.DeserializeObject<List<T>>(jsonData.ToString());` code, but sometimes when I have an empty field in the CSV, it writes dows fields has "^MISSING_VALUE$" instead of leaving it empty or setting it to null, I did set the configuration for the NullValue has you can see, but I still get that issue, I have done a small work around to avoid an exception by changing the `JsonData.ToString()` into  `jsonData.ToString().Replace("^MISSING_VALUE$", null)`.

I have attached a file with this error so that you can check it out.

Thank you and let me know if you need anything.
[CSVToJsonFile.txt](https://github.com/Cinchoo/ChoETL/files/8302398/CSVToJsonFile.txt)

**Comment by Cinchoo** [comment]
Remove `.Configure(c => c.LiteParsing = true)` line.

LiteParsing doesn't comes with all the standard rich parsing capabilities. Purpose is to load the CSV file faster, leave the rest to the developer to do the handle the data massaging. 

Sample fiddle to handle null value: https://dotnetfiddle.net/8fbq3W

**Comment by Cinchoo** [comment]
FYI, Cinchoo ETL comes  with micro CSV parser `ChoCSVLiteReader`, refer this article for more information

https://www.codeproject.com/Articles/5320967/Cinchoo-ETL-CSV-Lite-Reader

This might help to parse any large CSV file faster.

**Comment by WolfAlvein** [comment]
Hi Cinchoo, thank you very much for the quick response, if I where to use the `ChoCSVLiteReader`, would I be able to transform the data into my T classes that are like>

```
using System;
using System.Collection.Generic

namespace CSVData {
	
   public class Class1 {
	   
	  public int optionsCount; 
	  
	  public string column2;  
	  
	  public int columnn3;   
	  
	  public string column4;   
	  
	  public string column5;   
	  
	  public string column6;   
	  
	  public string column7;   
	  
	  public List<Options> column8;   
	  
	  public int column9;   
	  
	  public DateTime column10;   
	  
	  public string column11;   
	  
	  public int column12;   
   }

   public class Options {
      
	  public string subColumn2; 
	  
          public string subColumn3;  
	  
          public int subColumn4;   
	  
	  public int subColumn5;
   }
}
```

Where my CSV doesn't have a header and the amount of columns can vary per row depending on the `OptionsCount` column and the amount of columns that the Class options have, here is an example of the CSV in google: 

https://docs.google.com/spreadsheets/d/1BjHcH1uUr6flgKl6adg7y7aUBuWRVcJjGEZdcIz_3nU/edit?usp=sharing

The issue is that I will have in some cases an exorbitant amount of columns added, in one case it's `345 OptionsCount * 5 Columns, so we are talking about 345 * 5 = 1,725 total columns` 

I have done a small method to create the header of the CSV dynamically taking into account the Max `OptionsCount` in the CSV by doing:


[CSVExample.txt](https://github.com/Cinchoo/ChoETL/files/8308833/CSVExample.txt)
[Class Example.txt](https://github.com/Cinchoo/ChoETL/files/8308834/Class.Example.txt)

**Comment by Cinchoo** [comment]
Here you go, the working sample using liteparser

https://dotnetfiddle.net/p5b1VH

**Comment by WolfAlvein** [comment]
Thank you for the Example especially since you took some time today to answer, but I think I didn't explain myself very clearly....

The current code that I'm using is not for only one CSV, we are managing 23 CSV's that are transformed into 5 different Classes and some of them have information like the one I sent you before, where they have rows with variyng amount of columns base on a field inside of the CSV, while other have a strict amount of columns and don't have a special way of transforming the data, so it's quite more direct, is it possible with the CSVLiteParser to do the serialization into the class using the header and the nested column separator, or will I have to do a different treatment for each of the 5 clases and their corresponding files, this is the code that currently transforms the 23 file into their correct classes based on the header.

```
private async Task<List<T>> DeserializeFromZipCSVToObject<T>(CapProductFileData capFile, string fileName)
{
	string filePath = AppDomain.CurrentDomain.BaseDirectory + @"\tmp\";
	List<T> returnObject = new List<T>();
	MemoryStream jsonStream = new MemoryStream();

	try
	{
		bool readLargeStream = ((double)capFile.FileData.Length / (double)1024) / (double)1024 > 16;
		string _csvData = await GetZipByteAsStringAsync(capFile.FileData);
		string header = string.Empty;

		Type t = typeof(T);

		if (t == typeof(CapVehicleNewPriceOption) || t == typeof(CapVehicleUsedValuePrice) || t == typeof(CapVehicleUsedMonitor))
		{
			header = GetSpecialCSVHeader<T>(_csvData);
		}
		else
		{

			BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic |
				 BindingFlags.Static | BindingFlags.Instance |
				 BindingFlags.DeclaredOnly;

			PropertyInfo[] fields = t.GetProperties(flags);

			header = String.Join(",", fields.Select(f => f.Name));
		}

		using (var csvParser = ChoCSVReader.LoadText(header + Environment.NewLine + _csvData)
										   .WithFirstLineHeader()
										   .ThrowAndStopOnMissingField(false)
										   .Configure(c => c.LiteParsing = true)
										   .Configure(c => c.NestedColumnSeparator = '/')
										   .Configure(c => c.NullValue = "^MISSING_VALUE$")
										   .Configure(c => c.NullValueHandling = ChoNullValueHandling.Null)
										   .Configure(c => c.FieldValueTrimOption = ChoFieldValueTrimOption.None))
		{
			ChoJSONRecordConfiguration jsonConfig = new ChoJSONRecordConfiguration();
			jsonConfig.LiteParsing = true;
			jsonConfig.IgnoreFieldValueMode = ChoIgnoreFieldValueMode.Any;
			jsonConfig.FieldValueTrimOption = ChoFieldValueTrimOption.None;

			using (var jsonParser = new ChoJSONWriter(jsonStream, jsonConfig))
			{
				jsonParser.Write(csvParser);
			}
		}

		jsonStream.Position = 0;

		if (readLargeStream)
		{
			using (StreamReader streamReader = new StreamReader(jsonStream))
			using (JsonTextReader reader = new JsonTextReader(streamReader))
			{
				reader.SupportMultipleContent = true;
				List<T> objectDeserialized = new List<T>();

				var serializer = new JsonSerializer();
				while (reader.Read())
				{
					if (reader.TokenType == JsonToken.StartObject)
					{
						var _jsonReturn = serializer.Deserialize<T>(reader);
						objectDeserialized.Add(_jsonReturn);
					}
				}
				returnObject.AddRange(objectDeserialized);
			}
		}
		else
		{
			returnObject = JsonConvert.DeserializeObject<List<T>>(jsonStream.ReadToEnd().Replace("^MISSING_VALUE$", null));
		}
	}
	catch (Exception ex)
	{
		if (!Directory.Exists(filePath.Replace(@"\tmp\", @"\log\")))
		{
			Directory.CreateDirectory(filePath.Replace(@"\tmp\", @"\log\"));
		}

		File.WriteAllText(filePath.Replace(@"\tmp\", @"\log\") + fileName + ".txt", ex.Message); //jsonData.ToString().Replace("^MISSING_VALUE$", null));
	}

	return returnObject;
}

private string GetSpecialCSVHeader<T>(string _csvData)
{
	string header = string.Empty;
	Type t = typeof(T);

	BindingFlags flags = BindingFlags.Public | BindingFlags.NonPublic |
			 BindingFlags.Static | BindingFlags.DeclaredOnly |
			 BindingFlags.Instance;

	List<PropertyInfo> originalFields = t.GetProperties(flags).ToList();

	if (t == typeof(CapVehicleNewPriceOption))
	{
		if (!string.IsNullOrEmpty(_csvData))
		{
			if (originalFields != null)
			{
				originalFields.RemoveRange(8, 7);
				header = String.Join(",", originalFields.Select(f => f.Name));
				int maxOptionCount = 0;

				ChoCSVRecordConfiguration choConfig = new ChoCSVRecordConfiguration
				{
					ThrowAndStopOnMissingField = false,
					FieldValueTrimOption = ChoFieldValueTrimOption.None
				};
				
				using (var csvParser = ChoCSVReader.LoadText(_csvData, choConfig))
				{
					maxOptionCount = csvParser.Max(c => Convert.ToInt32(c.Column1));
				}

				Type capVehicleOption = typeof(CapVehicleOption);
				List<PropertyInfo> indexedCSVFields = capVehicleOption.GetProperties(flags).ToList();

				indexedCSVFields.RemoveRange(5, 4);

				string endingHeader = string.Empty;

				for (int i = 0; i < maxOptionCount; ++i)
				{
					endingHeader += String.Join(",", indexedCSVFields.Select(f => "VehicleOptions/" + i + "/" + f.Name)) + ",";
				}

				header += "," + endingHeader.TrimEnd(',');
			}
		}
	}
	else if (t == typeof(CapVehicleUsedValuePrice))
	{
		if (originalFields != null)
		{
			string firstHeader = String.Join(",", originalFields.GetRange(0, 6).Select(f => f.Name));
			string endHeader = String.Join(",", originalFields.GetRange(7, 4).Select(f => f.Name));

			Type capVehicleOption = typeof(CapVehicleMileagePoint);
			List<PropertyInfo> indexedCSVFields = capVehicleOption.GetProperties(flags).ToList();

			string middleHeader = string.Empty;

			for (int i = 0; i < 6; ++i)
			{
				middleHeader += String.Join(",", indexedCSVFields.Select(f => "MileagePoints/" + i + "/" + f.Name)) + ",";
			}

			header = firstHeader + "," + middleHeader + endHeader;
		}
	}
	else if (t == typeof(CapVehicleUsedMonitor))
	{
		if (originalFields != null)
		{
			string firstHeader = String.Join(",", originalFields.GetRange(0, 4).Select(f => f.Name));
			string endHeader = String.Join(",", originalFields.GetRange(5, 2).Select(f => f.Name));

			Type capVehicleOption = typeof(CapVehicleMileagePointMonitor);
			List<PropertyInfo> indexedCSVFields = capVehicleOption.GetProperties(flags).ToList();

			string middleHeader = string.Empty;

			for (int i = 0; i < 20; ++i)
			{
				middleHeader += String.Join(",", indexedCSVFields.Select(f => "MileagePoints/" + i + "/" + f.Name)) + ",";
			}

			header = firstHeader + "," + middleHeader + endHeader;

		}
	}


	return header;
}
```

**Comment by Cinchoo** [comment]
CSVLiteParser is simple and light weight parser, catered to load csv file faster. Leave the rest to user to map the csv fields to object model. This will not work for you as you already put some development using regular csv parser. You must continue to work towards solution. Just remove `LiteParsing = true` (this is not suitable for your need as well).

**Comment by WolfAlvein** [comment]
Thank you for the answer I'm going to use the Lite Parser for the files that have a 1 to 1 transform from columns to values in their Classes, and use the normal Reader on the ones that have special use cases like the ones indicated before, I'm sure that would make everything faster at the end.

Still thank you very much for all the input and everything.
