### ISSUE TITLE
Exception while accessing into flattened json object

### ISSUE THREAD

**Issue by CreaterCalvin** [Cinchoo/ChoETL#193]
I'm trying to access flattened json object by using json path:
```using System;
using ChoETL;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

public class Program
{
	public static void Main()
	{
		typeof(ChoJSONReader).GetAssemblyVersion().Print();
		"".Print();
		
		string json = @"{
  ""BrandId"": ""998877665544332211"",
  ""Categories"": [ ""112233445566778899"" ],
  ""Contact"": {
    ""Phone"": [
      {
        ""Value"": ""12346789"",
        ""Description"": { ""vi"": ""Phone"" },
        ""Type"": 1
      }
    ]
  }
}";
		using (var r = ChoJSONReader.LoadText(json)
			   .Configure(c => c.DefaultArrayHandling = false)
			   .Configure(c => c.FlattenNode = true)
			   .Configure(c => c.UseNestedKeyFormat = true)
			   .Configure(c => c.FlattenByNodeName = "Contact.Phone")
			   .Configure(c => c.NestedKeySeparator = '.')
			   .Configure(c => c.NestedColumnSeparator = '.')
			  )
		{
			//var dt = r.AsDataTable();
			//dt.DumpAsJson().Print();
			var a = r.WithField("Phone","$.[\"Contact.Phone.Value\"]");
			a.Print();
			
		}

	}
}
```
After running this code, it's return this output:
```
ChoETL.JSON.Core v1.2.1.45

[
  [ ]
]
```
Expected output:
```
[
"12346789"
]
```
I'm using ChoETL.JSON.Core v1.2.1.45 beta1
[https://dotnetfiddle.net/WJHC2P](https://dotnetfiddle.net/WJHC2P)
@Cinchoo

**Comment by CreaterCalvin** [comment]
I understand what you have done. But when I access to `  ""Description"": { ""vi"": ""Phone"" }` by using 
```
var a = r.WithField("Phone","$.[\'Contact.Phone.Description.vi\']", isArray: false);
```
it's return null value
[https://dotnetfiddle.net/1fGp7O](https://dotnetfiddle.net/1fGp7O)

**Comment by CreaterCalvin** [comment]
By the way, can you plz explain all parameter in ChoJSONReader().Configure ?. I have search a lot but I can't find any kind of doc explain all parameter in your packet
@Cinchoo

**Comment by zhenyuan0502** [comment]
> I understand what you have done. But when I access to ` ""Description"": { ""vi"": ""Phone"" }` by using
> 
> ```
> var a = r.WithField("Phone","$.[\'Contact.Phone.Description.vi\']", isArray: false);
> ```
> 
> it's return null value @Cinchoo https://dotnetfiddle.net/1fGp7O

Because it was a key separator, if you change `.` to `_` as `.Configure(c => c.NestedKeySeparator = '_')`, you don't need to wrapper by brackets, so it is just simply 
`var a = r.WithField("Phone","$.Contact_Phone_Description.vi", isArray: false);`

**Comment by CreaterCalvin** [comment]
> > I understand what you have done. But when I access to ` ""Description"": { ""vi"": ""Phone"" }` by using
> > ```
> > var a = r.WithField("Phone","$.[\'Contact.Phone.Description.vi\']", isArray: false);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it's return null value @Cinchoo https://dotnetfiddle.net/1fGp7O
> 
> Because it was a key separator, if you change `.` to `_` as `.Configure(c => c.NestedKeySeparator = '_')`, you don't need to wrapper by brackets, so it is just simply `var a = r.WithField("Phone","$.Contact_Phone_Description.vi", isArray: false);`
Thanks alot for your explanation. It's help me alot for my project
