### ISSUE TITLE
Underscore missing in FieldName

### ISSUE THREAD

**Issue by asesidaa** [Cinchoo/ChoETL#195]
When I tried to use 
```c#
[ChoXmlElementRecordField(FieldName = "field_name")]
```
to set the field name, in the generated xml string, the field name is missing underscore, so in the XML I got is
```xml
<fieldname></fieldname>
```

I can workaround this issue by setting `UseXmlSerialization=true` and set the field name using `XmlElement` attribute.
It is a bug or am I doing it wrong? 

Thank you!

A minimal example (NuGet version 1.2.1.44)
```c#
public class Record
{
    [ChoXmlElementRecordField(FieldName = "field_name")]
    public int Field { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        var record = new Record { Field = 1 };
        var sb = new StringBuilder();
        var writer = new ChoXmlWriter<Record>(sb);
        writer.Write(record);

        Console.WriteLine(sb);
    }
}
```
I get 
```xml
<Records>
  <Record>
    <fieldname>1</fieldname>
  </Record>
```

**Comment by Cinchoo** [comment]
Applied fix, released ChoETL.JSON.Core v1.2.1.45-beta2.
