### ISSUE TITLE
ChoXmlWriter generates wrong nodes

### ISSUE THREAD

**Issue by MacMuffin** [Cinchoo/ChoETL#197]
I have problems generating an xml File out of a POCO.

Let’s say, I have similar structure to this:

`
public class Contact 
{
     public string Name { get; set; }
     public Certificate[] certificates { get; set; }
}

public class Certificate 
{
     public string certificateSign { get; set; }
}
`

When I generate now the output with this poco, I get something like:
`
<contact>
  <Name>Peter</Name>
  <certificate>
     <certificateSign>A1</certificateSign>
  </certificate>
  <certificate>
     <certificateSign>A2</certificateSign>
  </certificate>
</contact>
`

but the goal should be

`
<contact>
  <Name>Peter</Name>
  <certificates>
     <certificateSign>A1</certificateSign>
     <certificateSign>A2</certificateSign>
  </certificates>
</contact>
`

because this is exactly how the poco is working when I use ChoXmlReader.

what do I miss? 

Thank you very much in advance.

**Comment by Cinchoo** [comment]
well, you need to fix the POCO classes as below

```
    [XmlRoot("contact")]
    public class Contact
    {
        public string Name { get; set; }
        [XmlArrayItem("certificateSign")]
        public Certificate[] certificates { get; set; }
    }

    public class Certificate
    {
        [XmlText]
        public string certificateSign { get; set; }
    }
```

And use the writer to produce the expected xml

```
        using (var w = new ChoXmlWriter<Contact>(Console.Out)
            .UseXmlSerialization()
            .IgnoreRootName()
            )
        {
            w.Write(rec);
        }
```

Sample fiddle: https://dotnetfiddle.net/xsPqUs

**Comment by Cinchoo** [comment]
you should `ShouldSerializeXXX` to control the serialization

Tweak the class as below
```
    [XmlRoot("contact")]
    public class Contact
    {
		public string Title { get; set; }
		public bool ShouldSerializeTitle()
		{
			Title = Title ?? "";
			return true;
		}
        public string Name { get; set; }
        [XmlArrayItem("certificateSign")]
        public Certificate[] certificates { get; set; }
    }
```

Sample fiddle: https://dotnetfiddle.net/kDzMvD
