### ISSUE TITLE
CSV Append Putting New Record Next to Previous Last Record, No End of Line Added

### ISSUE THREAD

**Issue by jeffreywstevens** [Cinchoo/ChoETL#199]
I am trying append to make something more scalable and operate in smaller chunks.

This seemed to be working before and now is failing in this scenario. It is a scenario of adding 1 record to an existing file.  I am following the recommended approach with FileMode.Append, skipping WithFirstLineHeader.

The fields are all quoted. However, instead of the new record getting appended, it is putting it right beside the previous last record without an end of line character getting added.

I guess I could fix this with code but it should work IMHO.

![image](https://user-images.githubusercontent.com/637945/164955372-105c5bae-8395-460c-87ad-b632d4c85000.png)

**Comment by Cinchoo** [comment]
Duplicate: CRLF not being added to the end of Fixed Length Files. #183

could this help?

**Comment by jeffreywstevens** [comment]
Potentially. I fixed it by appending a CRLF first to the file if the file existed.

I was using a defined class for appending. 

I abandoned that technique anyway. I wanted to eliminate potential contention and allow for creating multiple file simultaneously. Then I merge them all together. It seems better.
