### ISSUE TITLE
in ChoFileRecordObjectAttribute.cs default Encoding is set to "UTF8"

### ISSUE THREAD

**Issue by etwina** [Cinchoo/ChoETL#2]
However 
Encoding.GetEncoding("UTF8") is failing.
and should be 
Encoding.GetEncoding("UTF-8")

I encountering this error while trying to use your NACHA Library 

![image](https://cloud.githubusercontent.com/assets/3801343/24322928/17d779ec-117e-11e7-9008-a4f538f6730e.png)

**Comment by Cinchoo** [comment]
Corrected. Applied the fix. 
Thanks for reporting it.

**Comment by etwina** [comment]
Thank you for the quick response

**Comment by Cinchoo** [comment]
Fixes few issues with NACHA libraries. Try with the latest.
