### ISSUE TITLE
Convert Json string to CSV string

### ISSUE THREAD

**Issue by outlookcast** [Cinchoo/ChoETL#20]
I would like to know how can I convert the json string to a csv string without saving the files to the computer.
The code I'm using reads and writes to PC files, but I'd like to use it without dealing with the files.

The code that I was using is this:

```
using (var r = new ChoJSONReader("sample.json"))
{
 using (var w = new ChoCSVWriter("sample.csv").WithFirstLineHeader())
 {
  w.Write(r);
 }
}
```

I would like a code like this:

```
public string json2CSV(string jsonData)
{
 string csvData;
 //Convert jsonData and save in csvData...
 //...
 return csvData;
}
```

**Comment by Cinchoo** [comment]
Well, you can do as below

StringBuilder csvData = new StringBuilder();

using (var r = new ChoJSONReader.LoadText(jsonText))
{
 using (var w = new ChoCSVWriter(csvData).WithFirstLineHeader())
 {
  w.Write(r);
 }
}

**Comment by outlookcast** [comment]
I getting this error:
"LoadText" does not exist in type ChoJSONReader

:/

**Comment by mrp100461** [comment]
cannot find ChoJSONReader in my ChoETL using 4.7.2 .net

**Comment by Cinchoo** [comment]
install this package https://www.nuget.org/packages/ChoETL.JSON/

**Comment by mrp100461** [comment]
Thanks
