### ISSUE TITLE
ChoParquetWriter.Write(IDataReader dr) duplicates the last IDataReader result in resulting Parquet file

### ISSUE THREAD

**Issue by andresharpe** [Cinchoo/ChoETL#204]
There seems to be a bug in the `ChoParquetWriter.Write(IDataReader dr)` helper method.

The method reuses the same `dynamic expando` variable, maps it onto an `IDictionary<string, object> expandoDic`, and reuses it for every iteration of the `IDataReader.Read()` method. 

The result is that the `private List<dynamic> _records` variable in class `ChoParquetRecordWriter` all reference exactly the same object which results in the systematic duplication of the last row read.

Here is the sample usage code for the method:
```
using ChoETL;
using Parquet;
using System.Data.SqlClient;

using (var conn = new SqlConnection(@"*** SQL SERVER CONNECTION STRING ***"))
{
    conn.Open();
    var cmd = new SqlCommand("*** SQL SERVER COMMAND ***", conn);
    var dr = cmd.ExecuteReader();

    using (var w = new ChoParquetWriter(@"*** PARQUET OUTPUT FILE ***")
        .Configure(c => c.RowGroupSize = 5000)
        .Configure( c => c.CompressionMethod = CompressionMethod.Snappy )
     )
    {
        w.Write(dr);
    }
}
```

The bug can be corrected by updating the `public void Write(IDataReader dr)` in `ChoParquetWriter.cs` as follows:-

```
            var ordinals = Configuration.ParquetRecordFieldConfigurations.ToDictionary(c => c.Name, c => dr.HasColumn(c.Name) ? dr.GetOrdinal(c.Name) : -1);
            while (dr.Read())
            {
               // move variable initialization to here and remove the expandoDic.Clear() call
                dynamic expando = new ExpandoObject();
                var expandoDic = (IDictionary<string, object>)expando;
                
                foreach (var fc in ordinals)
                {
                    expandoDic.Add(fc.Key, fc.Value == -1 ? null : dr[fc.Value]);
                }

                Write(expando);
            }
```

**Comment by Cinchoo** [comment]
Took care of the changes (no pull request needed), as this fix needs to be applied to all writers. Released 1.0.1.22-beta1.

**Comment by andresharpe** [comment]
Many thanks Cinchoo. 

P.S. The PR that I submitted also failed compilation in build pipeline via Appvayor.  Something about version conflicts in dll's

**Comment by andresharpe** [comment]
Issue resolved
