### ISSUE TITLE
ChoJSONRecordConfiguration interferes with Union statement when parsing JSON

### ISSUE THREAD

**Issue by gjvanvuuren** [Cinchoo/ChoETL#209]
In order to deal with the conversion of complex, nested json structures into table format, I perform a union on the subsets, and expect all  columns in the subsets to be present in the result set. But depending on the use of ``ChoJSONRecordConfiguration``, this is not always the case. This example does **NOT** work:
```
var json = @"
{
    ""A"": ""a_val"",
    ""B"": ""b_val"",
    ""C"": ""c_val"",
    ""D"": ""d_val""
}";

var cfg = new ChoJSONRecordConfiguration
{
    Culture = CultureInfo.InvariantCulture
};

using 
(
    var r = ChoJSONReader.LoadText(json, cfg)
        .WithField("A", jsonPath: "$.A", typeof(string), fieldName: "Field_A")
        .WithField("B", jsonPath: "$.B", typeof(string), fieldName: "Field_B")
        .WithField("C", jsonPath: "$.C", typeof(string), fieldName: "Field_C")
)
using 
(
    var s = ChoJSONReader.LoadText(json, cfg)
        .WithField("A", jsonPath: "$.A", typeof(string), fieldName: "Field_A")
        .WithField("B", jsonPath: "$.B", typeof(string), fieldName: "Field_B")
        .WithField("D", jsonPath: "$.D", typeof(string), fieldName: "Field_D")
)
{
    r.Union(s).Dump();
}
```

Only ``Field_A``, ``Field_B``, and ``Field_D`` are present in the results.

But as soon as I remove one of the configurations from ``ChoJSONReader``, OR use different instances of ``ChoJSONRecordConfiguration``, all 4 fields are present again, as is my intention. It seems the 2 supplied configurations cause an internal conflict.

**Comment by gjvanvuuren** [comment]
I discovered a new variant of the issue. The following code works:
```
var json = @"
{
    ""A"": ""a_val"",
    ""B"": ""b_val"",
    ""C"": ""c_val"",
    ""D"": ""d_val""
}";

using 
(
    var r = new ChoJSONReader(new StringBuilder(json))
        .WithField("A", jsonPath: "$.A", typeof(string), fieldName: "Field_A")
        .WithField("B", jsonPath: "$.B", typeof(string), fieldName: "Field_B")
        .WithField("C", jsonPath: "$.C", typeof(string), fieldName: "Field_C")
        .Configure(cjsonr => cjsonr.Culture = CultureInfo.InvariantCulture)
)
using 
(
    var s = new ChoJSONReader(new StringBuilder(json))
        .WithField("A", jsonPath: "$.A", typeof(string), fieldName: "Field_A")
        .WithField("B", jsonPath: "$.B", typeof(string), fieldName: "Field_B")
        .WithField("D", jsonPath: "$.D", typeof(string), fieldName: "Field_D")
        .Configure(cjsonr => cjsonr.Culture = CultureInfo.InvariantCulture)
)
{
    r.Union(s).Dump();
}
```

But as soon as I replace ``r.Union(s).Dump();`` with ``r.Union(s).AsDataTable().Dump();``, one of the fields is missing again.

**Comment by Cinchoo** [comment]
> In order to deal with the conversion of complex, nested json structures into table format, I perform a union on the subsets, and expect all columns in the subsets to be present in the result set. But depending on the use of `ChoJSONRecordConfiguration`, this is not always the case. This example does **NOT** work:
> 
> ```
> var json = @"
> {
>     ""A"": ""a_val"",
>     ""B"": ""b_val"",
>     ""C"": ""c_val"",
>     ""D"": ""d_val""
> }";
> 
> var cfg = new ChoJSONRecordConfiguration
> {
>     Culture = CultureInfo.InvariantCulture
> };
> 
> using 
> (
>     var r = ChoJSONReader.LoadText(json, cfg)
>         .WithField("A", jsonPath: "$.A", typeof(string), fieldName: "Field_A")
>         .WithField("B", jsonPath: "$.B", typeof(string), fieldName: "Field_B")
>         .WithField("C", jsonPath: "$.C", typeof(string), fieldName: "Field_C")
> )
> using 
> (
>     var s = ChoJSONReader.LoadText(json, cfg)
>         .WithField("A", jsonPath: "$.A", typeof(string), fieldName: "Field_A")
>         .WithField("B", jsonPath: "$.B", typeof(string), fieldName: "Field_B")
>         .WithField("D", jsonPath: "$.D", typeof(string), fieldName: "Field_D")
> )
> {
>     r.Union(s).Dump();
> }
> ```
> 
> Only `Field_A`, `Field_B`, and `Field_D` are present in the results.
> 
> But as soon as I remove one of the configurations from `ChoJSONReader`, OR use different instances of `ChoJSONRecordConfiguration`, all 4 fields are present again, as is my intention. It seems the 2 supplied configurations cause an internal conflict.

Well, if you are sharing the same config among readers, you must construct one with all fields up front and use them in the readers.  

sample:

```
          var cfg = new ChoJSONRecordConfiguration
            {
                Culture = CultureInfo.InvariantCulture
            }
            .Map("A", jsonPath: "$.A", fieldName: "Field_A", fieldType: typeof(string))
            .Map("B", jsonPath: "$.B", fieldName: "Field_B", fieldType: typeof(string))
            .Map("C", jsonPath: "$.C", fieldName: "Field_C", fieldType: typeof(string))
            .Map("D", jsonPath: "$.D", fieldName: "Field_D", fieldType: typeof(string))
            ;

```

**Comment by gjvanvuuren** [comment]
Thanks! I haven't come across the Map function in any of the online resources. Makes a lot of sense to do it this way.

**Comment by gjvanvuuren** [comment]
I thought I understood, but I'm totally confused now. How does the ``.WithField`` and ``.Map`` complement or contradict each other?
I have 2 ``ChoJSONReader`` instances. I want to share a common configuration, and want the same fields in the result, but I have 2 different ``valueConverter``s - a different one for each ``ChoJSONReader``. The ``valueConverter``s I have to specify in the ``.WithField`` declaration, but the fields are specified in the ``.Map`` statement.

```
var json = @"
{
    ""A"": ""a_val"",
    ""B"": { ""b_arr"": [ 1, 2 ] },
    ""C"": ""c_val"",
    ""D"": { ""d_arr"": [ 3, 4 ] }
}";

var cfg = new ChoJSONRecordConfiguration
{
    Culture = CultureInfo.InvariantCulture
}

  .Map("A", jsonPath: "$.A", fieldName: "Field_A", fieldType: typeof(string))
  .Map("B", fieldName: "Field_B", fieldType: typeof(decimal))
  .Map("C", jsonPath: "$.C", fieldName: "Field_C", fieldType: typeof(string))
  .Map("D", fieldName: "Field_D", fieldType: typeof(decimal))
  ;

using 
(
    var r = new ChoJSONReader(new StringBuilder(json), cfg)
  .WithField("B", jsonPath: "$.B.b_arr[*]", valueConverter: o => { var v = o as IList; /* do something */ return v; })
)
using 
(
    var s = new ChoJSONReader(new StringBuilder(json), cfg)
  .WithField("D", jsonPath: "$.D.d_arr[*]", valueConverter: o => { var v = o as IList; /* do something */ return v; })
)
{
    r.Union(s).Dump();
}
```

This doesn't work. I have to use `.WithField` for all fields in both `using` blocks, like so:

```
using 
(
    var r = new ChoJSONReader(new StringBuilder(json), cfg)
  .WithField("A", jsonPath: "$.A", fieldName: "Field_A", fieldType: typeof(string))
  .WithField("B", jsonPath: "$.B.b_arr[*]", valueConverter: o => { var v = o as IList; /* do something */ return v; })
  .WithField("C", jsonPath: "$.C", fieldName: "Field_C", fieldType: typeof(string))
)
using 
(
    var s = new ChoJSONReader(new StringBuilder(json), cfg)
  .WithField("A", jsonPath: "$.A", fieldName: "Field_A", fieldType: typeof(string))
  .WithField("C", jsonPath: "$.C", fieldName: "Field_C", fieldType: typeof(string))
  .WithField("D", jsonPath: "$.D.d_arr[*]", valueConverter: o => { var v = o as IList; /* do something */ return v; })
)
```

But then I'm back to the problem I originally had: Passing the configuration to the second ``using`` block causes ``Field_B`` to be dropped. The only solution seems to be to create 2 instances of the same configuration, cfg1 and cfg2, but this is a very strange  way to go about. And I don't understand why 2 readers cannot share the same configuration.

**Comment by Cinchoo** [comment]
Use `Map` overload to set value converter and other field level properties as below

```
            var cfg = new ChoJSONRecordConfiguration
            {
                Culture = CultureInfo.InvariantCulture
            }
            .Map("A", fc =>
            {
                fc.JSONPath("$.A");
                fc.FieldName("Field_A");
                fc.FieldType(typeof(string));
                fc.ValueConverter(o => { var v = o as IList; /* do something */ return v; });
            })
            .Map("B", jsonPath: "$.B", fieldName: "Field_B", fieldType: typeof(string))
            .Map("C", jsonPath: "$.C", fieldName: "Field_C", fieldType: typeof(string))
            .Map("D", jsonPath: "$.D", fieldName: "Field_D", fieldType: typeof(string))
            ;
```

**Comment by gjvanvuuren** [comment]
Thank you. I followed your suggestion. My code:

```
var json = @"
{
    ""A"": 5.5,
    ""B"": { ""b_arr"": [ 1.1, 2.2 ] },
    ""C"": ""c_val"",
    ""D"": { ""d_arr"": [ 3.3, 4.4 ] }
}";

var cfg = new ChoJSONRecordConfiguration
{
    Culture = CultureInfo.InvariantCulture
}
.Map("A", jsonPath: "$.A", fieldName: "Field_A", fieldType: typeof(decimal))
.Map("B", fc =>
{
    fc.JSONPath("$.B.b_arr[*]");
    fc.FieldType(typeof(decimal));
    fc.ValueConverter(o => { var v = o as IList; return v.OfType<dynamic>().Select(i => new { i }); });
})
.Map("C", jsonPath: "$.C", fieldName: "Field_C", fieldType: typeof(string))
.Map("D", fc =>
{
    fc.JSONPath("$.D.d_arr[*]");
    fc.FieldType(typeof(decimal));
    fc.ValueConverter(o => { var v = o as IList; return v.OfType<dynamic>().Select(i => new { i }); });
});

using
(
    var r = ChoJSONReader.LoadText(json, cfg)
)
```

Two problems I observed with this approach:

1. The ``fieldName: `` setting, where specified, is ignored. The columns are output as A, B, C, D
2. The table structure is wrong. For the given json contents, the table should be:
```
Field_A | Field_B | Field_C | Field_D
5.5 | 1.1 | c_val |
5.5 | 2.2 | c_val |
5.5 | | c_val | 3.3
5.5 | | c_val | 4.4
```
Using the ``.Map`` approach places everything on one level. But Field_B and Field_D should be on different levels, which I can only achieve by doing a Union on two differently configured readers.

**Comment by gjvanvuuren** [comment]
Thanks again for the example. My question was more about the unexpected side effects of using a shared ``ChoJSONRecordConfiguration``, and less about the JSON. But I can see now that using the inline ``.Configure`` is the only way to go when using multiple readers, and that using a shared instance of ``ChoJSONRecordConfiguration`` will cause issues.
