### ISSUE TITLE
Cannot read CSV file without header and empty field

### ISSUE THREAD

**Issue by code2learnit** [Cinchoo/ChoETL#21]
I have a simple CSV file made of 3 field (pipe separated), the second of which is empty, like the following

some||1234

I'm trying to read it using 

` var reader = new ChoCSVReader(csvFilePath).WithDelimiter("|");`

but getting a "At least one of the field header is empty." exception message in ChoETL.ChoCSVRecordReader.GetHeaders(String line)

I tried to use .WithFirstLineHeader(false) or a POCO object without any success.

any clue?
thanks

stefano

**Comment by Cinchoo** [comment]
Put a fix, take the latest. Let me know if that works.

**Comment by code2learnit** [comment]
NuGet package 1.0.8.7 works like a charm!
thank you :)

stefano

**Comment by ivanoalberti** [comment]
I have the same problem with version 1.2.1.64

Not having a header I set WithFirstLineHeader(false) and get the exception "Atleast one of the field header is empty".
Trying to set WithFirstLineHeader(true) works, but I'm clearly missing the first line.

thanks
Ivano
