### ISSUE TITLE
Does not handle CSV Values with Double Quote 

### ISSUE THREAD

**Issue by alfredomi** [Cinchoo/ChoETL#227]
ID,TIN,PROVIDER,NEIGHBOR,DRIVERNO,DRIVERNO2,LASTNAME,FIRSTNAME
"","052965646","1760638008","BRYAN, RICKY","898082","899082","LO"PEZ JAINA","ROBERTO"

I have a file with content shown above, this will fail to handle the value for Lastname = "LO"PEZ JAINA", the result will give me like Lastname and Firstname is combined.

I'm using the code below:
using (var p = new ChoCSVReader<Info>(file))
 {
     foreach (Info m in p.WithFirstLineHeader().QuoteAllFields(true)) 
     { 

     }
}

public partial class Info
{
        [ChoCSVRecordField(1, FieldName = "ID")]
        public string ID { get; set; }

        [ChoCSVRecordField(2, FieldName = "TIN")]
        public string TIN { get; set; }

        [ChoCSVRecordField(3, FieldName = "PROVIDER")]
        public string PROVIDER { get; set; }

        [ChoCSVRecordField(4, QuoteField = true, FieldName = "NEIGHBOR")]
        public string NEIGHBOR { get; set; }

        [ChoCSVRecordField(5, QuoteField = true, FieldName = "DRIVERNO")]
        public string DRIVERNO { get; set; }

        [ChoCSVRecordField(6, QuoteField = true)]
        public string DRIVERNO2 { get; set; }

        [ChoCSVRecordField(7, QuoteField = true)]
        public string LASTNAME { get; set; }

        [ChoCSVRecordField(8, QuoteField = true)]
        public string FIRSTNAME { get; set; }
}

**Comment by Cinchoo** [comment]
This is invalid CSV. The quotes must be escaped with 2 quotes `"LO""PEZ JAINA"` in order to handle it.

```
ID,TIN,PROVIDER,NEIGHBOR,DRIVERNO,DRIVERNO2,LASTNAME,FIRSTNAME
"","052965646","1760638008","BRYAN, RICKY","898082","899082","LO""PEZ JAINA","ROBERTO"
```

**Comment by alfredomi** [comment]
I can't say that it is invalid csv, but given that i have that kind of .csv
file ..i'm seeing that it is not solveable with this parser.

Thanks
