### ISSUE TITLE
Load from an api

### ISSUE THREAD

**Issue by abdolrhman** [Cinchoo/ChoETL#23]
can i load the response of json from an api ???
@Cinchoo

**Comment by Cinchoo** [comment]
I'm not getting you. Please explain in detail. Sample would help.

**Comment by Cinchoo** [comment]
If I'm understanding correctly, you want to pass the json response stream to the library to parse it. 

Yes, you can. One of the ChoJSONReader constructor overload takes stream as parameter. Hope this helps.
