### ISSUE TITLE
Incorrect Offset when ChoJSONReader parses a string as DateTimeOffset

### ISSUE THREAD

**Issue by gjvanvuuren** [Cinchoo/ChoETL#234]
I'm using ChoETL.JSON.NETStandard v1.2.1.49-beta2.

When I declare a `DateTimeOffset` field using `.WithField`, the parsing of the `.Offset` component is handled incorrectly compared to the .NET `DateTimeOffset` type. Specifying a `ChoTypeConverterFormatSpec` doesn't make a difference.

```
var json = @"{
  ""TimestampGlobal"": ""2022-08-06T19:36:46.1043075+00:00""
}";

using
(
    var r = ChoJSONReader.LoadText(json)
        .WithField("TimestampGlobal", jsonPath: "$.TimestampGlobal", fieldType: typeof(DateTimeOffset), fieldName: "TimestampGlobal")
        .Configure(c => c.Culture = CultureInfo.InvariantCulture)
        .Configure(c => c.TypeConverterFormatSpec = new ChoTypeConverterFormatSpec { DateTimeFormat = "o" })
)
{
    var dt1 = r.Select(k => k.AsDictionary()["TimestampGlobal"]).Cast<DateTimeOffset>().First();
    dt1.Offset.Print(); // 02:00:00

    // Compare with .NET
    var dt2 = DateTimeOffset.Parse("2022-08-06T19:36:46.1043075+00:00");
    dt2.Offset.Print(); // 00:00:00
}
```

**Comment by Cinchoo** [comment]
there was a bug, applied fix. pushed new package. uninstall, reinstall ChoETL.JSON.NETStandard v1.2.1.49-beta3

Projects must reference to below pakages versions. 
ChoETL.Core v1.2.1.49 (beta3)
ChoETL.JSON.Core v1.2.1.49 (beta3)

Sample fiddle: https://dotnetfiddle.net/vbtyr0

**Comment by gjvanvuuren** [comment]
Thanks, this fixes the issue for me.
