### ISSUE TITLE
Possible regression error or breaking changes after ChoETL.JSON.NETStandard v1.2.1.44

### ISSUE THREAD

**Issue by gjvanvuuren** [Cinchoo/ChoETL#235]
After updating the `ChoETL.JSON.NETStandard` nuget to the latest beta version (`v1.2.1.49-beta3`) due to a bugfix, I did a regression test, and noticed that for some of my json files, my code doesn't deliver the content as it used to.

In the fiddle below, using the latest pre-45 version (`v1.2.1.43`), a full table structure is returned:

[https://dotnetfiddle.net/10W9S1](https://dotnetfiddle.net/10W9S1)

But updating to a `v1.2.1.45` or later causes an empty table to be returned.

Is this a bug, or was the behaviour changed by design? In case of the latter, is there a way to get the old behaviour?

**Comment by Cinchoo** [comment]
Found the issue, fixed it. New package avail: ChoETL.JSON.Core v1.2.1.49 (beta4)

Sample fiddle: https://dotnetfiddle.net/7YBcqt

Thanks for reporting.

**Comment by gjvanvuuren** [comment]
Fantastic! That solves the issue. Thanks for the fast response.
