### ISSUE TITLE
ReflectionTypeLoadException when using ChoCSVReader()

### ISSUE THREAD

**Issue by code2learnit** [Cinchoo/ChoETL#24]
Hi, 
I'm using ChoCSVReader (with POCO) to load a file 
My POCO contains a bunch of string properties.

When I hit the following code 

`var reader = new ChoCSVReader<csvRow>(csvFilePath, config).WithDelimiter("|");` 

I get a couple of

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   in System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   in System.Reflection.RuntimeModule.GetTypes()
   in System.Reflection.Assembly.GetTypes()
   in ChoETL.ChoType.ExtractTypes(Type attributeType, ArrayList types, Assembly assembly)

I tried to delete my obj and bin and recompile, but it does not solve

I'm using Nuget version 1.0.8.7 (I think it is the latest)

any suggestion?

TIA

stefano

**Comment by Cinchoo** [comment]
That must be warning messages, should be ignorable.

**Comment by Cinchoo** [comment]
Thanks for the input. 

I've added couple of members in ChoETLFrxBootstrap to control the loading of referenced assemblies.

EnableLoadingReferencedAssemblies - Now the framework disable this feature by default. If you want to enable, just set this flag to true at the application startup.

IgnoreLoadingAssemblies - If you want to exclude selective assemblies from loading, you can add them to this list (either assembly full path / just file name with extension). This will be effective only when EnableLoadingReferencedAssemblies  = true.

Pull the latest, give it a try. Let me know. Appreciate your help. Thx

**Comment by code2learnit** [comment]
wow!
thank you very much
It works
