### ISSUE TITLE
Automatic field renaming causes conflict with existing field

### ISSUE THREAD

**Issue by gjvanvuuren** [Cinchoo/ChoETL#240]
I'm using ChoETL.JSON.Core v1.2.1.49 (beta4).

I have the following JSON string:

```
var json = @"
{
  ""Name"": ""ABC"",
    ""Data"": {
        ""Result"": ""ok"",
        ""Results"": [
            ""x"",
            ""y""
        ]
    }
}";
```

In the JSON, I have a scalar `Result` field, and an array `Results[]`. ChoETL automatically renames the array to `Result`, which causes a conflict with the scalar `Result` field. The scalar field is dropped from the resulting flattened table:

```
var json = @"
{
  ""Name"": ""ABC"",
    ""Data"": {
        ""Result"": ""ok"",
        ""Results"": [
            ""x"",
            ""y""
        ]
    }
}";

using
(
    var r = ChoJSONReader.LoadText(json)
        .WithField("Name", jsonPath: "$.Name", typeof(string), fieldName: "Name")
        .WithField("DataResult", jsonPath: "$.Data.Result", typeof(string), fieldName: "DataResult")
        .WithField("DataResults", jsonPath: "$.Data.Results[*]", typeof(string[]), fieldName: "DataResults")
)
{
    r.Flatten().AsDataTable().Print();
}
```

Is there a way to disable the auto-renaming? I couldn't find a configuration setting for this.

**Comment by Cinchoo** [comment]
Applied fix, take v1.2.1.49-beta5 and give it try.

Use `r.Flatten(true).AsDataTable().Print();' to handle it.

**Comment by gjvanvuuren** [comment]
The API doesn't accept the signature `.Flatten(true)`. I tried `.Flatten(ignoreDictionaryFieldPrefix:true)`, but an empty result is returned.

**Comment by Cinchoo** [comment]
Missed to push the base lib. 

Pushed it, take ChoETL.JSON.NETStandard 1.2.1.49-beta6

**Comment by gjvanvuuren** [comment]
Issue fixed. Thanks.
