### ISSUE TITLE
ChoAvroWriter fails with IDataReader

### ISSUE THREAD

**Issue by relcodedev** [Cinchoo/ChoETL#241]
The following code fails on parser.write(reader) with MoveNext does not exist in ListDictionary.
Note: same code using the ChoParquetWriter works. 

dotnet 6 console app 
    <PackageReference Include="choetl.avro" Version="1.0.0.12" />
    <PackageReference Include="choetl.parquet" Version="1.0.1.22" />

        var conn = new SqlConnection(connectionString);

       
        using(var cmd = new SqlCommand("select * from tablename order by  1", conn))
        {

            conn.Open();
            cmd.CommandTimeout = 300;  
            using (var reader = cmd.ExecuteReader())
            {
                var outputFile = "tablename.avro";

                using (var parser = new ChoAvroWriter(outputFile))
                {
                    if (reader.HasRows)
                    {   
                        parser.Write(reader);
                    }
                }
            }

        }

-------------------------Exception--------------------------------------------------------------------------------------------
An application error occurred. Please contact the administrator with the following information:
3

1) Exception Information
*********************************************
Exception Type: ChoETL.ChoParserException
TargetSite: Boolean MoveNext()
Message: Missing valid writer object passed.
Data: System.Collections.ListDictionaryInternal
HelpLink: NULL
Source: ChoETL.Avro
HResult: -2146232832

StackTrace Information
*********************************************
   at ChoETL.ChoAvroRecordWriter.WriteTo[T](Object writer, IEnumerable`1 records, Func`2 predicate)+MoveNext()
   at ChoETL.ChoAvroWriter`1.Write(T record)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at ChoETL.ChoAvroWriter`1.Write(IDataReader dr)

**Comment by Cinchoo** [comment]
applied fix, pushed new package v1.0.0.13-beta1. try and let me know.

**Comment by relcodedev** [comment]
Worked. Thanks!

**Comment by relcodedev** [comment]
Is there a way to snappy compression like in parquet?  I tried snappy but only deflate would work.

**Comment by relcodedev** [comment]
If I use both packages choetl.avro 1.0.0.13-beta1 and choetl.parquet 1.0.1.22 in the same cli, avro works with compression but parquet stop writing. It creates a blank parquet file with no errors.  I commented out the avro function and removed avro beta package and parquet started working again.  Very strange.

**Comment by relcodedev** [comment]
I will create a new issue for this.
