### ISSUE TITLE
ChoCSVLiteReader : Stream is not closed

### ISSUE THREAD

**Issue by fosterz** [Cinchoo/ChoETL#242]
While using ChoCSVLiteReader, I am facing file locked issue in dotnetcore 6. Here is the snippet that I am using :
```
using (var r = new ChoCSVLiteReader())
            {
                productList.AddRange(r.ReadFile<MyClass>(filePath, true, mapper: (lineno, cols, rec) =>
                {
                    rec.Name = cols[0];
                    rec.Code = cols[1];                    
                }));
            }     
```
 Error : The process cannot access the file 'xyz.csv' because it is being used by another process when I try to delete the file once I am done with it.

**Comment by Cinchoo** [comment]
applied fix, pushed new package.

ChoETL.NETStandard.1.2.1.49-beta5

Try and let me know. Thanks for reporting.
