### ISSUE TITLE
DateTime being converted

### ISSUE THREAD

**Issue by optometristPrime** [Cinchoo/ChoETL#247]

**Comment by AmarokPrime13** [comment]
Hello,

I need some help understanding why the DateTime values from my json file is being converted to a different time zone. I am using ChoETL.Parquet v1.0.1.23 (beta6).

`class SomeType
    {
        public DateTime CreateDate { get; set; }
        public DateTime LastModDate { get; set; }
    }`

`var createDate = DateTime.Parse("2022-10-13T11:30:19.3675716");
            var defaultDateTime = DateTime.Parse("1900-01-01T00:00:00");

            var parquetConfig = new ChoParquetRecordConfiguration();
            parquetConfig.ParquetRecordFieldConfigurations
                .Add(new ChoParquetRecordFieldConfiguration("CreateDate") { FieldType = typeof(DateTime?), IsNullable = true, DefaultValue = defaultDateTime, });
            parquetConfig.ParquetRecordFieldConfigurations
                .Add(new ChoParquetRecordFieldConfiguration("LastModDate") { FieldType = typeof(DateTime?), IsNullable = true, DefaultValue = defaultDateTime });

            using (var w = new ChoParquetWriter<SomeType>(@$"{filePath}", parquetConfig).Configure(c => c.CompressionMethod = Parquet.CompressionMethod.Snappy)
                  )
            {
                w.Write(new SomeType
                {
                    CreateDate = createDate,
                    LastModDate = defaultDateTime
                });
            }

            using (var r = new ChoParquetReader(filePath))
            {
                r.AsDataTable().Print();
            }`

The output is CreateDate,LastModDate
10/13/2022 5:30:19 PM +00:00,1/1/1900 7:00:00 AM +00:00

How can I keep the DateTime values as their original values? Thanks for the help!
