### ISSUE TITLE
Convert a Value from string to bool

### ISSUE THREAD

**Issue by WolfAlvein** [Cinchoo/ChoETL#249]
Hi Cinchoo, sorry to disturb you, I wanted to ask if you can help me a moment to convert a CSV field which has the values "FALSE" , "TRUE" into boolean values, I have tried this:

                using (var csvParser = ChoCSVReader.LoadText(header + Environment.NewLine + _csvData)
                                                                            .WithFirstLineHeader()
                                                                            .ThrowAndStopOnMissingField(false)
                                                                            .Configure(c => c.LiteParsing = true)
                                                                            .Configure(c => c.NestedColumnSeparator = '/')
                                                                            .Configure(c => c.FieldValueTrimOption = ChoFieldValueTrimOption.None))
                {
                    if (t == typeof(CapNVDTechnical))
                    {
                        csvParser.WithField<CapNVDTechnical>(c => c.ValueBoolean, valueConverter: (v) => bool.Parse(v as string));
                    }

                    ChoJSONRecordConfiguration jsonConfig = new ChoJSONRecordConfiguration();
                    jsonConfig.LiteParsing = true;
                    jsonConfig.IgnoreFieldValueMode = ChoIgnoreFieldValueMode.Any;
                    jsonConfig.FieldValueTrimOption = ChoFieldValueTrimOption.None;

                    using (var jsonParser = new ChoJSONWriter(jsonStream, jsonConfig))
                    {
                        jsonParser.Write(csvParser);
                    }
                }

but I'm getting a error in the line `csvParser.WithField<CapNVDTechnical>(c => c.ValueBoolean, valueConverter: (v) => bool.Parse(v as string));` in the part: `c.ValueBoolean`, where it says: "An expression tree may not contain a dynamic operation".

Thank you for your help.

**Comment by Cinchoo** [comment]
Cinchoo ETL handles 'TRUE' / 'FALSE' to boolean values out of the box.

Here is working sample

https://dotnetfiddle.net/qRnnkr

If you are facing different issue, pls share sample CSV along with code. Thanks.

**Comment by WolfAlvein** [comment]
> Cinchoo ETL handles 'TRUE' / 'FALSE' to boolean values out of the box.
> 
> Here is working sample
> 
> https://dotnetfiddle.net/qRnnkr
> 
> If you are facing different issue, pls share sample CSV along with code. Thanks.

In what .Net Core framework should I use has a minimum for this to work correctly? The project is in .Net Core 2.0 and I think I can't upgrade it.

**Comment by Cinchoo** [comment]
it should work .net core 2 as well.

Make sure u use ChoETL.JSON.NETStandard package.

**Comment by WolfAlvein** [comment]
> it should work .net core 2 as well.
> 
> Make sure u use ChoETL.JSON.NETStandard package.

Hi thank you for the reply, Yes I'm using both ChoETL.JSON.NETStandard package and ChoETL.NETStandard package, would using both cause the issue I have?

**Comment by WolfAlvein** [comment]
> it should work .net core 2 as well.
> 
> Make sure u use ChoETL.JSON.NETStandard package.

Hi Cinchoo sorry to disturb you, where you able to see my last reply?

**Comment by WolfAlvein** [comment]
Hi @Cinchoo, any update regarding this issue?

**Comment by WolfAlvein** [comment]
> Well, looked at your sample file, found out the boolean column has not only TRUE/FALSE values, has N/E/42E etc. seems like this field is not boolean field. You must treat it as string.
> 
> Hope it helps.

Hi Cinchoo thank you, I will look into the file that I sent you and make sure that the columns are correct, I'm downloading a new file to verify but I think that was not the issue when I tried it.

**Comment by WolfAlvein** [comment]
> Well, looked at your sample file, found out the boolean column has not only TRUE/FALSE values, has N/E/42E etc. seems like this field is not boolean field. You must treat it as string.
> 
> Hope it helps.

Hi Cinchoo, so I verified the document and the only column that should be treated has a pure boolean is the last one (Column H), the clumn before (G) is not a boolean and it's treated as a string, this is the POCO that is used to transform the info:

`
using Newtonsoft.Json;
using System;

namespace DTO
{
    public class NVDTechnical
    {
        #region "Fields"

        #endregion

        #region "Properties"

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int CapId { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int TechCode { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public DateTime EffectiveFrom { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public DateTime EffectiveTo { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public DateTime ValueDatetime { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public float ValueFloat { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string ValueString { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public bool? ValueBoolean { get; set; }

        #endregion

        #region "Constructors"

        public VDTechnical()
        {

        }

        #endregion

        #region "Methods"

        #endregion
    }
}
` 

Has you can see the only column that I'm treating has a bool is the last one, any other idea of what could be happening?

**Comment by Cinchoo** [comment]
wrote sample fiddle, https://dotnetfiddle.net/lV1W7v

lets use this to discuss. review and explain what is missing.

**Comment by WolfAlvein** [comment]
> 

Hi Cinchoo, yes please let's try and solve this.

Sorry for not responding before but I didn't want to bother you during the weekend and I think we have a big time difference (I'm in spain), Thank you.

**Comment by WolfAlvein** [comment]
> wrote sample fiddle, https://dotnetfiddle.net/lV1W7v
> 
> lets use this to discuss. review and explain what is missing.

Hi Cinchoo I have finished working with this issue, finally after the Project owner talked with me we got to an agreement where the boolean values are not needed, so I will be omitting them and will simply set them as String in the POCO, after that there is no more problems and I can work without any issues, Thank you.
