### ISSUE TITLE
Parquet: Issues with nullable values

### ISSUE THREAD

**Issue by optometristPrime** [Cinchoo/ChoETL#251]
Hello,

I am having two issues when working with nullable values with the Parquet writer.

The first issue is that in this example that you posted: [https://dotnetfiddle.net/TM2dW4](https://dotnetfiddle.net/TM2dW4) the output is:

ChoETL.Parquet v1.0.1.22
Id,Price,Quantity
,1.3,2.45

If I use the same code as the example above and upgrade the version I get this output:
ChoETL.Parquet v1.0.1.24
Id,Price,Quantity
0,1.3,2.45

How can I keep the empty/null value when Id = null in the current version?

The second issue is that if I try to read from a list, the records in the Parquet value are being moved and the records are not correct when using nullable values.

`public static void Main()
		{
			ChoETLFrxBootstrap.TraceLevel = System.Diagnostics.TraceLevel.Error;
			typeof(ChoParquetReader).GetAssemblyVersion().Print();

			var tradeList = new List<Trade>();

			var trade1 = new Trade()
			{
				Quantity = 2
			};

			var trade2 = new Trade()
			{
				Id = 100
			};

			tradeList.Add(trade1);
			tradeList.Add(trade2);

			using (var w = new ChoParquetWriter<Trade>(@$"{Rootfolder}\Trade3.parquet")
				  )
			{
				w.Write(tradeList);
			}

			PrintParquetFile(@$"{Rootfolder}\Trade3.parquet");
		}

		static void PrintParquetFile(string filePath)
		{
			using (var r = new ChoParquetReader(filePath))
			{
				r.AsDataTable().Print();
			}
		}

		public class Trade
		{
			public int? Id { get; set; }
			public double? Price { get; set; }
			public double? Quantity { get; set; }
		}
	}`

and the output is:
ChoETL.Parquet v1.0.1.24
Id,Price,Quantity
100,0,2
0,0,0

When it should be
Id,Price,Quantity
0,0,2
100,0,0

Please let me know if I should open a separate issue for either of these problems.
Thanks for the help!

**Comment by Cinchoo** [comment]
thanks for reported it. Put a fix, released packages

ChoETL.Parquet -Version 1.0.1.25-beta1
ChoETL.NETStandard -Version 1.2.1.51-beta1

try and let me know.

**Comment by optometristPrime** [comment]
Hello, I tried the beta and it looks like there is an issue with non-null string values being written. If I add the property string Name to Trade and give it a value, the actual value is not being written.

public class Trade
{
    public long? Id { get; set; }
    public double? Price { get; set; }
    public double? Quantity { get; set; }
    public string Name {get; set; }
}

`w.Write(new Trade
					{
						Id = null,
						Price = 2.3,
						Quantity = 2.45,
						Name = "Name"
					});`

Here is the output:
ChoETL.Parquet v1.0.1.25 (beta1)
Id,Price,Quantity,Name
,2.3,2.45,

**Comment by Cinchoo** [comment]
Pls try with ChoETL.NETStandard -Version 1.2.1.51-beta3
let me know. thx.

**Comment by Cinchoo** [comment]
Pls take v1.0.1.25-beta2 and give it try. let me know.

**Comment by svanjole** [comment]
Unfortunately this still isn't resolved in v1.0.1.25-beta2. Is this issue still being looked at?

It works for strings and DateTime? properties but unfortunately long? and double? are serialized with value 0 instead of null
See https://dotnetfiddle.net/5wJYX7

**Comment by Cinchoo** [comment]
latest release fixes them

https://dotnetfiddle.net/UEgjdt

**Comment by gbahsa** [comment]
Hi, 

The latest release fixes them but i noticed in the schema parquet the type is String for nullable values and not the original Type. Could you please help me with that ?

**Comment by jsn-m** [comment]
Also picking this up, but not only with Dates. I see it on Integers as well. Dates default to "0001-01-01 00:00:00". Integers default to "0". In my case even setting a defaultValue using `w.WithField(name: Name, defaultValue: DateTime.Parse("1970-01-01 00:00:00"))` doesn't get respected.

**Comment by RichN7** [comment]
New to ChoETL.Parquet. Got the latest version today. Is this issue (bug) resolved. Found ParquetWriter is not writing null values when a nullable DateTime column in my DataTable contains a null value. Instead I find the value is DateTime.MinValue. Same thing for interger columns (get 0 instead of null).  String column has empty string instead of null.

When using Parquet.Net directly and writing a POCO containing DateTime? member and Int? member, the output contains nulls where expected.

**Comment by RichN7** [comment]
Additional interesting fact. Using ChoParqueWriter with a POCO produces the correct output (with null values in DateTime and Int and String).  It is only when writing a DataTable that nulls switch to the default value of each data type.

**Comment by Cinchoo** [comment]
Yes, this is expected behaviour. Datatable doesn't support nullable types.
