### ISSUE TITLE
Data is using CSV comma Delimiter

### ISSUE THREAD

**Issue by WolfAlvein** [Cinchoo/ChoETL#259]
Hi Cinchoo, I have a small problem with a delimiter that comes within the CSV data that I'm reading, in this case in the column: "Derivative", there is one row that has a value has "Maverick X RS SAS Turbo RR Intense Blue, Carbon Bl", but the ChoCSVReader is separating that value by the comma delimiter, so the Carbon BI is getting moved to the "DerivativeIntroducedYear", is there anyway to fix this issue?

Here is a copy of the data: https://docs.google.com/document/d/1s3sf3ffkyphOwjFq6LqlmtYVpCaFimidF1vF5cnKzuw/edit?usp=share_link

I have tried to use the QuoteField in the class that has the problem, but it was ignored and I still get the error mentioned before:

          using ChoETL;
          using Newtonsoft.Json;
          using System;
          using System.Collections.Generic;
          using System.Text;
          
          namespace FicresUK.CAP.Core.ValueObjects
          {
              public class CapVehicleCodeDesc
              {
                  #region "Fields"
          
                  #endregion
          
                  #region "Properties"
          
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string CapCode { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public int CapId { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string Manufacturer { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string ShortModel { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string Model { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public int? ModelIntroduced { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public int? ModelDiscontinued { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string ShortDerivative { get; set; }
                  [ChoCSVRecordField(QuoteField = true)]
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string Derivative { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public int? DerivativeIntroducedYear { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public int? DerivativeDiscontinuedYear { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string AvailableNewVehicle { get; set; }
                  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
                  public string VehicleType { get; set; }
          
          
          
                  #endregion
          
                  #region "Constructors"
          
                  public CapVehicleCodeDesc()
                  {
          
                  }
                  #endregion
          
                  #region "Methods"
          
          
                  #endregion
              }
          }

**Comment by Cinchoo** [comment]
these seems to be issue with QuoteField value is not respected by framework. I'm putting fix. 

In the mean time, you can do with this workaround using `MayHaveQuotedFields` on the reader to parse the csv file successfully. Sample fiddle below.

https://dotnetfiddle.net/Gh0YTI

**Comment by Cinchoo** [comment]
Here is the working sample using `[ChoCSVRecordField(QuoteField = true)]` with ChoETL.Core v1.2.1.51 (beta5)

https://dotnetfiddle.net/gdjALv

**Comment by WolfAlvein** [comment]
> 

Thank you very much, I have updated to the latest stable version and have added the 'MayHaveQuotedFields' to the parser, will test it an let you know.

**Comment by WolfAlvein** [comment]
> > 
> 
> Thank you very much, I have updated to the latest stable version and have added the `MayHaveQuotedFields` to the parser, will test it an let you know.

Hi Cinchoo, thank you for the help, at the end I was able to solve the issue by using the `QuoteAllFields` method in the parser.
