### ISSUE TITLE
XML Reader and Array

### ISSUE THREAD

**Issue by code2learnit** [Cinchoo/ChoETL#26]
Hi
I modified a bit the example in the tutorial https://www.codeproject.com/Articles/1171289/Cinchoo-ETL-Xml-Reader, and I'm trying to load the following XML

```
<Employees>
    <Employee Id='1'>
        <Name>Tom</Name>
        <Address>
            <AddressLine Id='1'>XYZ road</AddressLine>
            <AddressLine Id='2'>MiceTown</AddressLine>
        </Address>
    </Employee>
    <Employee Id='2'>
        <Name>Mark</Name>
        <Address>
            <AddressLine Id='1'>123 street</AddressLine>
            <AddressLine Id='2'>TigerCity</AddressLine>
        </Address>
    </Employee>
</Employees>
```
I need to have 1+ AddressLine for each employee

I modified POCO as follow

```
    public partial class EmployeeRec
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public AddressRec Address { get; set; }
    }

    public partial class AddressRec
    {
        public AddressLineRec[] AddressLines { get; set; }
    }
    
    public partial class AddressLineRec
    {
        public int Id { get; set; }
        public string AddressLine { get; set; }
    }

```

But when I read the XML, AddressLines Array is always empty
I Tried to specify [ChoXmlNodeRecordField(XPath=...] on my POCO fields, but with no success

I think I miss something important here :(

I saw the answer to Issue#14, but I hope I can have something less "dynamic"

any suggestion will be appreciated!

TIA 

stefano

p.s. I attach full example
[Program.cs.txt](https://github.com/Cinchoo/ChoETL/files/2695532/Program.cs.txt)

**Comment by Cinchoo** [comment]
You POCO object structure must be defined as below to deserialize your xml successfully.


    public class EmployeeRec1
    {
        [ChoXmlNodeRecordField(XPath = "@Id")]
        public int Id { get; set; }
        [ChoXmlNodeRecordField(XPath = "Name")]
        public string Name { get; set; }
        [ChoXmlNodeRecordField(XPath = "/Address/*")]
        public AddressLineRec[] Address { get; set; }
    }
    public partial class AddressLineRec
    {
        [XmlAttribute(AttributeName = "Id")]
        public int Id { get; set; }
        [XmlText]
        public string AddressLine { get; set; }
    }

Hope it helps.

**Comment by code2learnit** [comment]
Thanks!! It works :)

I see you completly by-pass the AddressRec class, since it contains only an array of AddressLine.
But what happens if I have a more "complex" situation where there are AddressRec contains more fields (possibly other arrays) or even AddressLineRec contains other fields or array of fields

Is there any way or reason to include back AddressRec?

I tried to modify your sample to manage the following xml

```
<Employees>
    <Employee Id='1'>
        <Name>Tom</Name>
        <Address>
            <AddressLine Id='1'>XYZ road</AddressLine>
            <AddressLine Id='2'>MiceTown</AddressLine>
            <Country>United States</Country>
        </Address>
    </Employee>
    <Employee Id='2'>
        <Name>Mark</Name>
        <Address>
            <AddressLine Id='1'>123 street</AddressLine>
            <AddressLine Id='2'>TigerCity</AddressLine>
            <Country>Italy</Country>
        </Address>
    </Employee>
</Employees>
```

I understand that I can flat in some way the struct introducing a Country field in EmployeeRec

```
    public class EmployeeRec
    {
        [ChoXmlNodeRecordField(XPath = "@Id")]
        public int Id { get; set; }
        [ChoXmlNodeRecordField(XPath = "Name")]
        public string Name { get; set; }
        [ChoXmlNodeRecordField(XPath = "Address/AddressLine")] 
        public AddressLineRec[] Address { get; set; }
        [ChoXmlNodeRecordField(XPath = "Address/Country")]
        public string Country { get; set; }
    }
```

But was not able to put Country and AddressLines in a distinct class :(

sorry for "abusing" of your knowledge and patience

TIA
stefano

**Comment by Cinchoo** [comment]
In that case, you can use the original object structure with few tweaks as below 


    public class EmployeeRec1
    {
        [ChoXmlNodeRecordField(XPath = "@Id")]
        public int Id { get; set; }
        [ChoXmlNodeRecordField(XPath = "Name")]
        public string Name { get; set; }
        [ChoXmlNodeRecordField(XPath = "/Address")]
        public AddressRec Address { get; set; }
    }

    public partial class AddressRec
    {
        [XmlElement(ElementName = "AddressLine")]
        public AddressLineRec[] AddressLines { get; set; }
        [XmlElement(ElementName = "Country")]
        public string Country { get; set; }
    }

    public partial class AddressLineRec
    {
        [XmlAttribute(AttributeName = "Id")]
        public int Id { get; set; }
        [XmlText]
        public string AddressLine { get; set; }
    }

**Comment by code2learnit** [comment]
Great! Thank you very much!!

I was trying to use ChoXmlNodeRecordField in the AddressRec class, and it did not work :(
