### ISSUE TITLE
ChoParquetWriter : Error while creating parquet file

### ISSUE THREAD

**Issue by stephane3434** [Cinchoo/ChoETL#261]
PC : net framework 4.8 / windows 11

When I try to test the parquet file creation I always get an error message.

I tested about ten versions of ChoETL / ChoETL.Parquet, 

I can't create a file, I always have the same error

My Code : 

```
  List<EmployeeRecSimple> objs = new List<EmployeeRecSimple>();

            dynamic rec1 = new EmployeeRecSimple();
            rec1.Id = 1;
            rec1.Name = "Mark";
            objs.Add(rec1);

            dynamic rec2 = new EmployeeRecSimple();
            rec2.Id = 2;
            rec2.Name = "Jason";
            objs.Add(rec2);

 using (var parser = new ChoParquetWriter("emp3.parquet"))
//using (var parser = new ChoParquetWriter<EmployeeRecSimple>("emp.parquet",config))
{
                    parser.Write(objs);
} <= error
```

**System.MissingMethodException :  Method not found 
'Void Parquet.ParquetRowGroupWriter.WriteColumn(Parquet.Data.DataColumn)'.'**

I don't understand, I also tried with a datatable and I get the same error

```
   DataTable db = new DataTable();
            db.Columns.Add("id", typeof(int));
            db.Columns.Add("name", typeof(string));

            var row = db.NewRow();
            row["id"] = 1;
            row["name"] = "john";

            // ajoute une ligne 
            db.Rows.Add(row);
            try
            {
                using (var parser = new ChoParquetWriter("emp2.parquet"))              
                {
                    parser.Write(db);
                }
            }
            catch (Exception ex)
            { 
                Console.WriteLine(ex.ToString()); 
            }
```

Thanks for your help

**Comment by Cinchoo** [comment]
Based on the error reported, looks like your project references inconsistent Cinchoo libraries. Couple of ways to resolve them

1. Create a fresh .net 4.8 project.
2. Install Cinchoo parquet library (using ChoETL.Parquet) - which will pull all the required binaries
3. Goto the application references, you will see ChoETL.Core (v1.2.1.50), ChoETL.Parquet (1.0.1.24). These are the latest.

Give it try and let me know.

**Comment by stephane3434** [comment]
Hello,

Thanks for the help.

In a new wpf net6 project it works fine

In the old winform 4.8 project I still have the same error.

This seems to come from the parquet.net assembly.
during installation version 3.7 is installed

In this case there is a version error

I installed version 4.0 to 4.1.3 and there I have the error from the beginning of my message. I don't understand what is blocking

I tested on a project in net framework 4.7.2 same problem

after several attempts: remove then put back the packages, restart Visual studio it works.

summarize :
wpf net 6 => directly Ok
winform net framework 4.8 or 4.7.2 it works but you have to force it a bit... I haven't found what was blocking it yet

Beautiful day
