### ISSUE TITLE
Memory leak/Memory consumption goes 100% in case of large data

### ISSUE THREAD

**Issue by sanketakulkarni** [Cinchoo/ChoETL#262]
We are using this package and it works fine. 
But in case data is very huge like 5000000 or 5M and we are using reader but still memory usage goes to 100%
We are expecting as we are using the reader it should not pull and keep all data in memory..
Below is a sample code.. One note is it is connecting and reading data from Oracle 

 ` using (OracleDataReader rdr = cmd.ExecuteReader())
                        {
                           
                            using (var parser = new ChoParquetWriter(filePathWithFileName, new ChoParquetRecordConfiguration() 
                            {  AutoFlush = true, BufferSize = 1024 }))
                            {
                                ChoParquetRecordConfiguration config = new ChoParquetRecordConfiguration();

                                parser.Write(rdr);
                                }
                            
                        }                        `            
Any help on this is really helpful. Thanks in advance

**Comment by Cinchoo** [comment]
Set `RowGroupSize` to smaller value in the configuration, default is 5000.

try and let me know.

**Comment by sanketakulkarni** [comment]
Thanks it worked after setting it to a smaller value
