### ISSUE TITLE
NestedColumnSeparator causing Runtime Binder Exception.

### ISSUE THREAD

**Issue by ankitsinha1504** [Cinchoo/ChoETL#264]
This is the code snippet that is provided in the documentation.

>string csv = @"Id,name,nestedobject/id,nestedarray/0/name, nestedarray/0/city, nestedarray/1/name, nestedarray/200/city
1,name,2,namelist10, citylist10,namelist11, citylist11
2,name1,3,namelist20, citylist20,namelist21, citylist21";

>StringBuilder json = new StringBuilder(); 
>using (var w = new ChoJSONWriter(json))
>{
>    using (var r = ChoCSVReader.LoadText(csv).WithFirstLineHeader()
>        .Configure(c => c.NestedColumnSeparator = '/')
>        )
>        w.Write(r);
>Console.WriteLine(json.ToString());

But it is throwing the following exception ->
`Exception Type: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
TargetSite: System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Char, System.Nullable\``1[System.Char], System.Object, Boolean)
Message: Cannot perform runtime binding on a null reference
`

**Comment by Cinchoo** [comment]
yes, u got it. release new version (v1.2.1.51). take it and let me know.

https://www.nuget.org/packages/ChoETL.NETStandard/1.2.1.51
https://www.nuget.org/packages/ChoETL.JSON.NETStandard/1.2.1.51

**Comment by ankitsinha1504** [comment]
Installed both ChoETL.NETStandard v1.2.1.51 and ChoETL.JSON.NETStandard v1.2.1.51
But Getting the same error.

**Comment by ankitsinha1504** [comment]
Just checked correctly. Its working fine now. Thanks!
