### ISSUE TITLE
Column Missing in CSV throws error when in DTO

### ISSUE THREAD

**Issue by bakes82** [Cinchoo/ChoETL#268]
@Cinchoo Is it suppose to throw a missing col error if the csv doesnt have a col?  EX: On the fiddler example if you add another string "Test" but dont have it in the CSV it errors with missing field.
	
```C#
		[ChoCSVRecordField(FieldName = "Test")]
		public string Test { get; set; }
```

**Comment by Cinchoo** [comment]
yes, if you want to ignore, parse the file, use `.Configure(c => c.ThrowAndStopOnMissingField = false)`
