### ISSUE TITLE
XML reader and namespaces

### ISSUE THREAD

**Issue by code2learnit** [Cinchoo/ChoETL#27]
Hi

I'm trying to read an xml file whose root element is 

`<SyncInvoice xmlns="http://schema.infor.com/InforOAGIS/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SyncInvoice.xsd" languageCode="IT">`

using the following

```
using (var parser = new ChoXmlReader<SyncInvoice>(@"invoice.xml")
               .WithXPath("SyncInvoice")
          )
```
where SyncInvoice is my topmost POCO

I cannot read the XML file unless I modify the root element to 

`<SyncInvoice languageCode="IT">`

I tried using WithXmlNamespace(), but with no success.

Could you help me?

thanks
stefano

**Comment by Cinchoo** [comment]
Please post the SyncInvoice class definition and sample code as well.

FYI, I'm not able to reproduce it.

**Comment by Cinchoo** [comment]
I got it. When you define xml namespace using `WithXmlNamespace`, pass prefix. Then use the prefix in xpath on class members

Here is the working sample

```
    public class SyncInvoice
    {
        [ChoXmlNodeRecordField(XPath = "@languageCode")]
        public string LanguageCode { get; set; }
        [ChoXmlNodeRecordField(XPath = "/x:ApplicationArea")]
        public ApplicationArea ApplicationArea { get; set; }

    }

            // SyncInvoice.ApplicationArea is null
            using (var parser = ChoXmlReader<SyncInvoice>.LoadText(xml).WithXPath("SyncInvoice")
                .WithXmlNamespace("x", "http://schema.infor.com/InforOAGIS/2")
                )
            {
                foreach (dynamic rec in parser)
                {
                    Console.WriteLine(ChoUtility.Dump(rec));
                }
            }

```

**Comment by code2learnit** [comment]
It works!

you rock  🥇 🥇🥇
