### ISSUE TITLE
Cannot see some libraries

### ISSUE THREAD

**Issue by keith-bartley** [Cinchoo/ChoETL#273]
Just a simple question but why can't I see the ChoJSONWriter type loaded here?

![image](https://user-images.githubusercontent.com/102529181/219446631-7e537c4c-ca17-4485-b509-fc49f25f208c.png)

**Comment by Cinchoo** [comment]
you need to download JSON plug-ins ([ChoETL.JSON](https://www.nuget.org/packages/ChoETL.JSON) / [ChoETL.JSON.NETStandard](https://www.nuget.org/packages/ChoETL.JSON.NETStandard))

visit here to download
https://www.nuget.org/packages?q=choetl

**Comment by keith-bartley** [comment]
Thanks very much.
