### ISSUE TITLE
Change Delimiter when Converting to CSV

### ISSUE THREAD

**Issue by kleedtke** [Cinchoo/ChoETL#290]
Is there a way I can change the default comma delimiter to something else when converting from JSON to CSV?

**Comment by Cinchoo** [comment]
Hope this link helps

https://www.codeproject.com/Articles/1145337/Cinchoo-ETL-CSV-Reader#21.1WithDelimiter66

**Comment by kleedtke** [comment]
Will this achieve the same result when using the CSV writer?

**Comment by Cinchoo** [comment]
Yes.
