### ISSUE TITLE
New Parquet.Net default encoding DELTA_BINARY_PACKED is causing issues with Spark

### ISSUE THREAD

**Issue by jsn-m** [Cinchoo/ChoETL#299]
As reported in the Parquet.Net [Repo](https://github.com/aloneguid/parquet-dotnet/issues/392), the new DELTA_BINARY_PACKED encoding in Parquet.Net does not play well with Spark 3.3.
Please expose the Parquet.Net UseDeltaBinaryPackedEncoding flag in ParquetOptions for setting.

https://aloneguid.github.io/parquet-dotnet/encodings.html#numbers

**Comment by Cinchoo** [comment]
All parquet options can be controlled as below

```
            using (var r = new ChoParquetReader(@"test1.parquet")
                .ParquetOptions(o => o.UseDeltaBinaryPackedEncoding = true))
            {

            }
```

**Comment by jsn-m** [comment]
I can't use LINQ because my ChoParquetWriter is declared dynamic because I needed to access the WithField method.
```C#
var genericParquetWriter = typeof(ChoParquetWriter<>).MakeGenericType(dtoType);
dynamic writerInstance = ChoActivator.CreateInstance(genericParquetWriter, new object[] { localPath, });
var dtoProperties = dtoType.GetAllProperties();

writerInstance.WithField(name: "SomeName", fieldType: typeof(string));
```

**Comment by jsn-m** [comment]
Figured it out:

```C#
var setParquetOptions = new Action<ParquetOptions>(s => s.UseDeltaBinaryPackedEncoding = false);
writerInstance.ParquetOptions(setParquetOptions);
```
