### ISSUE TITLE
import CSV - loading CSV file with header sample not working

### ISSUE THREAD

**Issue by leenvanpeltSELAS** [Cinchoo/ChoETL#305]
Hello,
example 13.2 " Loading CSV file with header sample" from the documentation on page https://www.codeproject.com/Articles/1145337/Cinchoo-ETL-CSV-Reader

gives output:
Id:
Name:
Id:
Name:
Id:
Name:

so the automatic header discovery doesn't seem to work. Is this a bug, or is the documentation out-of-date?
I'm using ChoETL package version 1.2.1.64.
greetings,
Leen

**Comment by Cinchoo** [comment]
here is the working sample for your reference

https://dotnetfiddle.net/Qlm3GF

**Comment by leenvanpeltSELAS** [comment]
The code from the fiddle also doesn't work. but if found out why: my Windows setting for list separator is ;
Changed the input and it works fine.
