### ISSUE TITLE
Old Code Upgrade - Pipe Delimiter - Double Quotes Now Breaking Code

### ISSUE THREAD

**Issue by jeffreywstevens** [Cinchoo/ChoETL#319]
The old code was more forgiving.

I am converting tab-delimited to pipe delimited.

Old code had no problem with this in data.  After converted from tab delimited to pipe delimited this was in file:
|"Kazinski, Virginia """"Jen"|

New code (upgraded to current Cho) outputed this.
|Kazinski, Virginia Jen"|

Old code then ran just fine with all processing, no errors with parsing, etc.

New upgraded .NET 8 code had many errors. I had to add the following everywhere to keep processing.
.ThrowAndStopOnMissingField(false)

This may have masked a bigger problem.

It seems now, the remaining single-quote, is causing the entire record to parse as all null values for all the columns.
|Kazinski, Virginia Jen"|
I had to add code to capture the exception. However, this records is getting skipped and the data is missing from the new files.

Is there a way to fix this without having to strip out all of the double-quotes? Years ago I went pipe to eliminate that problem.

**Comment by jeffreywstevens** [comment]
The old code seems to have run fine for 4 years. 
Anyway, I added code to remove all of the double quotes in the files. I feel I can deal with any complaints.

After that, only one case of adding .ThrowAndStopOnMissingField(false) when converting from Tab to Pipe.  I did have one case of a spurious blank record after the header which was fixed with an all column null check.

**Comment by Cinchoo** [comment]
hi, can u pls post sample csv data file, along with expected result? (Use dotnet fiddle if u can) Let me take a look.

**Comment by jeffreywstevens** [comment]
Unfortunately I can't share. 

However, after a few of my fixes, the totals line up between the old and the new and the data looks good. 

The major differences via comparisons are the lack of quotes now and it seems there were a few trailing nulls in a particular file. Its a file I am preparing to work on that has some data merges and dup elimination.

I don't want to go back at this point.

**Comment by jeffreywstevens** [comment]
By the way, I fixed this with: MayHaveQuotedFields on the reader.  I didn't know this existed but it fixed the quotes and the output records look fantastic. Much better than the original code.

I still got some difference in the reader in the new version. For instance, records with all nulls.  I just inspect and eliminate them. Looking good. Your library works great for me.
