### ISSUE TITLE
Issue Converting JSON to CSV File

### ISSUE THREAD

**Issue by Karthigeyan14** [Cinchoo/ChoETL#324]
Actually, I'm facing an issue while converting JSON to a CSV file. I deserialized it with a dynamic object, but the problem is that the headers are generated based on the first set of data. If the next set of data differs from the first, any missing data is not included in the CSV file. Do you have any suggestions...?

**Comment by Cinchoo** [comment]
use `WithMaxScanRows` on csv writer

```
            StringBuilder csv = new StringBuilder();
            using (var r = new ChoJSONReader(FileNameSample33JSON)
                .WithJSONPath("$..getUsers[*]", true)
                )
            {
                using (var w = new ChoCSVWriter(csv)
                    .WithFirstLineHeader()
                    .WithMaxScanRows(10)
                    .Configure(c => c.ThrowAndStopOnMissingField = false)
                    )
                    w.Write(r);
            }
```

**Comment by Karthigeyan14** [comment]
Thank you so much for your response. I need to convert a CSV string builder to a CSV file, but I encountered an error stating "Complex JSON path not supported." Could you please help me with how to convert it to a CSV file? Thank you in advance!

**Comment by Karthigeyan14** [comment]
Thank you for your response! It's working. 👍

**Comment by Karthigeyan14** [comment]
I have another issue. The field looks like this:

**json**

"extension": [
  {
    "Test": "value",
    "value": [
      "0",
      "1",
      "2"
    ]
  },
  {
    "Test1": "Test",
    "value": "20"
  },
  {
    "Test2": "Test",
    "value": "35"
  }
]
The values 20 and 35 are missing because in the first object, the value field is a list, while in the subsequent objects, value is not a list. This inconsistency causes the values to be overlooked.

**Comment by Cinchoo** [comment]
duplicate #325

**Comment by Karthigeyan14** [comment]
> @Cinchoo I have another issue. The field looks like this:
> 
> **json**
> 
> "extension": [ { "Test": "value", "value": [ "0", "1", "2" ] }, { "Test1": "Test", "value": "20" }, { "Test2": "Test", "value": "35" } ] The values 20 and 35 are missing because in the first object, the value field is a list, while in the subsequent objects, value is not a list. This inconsistency causes the values to be overlooked.

so how to fix this ..?
