### ISSUE TITLE
Unable to load shared library 'kernel32.dll' or one of its dependencies exception on MacOS.

### ISSUE THREAD

**Issue by alexey-belous** [Cinchoo/ChoETL#34]
I've found an issue that the library doesn't works on MacOS. It fails during initialization with following exception:
```
Exception Type: System.DllNotFoundException
Message: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting t
he DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32.dll, 1): image not found
TypeName:
Data: System.Collections.ListDictionaryInternal
TargetSite: Boolean SetConsoleCtrlHandler(ChoETL.ConsoleCtrlMessageHandler, Boolean)
HelpLink: NULL
Source: ChoETL.Core
HResult: -2146233052

StackTrace Information
*********************************************
   at ChoETL.ChoETLFramework.SetConsoleCtrlHandler(ConsoleCtrlMessageHandler consoleCtrlRoutine, Boolean Add)
   at ChoETL.ChoETLFramework.RegisterConsoleControlHandler()
   at ChoETL.ChoETLFramework._Initialize()
```

It seems that the problem is in the following lines that tries to import function from kernel.dll without check if the platform NETSTANDARD2_0 or no: https://github.com/Cinchoo/ChoETL/blob/1efa637746f91a1155e3f28fb1a2bd39fb010fbc/src/ChoETL/ETLCommon/ChoETLFramework.cs#L197-L198

**Comment by Cinchoo** [comment]
Thanks for reporting. I've put a fix and committed the changes. Please take the latest and let me know.

**Comment by Cinchoo** [comment]
Please close it if all looking good. Thx

**Comment by alexey-belous** [comment]
@Cinchoo, new version works fine on macOS, thanks for your help =)
