### ISSUE TITLE
I have Question! : CSVReader

### ISSUE THREAD

**Issue by swlee7811** [Cinchoo/ChoETL#36]
Hi, i got a problem! Help me plz. 

this is my code.
------
            //...
            var csvReader = new ChoCSVReader(CSVfilepath).WithFirstLineHeader(true);
            foreach (dynamic e in csvReader)
            {
                foreach (var value in e.Values)
                {
                       //...
                }
            }
-------
1. 100 fields CSV file : read Success (in 10 seconds).
2. 8000 fields CSV file : Error Occured.
Error Line : var csvReader = new ChoCSVReader(CSVfilepath).WithFirstLineHeader(true);

i want read CSV file (maybe 8000 fields, 1200 records) by high performancely.
How many field can read using CSVReader?

**Comment by Cinchoo** [comment]
No limit.

What are the issues you are running into? Please post exception with stack trace if possible to help.

**Comment by Cinchoo** [comment]
Looks like one of the field header is empty. Pls check the csv file header and correct it.

Or you can simply ignore the header by passing ‘false’ to ‘WithFirstLineHeader()’ method.

**Comment by swlee7811** [comment]
thanks, I fixed csv file and It worked well.
but, It takes a long time to Load CSV file and get Count. About 3 minuites.
I need a way to handle it fast, in 10 seconds

I tested 8400 fields, 2 records.
program is stopped when tested 1200 records.

**Comment by Cinchoo** [comment]
On the performance issue, can u post sample code with sample csv file? Appreciate it.

**Comment by swlee7811** [comment]
### **Sample code(Load & Read)**
```
            var csvReader = new ChoCSVReader(startFile)
                .Configure(c => c.IgnoreDuplicateFields = true)
                .Configure(c => c.Delimiter = ",")
                .Configure(c => c.IgnoreEmptyLine = true)
                .Configure(c => c.HasExcelSeparator = false);

            while (true)
            {
                DateTime begin_ = DateTime.Now;
                var read = csvReader.Read();
                DateTime end_ = DateTime.Now;

                Console.WriteLine("begin : " + begin_.ToString("hh:mm:ss.fff"));
                Console.WriteLine("end : " + end_.ToString("hh:mm:ss.fff"));
                Console.ReadKey();
            }
```

![image](https://user-images.githubusercontent.com/46707532/52105703-0d4f5000-2633-11e9-98ac-6691e7ad4145.png)


[ETLsampletest.zip](https://github.com/Cinchoo/ChoETL/files/2820283/ETLsampletest.zip)

**Comment by Cinchoo** [comment]
Thanks for the samples. It helped. Found the issue, put a fix. Take the new version 1.0.9.4 from nuget. Now it takes to load these 2 rows in 5secs. Let me know.

**Comment by swlee7811** [comment]
Thanks a lot!
