### ISSUE TITLE
ChoCSVReader - POCO with Nullable Types

### ISSUE THREAD

**Issue by oh-yeah** [Cinchoo/ChoETL#37]
I'm having difficulty configuring the ChoCSVReader to honor nullable types of a POCO.  Anytime the reader finds an empty cell, it puts a default values in.  Any idea on how I can configure the reader to parse a null value for the code below?  

**Reader**
```
using (var reader = new ChoCSVReader<GiveOptionalValuesSomeLove>("Path goes here!").WithDelimiter("\t").WithFirstLineHeader())
{
    return reader.AsEnumerable();
}
```

**POCO**
```
public class GiveOptionalValuesSomeLove
{
    public string SomeValue { get; set; } //<- will be an empty string instead of null
    public int? SomeOptionalValue { get; set; } //<- will be zero if blank on the csv
}
```

Currently using version: 1.0.8.7

**Comment by Cinchoo** [comment]
You have to tell the parser what is the null value token is. Sample shows how to treat empty string as null 

using (var reader = new ChoCSVReader<GiveOptionalValuesSomeLove>("Path goes here!").WithDelimiter("\t").WithFirstLineHeader()
.Configure(c => c.NullValue = “”))
{
    return reader.AsEnumerable();
}

**Comment by oh-yeah** [comment]
Perfect, thanks Cho!

**Comment by oh-yeah** [comment]
I spoke a little too soon.  Although the configuration change fixed my immediate issue, I've found that exporting to a datatable table doesn't keep null values for integers.  Based on the reader below, the SomeOptionalValue field will honor the configuration for strongly typed objects but will ignore the it when exporting to a datatable.

**Reader**
```
DataTable table;
IEnumerable<GiveOptionalValuesSomeLove> values;

using (var reader = new ChoCSVReader<GiveOptionalValuesSomeLove>(filePath).WithDelimiter("\t").WithFirstLineHeader().Configure(c => c.NullValue = String.Empty))
{
     table = reader.AsDataTable();
     values = reader.ToList<T>();
}
```

**Comment by oh-yeah** [comment]
Similar to issue #38?

**Comment by Cinchoo** [comment]
Put a fix, pushed new version 1.0.9.1 to nuget. try it.

**Comment by oh-yeah** [comment]
Thanks for the quick response.  Unfortunately, I'm getting the same behavior with the AsDataTable() method using the new version.  Integer values that are null in my POCO are still being converted to 0 in the datatable.

**Comment by oh-yeah** [comment]
Will do, once again thanks for the quick response!

**Comment by oh-yeah** [comment]
Version 1.0.9.3 fixed this issue, closed.
