### ISSUE TITLE
Parser results shows wrong data type - sample attached

### ISSUE THREAD

**Issue by papyr** [Cinchoo/ChoETL#39]
When I parse the file with

Hello, I am parsing this [sample CSV](https://file.town/download/diojcwwauyxnacc4sq5jeqb75) file with this code.

The problem:
The Header `"ProblemHeader"`/ 3rd col, is parsed as wrong data type with the code below, `true `or `false`, while it should be parsed as int!

            using (var r = new ChoCSVReader(csvIn)
                .WithFirstLineHeader()
                .WithMaxScanRows(10)
                )
            {
                foreach (IDictionary<string, object> rec in r.Take(1))
                {
                    foreach (var kvp in rec)
                        Console.WriteLine($"{kvp.Key} - {r.Configuration[kvp.Key].FieldType}");
                }
            }

**Comment by Cinchoo** [comment]
I'm not able to reproduce it. Am I missing something?

```
shftdte - System.DateTime
shft - System.String
ProblemHeader - System.Int64
prodcde - System.String
partcde - System.String
fgprodcde - System.String
proddesc - System.String
minthrpt - System.Int64
chrgs - System.Int64
qtypk - System.Int64
hrcyc01 - System.Int64
hrcyc02 - System.Int64
hrcyc03 - System.Int64
hrcyc04 - System.Int64
hrcyc05 - System.Int64
hrcyc06 - System.Boolean
hrcyc07 - System.Int64
hrcyc08 - System.Int64
hrcyc09 - System.Int64
hrcyc10 - System.Int64
hrcyc11 - System.Boolean
hrcyc12 - System.Int64
hrcyc13 - System.Int64
scrpqty - System.Int64
repqty - System.Int64
schhrs - System.Int64
acthrs - System.Double
prssgrp - System.String
chrgwgtcnt - System.Int64
chrgwgtcnt2 - System.Int64
bgtchrgwgts - System.Int64
actchrgwgts - System.Double
partcnt - System.Int64
erndhrs - System.Double
```

**Comment by papyr** [comment]
Thats strange, I am getting bool always on `ProblemHeader`, and it splits the header name when there is a 0 in the header as well, like hrcyc09 -> `hrcyc 09`

I increased scan depth to 20 rows, still same result. Should I build from source, please let me know where to set the break points and which variables to look at, I will include that in the debug info report here..

Could you share some suggestions
When using scanrows, how to safely peek ahead i.e. that it does not surpass the row depth for e.g. if a file only has 20 rows, but we have scan rows set at 20, will it crash. How to handle this.

**Comment by papyr** [comment]
unresolved still closing!
