### ISSUE TITLE
ChoETL Does not Appear Compatible with .NET Core Version 1.1

### ISSUE THREAD

**Issue by johnknelson** [Cinchoo/ChoETL#4]
Looking forward to trying ChoETL out to handle some JSON/CSV massaging, but am having trouble installing the package in my project. It looks like maybe the package is not compatible with the newest .NET Core or .NET framework I am using. Any chance that this is an error on my part? Or is this just not supported yet and ought to be a feature request?

I am targeting the .NETCoreApp 1.1 framework with my project. The out put of the installation command is below:

```
PM> Install-Package ChoETL
Restoring packages for C:\Users\jnelso07\Documents\Visual Studio 2017\Projects\JupyterWebService\JupyterWebService\JupyterWebService.csproj...
Install-Package : Package ChoETL 1.0.3.7 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package ChoETL 1.0.3.7 supports: net (.NETF
ramework,Version=v0.0)
At line:1 char:16
+ Install-Package <<<<  ChoETL
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:16
+ Install-Package <<<<  ChoETL
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'JupyterWebService'.
At line:1 char:16
+ Install-Package <<<<  ChoETL
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.7027199
```

Thanks for any assistance!

**Comment by Cinchoo** [comment]
ChoETL is not supported for .net core yet.

**Comment by johnknelson** [comment]
Gothca! Thanks for the confirmation.

**Comment by johnknelson** [comment]
Should I go ahead and close this or leave it open for future support?

**Comment by Cinchoo** [comment]
You can close it.

**Comment by os1r1s110** [comment]
Is there any plan to make it compatible with .net core?

**Comment by Cinchoo** [comment]
Ported code to .NET standard, published to Nuget. 

Package Id: ChoETL.NETStandard

Now you can use this library all version of .NET framework / any environment.

Let me know.

**Comment by bbakermmc** [comment]
@Cinchoo Are you going to maintain your .net standard versions?  They are behind.

**Comment by bbakermmc** [comment]
@Cinchoo NM, can you make the version numbers the same as the base packages, very confusing, thought they were behind.
