### ISSUE TITLE
CSVReader: Backslash should not escape double quote

### ISSUE THREAD

**Issue by renkin777** [Cinchoo/ChoETL#40]
Currently, backslash escapes the following double quote, but it should not. For example, if I have the file like this (tab delimited):
"Field1"	"Field2"
"Line 1 Field 1\"	"Line 1 Field 2"
"Line 2 Field 1"	"Line 2 Field 2"

the reader for the second line should return:
reader[0] = "Line 1 Field 1\\"
reader[1] = "Line 1 Field 2\\"
but it returns:
reader[0] = "Line 1 Field 1\\"
reader[1] = "Line 1 Field 2\"\r\n\"Line 2 Field 1".

As I recall, in order to escape the double quote character the second double quote should be used and the backslash.

**Comment by Cinchoo** [comment]
Can u please provide me sample code with test data? 

I'm not seeing backslash in the sample data. Am I missing something?

**Comment by renkin777** [comment]
Hello,
Thank you for the quick reply, you are right when copy-pasted I lost the backslash. 
I attached the sample file to this message.
[SampleColumnWithBackslashFile.txt](https://github.com/Cinchoo/ChoETL/files/2928504/SampleColumnWithBackslashFile.txt)

**Comment by renkin777** [comment]
Also if I modify the file and change "Field 1\" to be "Field 1\\" (trying to escape the backslash with another backslash), the reader now returns "Field 1\\\\" value.

**Comment by Cinchoo** [comment]
Found the issue, fixed it. Please take the latest package 1.0.9.7 and give it a try. Thanks for reporting.

**Comment by renkin777** [comment]
Hello,
Thank you for the quick fix, but unfortunately, I cannot verify it as the sample app throws ChoMissingRecordFieldException with the following message: "Missing 'Field2' field in CSV file."

**Comment by Cinchoo** [comment]
You will have to `ThrowAndStopOnMissingField` to false to suppress this error rmsg.

                .Configure(c => c.ThrowAndStopOnMissingField = false)

**Comment by renkin777** [comment]
I added this option and still get the field values corrupted. Now I see in the output:
Line 1 Field 1: Line 1 Field 1" Line 1 Field 2
Line 2 Field 1  Line 2 Field 2"
-------------------------------------------------------
Line 1 Field 2:


but it should be:
Line 1 Field 1: Line 1 Field 1
-------------------------------------------------------
Line 1 Field 2: Line 1 Field 2
Line 2 Field 1: Line 2 Field 1
-------------------------------------------------------
Line 2 Field 2: Line 2 Field 2


I am using the same sample project I attached earlier, I just changed the configuration to be:
.Configure(x =>
                        {
                            x.MaxScanRows = 0;
                            x.MayContainEOLInData = true;
                            x.IgnoreEmptyLine = true;
                            x.ThrowAndStopOnMissingField = false;
                        })

**Comment by renkin777** [comment]
I added this option and still get the field values corrupted. Now I see in the output:
Line 1 Field 1: Line 1 Field 1" Line 1 Field 2
Line 2 Field 1  Line 2 Field 2"
-------------------------------------------------------
Line 1 Field 2:


but it should be:
Line 1 Field 1: Line 1 Field 1
-------------------------------------------------------
Line 1 Field 2: Line 1 Field 2
Line 2 Field 1: Line 2 Field 1
-------------------------------------------------------
Line 2 Field 2: Line 2 Field 2


I am using the same sample project I attached earlier, I just changed the configuration to be:
.Configure(x =>
                        {
                            x.MaxScanRows = 0;
                            x.MayContainEOLInData = true;
                            x.IgnoreEmptyLine = true;
                            x.ThrowAndStopOnMissingField = false;
                        })

**Comment by Cinchoo** [comment]
Please remove `MayContainEOLInData = true`, unless it is necessary. 

Based on your data file

Line 1: 

"Line 1 Field 1\\"	"Line 1 Field 2"

Since the line starts with quote, parser reads until it finds end quote followed by separator / EOL. 
In this case, whole line will be treated as first field value.

Here is the output from your sample:
```

Line 1 Field 1: Line 1 Field 1" Line 1 Field 2"
-------------------------------------------------------
Line 1 Field 2:
Line 2 Field 1: Line 2 Field 1
-------------------------------------------------------
Line 2 Field 2: Line 2 Field 2
```

**Comment by renkin777** [comment]
Unfortunately, I cannot remove this setting as I may have a multiline content in a field. Why do you use the backslash to escape the double quote? Usually, in this case, a second double quote is used.

**Comment by Cinchoo** [comment]
Well, haven't thought about it. Good point. Let me get it fixed to handle both cases.

**Comment by Cinchoo** [comment]
Put a fix, pushed to Git. Take the code and try it. 

Will be pushing nuget tonight.

**Comment by Cinchoo** [comment]
version 1.0.9.8 is pushed to Nuget. Try it and let me know. Thanks for reporting

**Comment by renkin777** [comment]
Hello,
I finally was able to test the new version and found another issue: if the file has an empty field ("") the rest of the file will be broken.
I attached a slightly modified sample project. In the output I expected to get the following results:
Line 1 Field 1: Line 1 Field 1\
-------------------------------------------------------
Line 1 Field 2: 
-------------------------------------------------------
Line 1 Field 3: Line 1 Field 3
-------------------------------------------------------
Line 2 Field 1: Line 2 Field 1
-------------------------------------------------------
Line 2 Field 2: 
-------------------------------------------------------
Line 2 Field 3: Line 2 Field 3
-------------------------------------------------------
Rows: 3


but I got the following:

Line 1 Field 1: Line 1 Field 1\
-------------------------------------------------------
Line 1 Field 2: "
-------------------------------------------------------
Line 1 Field 3: Line 1 Field 3
Line 2 Field 1
-------------------------------------------------------
Rows: 2


Thank you
[CsvReaderTest.zip](https://github.com/Cinchoo/ChoETL/files/2942059/CsvReaderTest.zip)

**Comment by Cinchoo** [comment]
Parser treating the 2 double quotes as 1 double quote as default QuoteEscapeChar is double quote. Let me default that to nothing unless explicitly set.

In the mean time, please set `x.QuoteEscapeChar = '\0'` to fix this issue.

**Comment by renkin777** [comment]
Setting QuoteEscapeChar to '\0' helps with the empty field, but now an escaped quote is ignored by the reader. For example, if you change "Line 1 Field 3" in the file to be "Line 1 "" Field 3" the reader will return "Line 1  Field 3" but it should return "Line 1 " Field 3".

**Comment by Cinchoo** [comment]
Have put a fix for last issue. Please take the new nuget package and try it.

**Comment by renkin777** [comment]
Hello,
Now I see another issue:
if I have a sample file without any backslashes and multiple double quotes like the attached file
[SampleFile.txt](https://github.com/Cinchoo/ChoETL/files/2988730/SampleFile.txt), the output will look like this one 
[invalid_output.txt](https://github.com/Cinchoo/ChoETL/files/2988752/invalid_output.txt) but it should look like this 
[valid_output.txt](https://github.com/Cinchoo/ChoETL/files/2988753/valid_output.txt)

**Comment by Cinchoo** [comment]
Not able to reproduce it. I'm seeing expected output from your sample file.

```
            using (var reader = new ChoCSVReader<dynamic>("QuoteEscape.csv")
                .WithDelimiter("\t")
                .WithFirstLineHeader()
                .Configure(x =>
                {
                    x.QuoteEscapeChar = '\0';
                    x.MaxScanRows = 0;
                    x.IgnoreEmptyLine = true;
                    x.ThrowAndStopOnMissingField = false;
                }))
            {
                var dataReader = reader.AsDataReader();

                while (dataReader.Read())
                {
                    Console.WriteLine($"{dataReader[0]}, {dataReader[1]}, {dataReader[2]}");
                }
            }
```


Output:

```
Line 1 Field 1, , Line 1 Field 3
Line 2 Field 1, , Line 2 Field 3
Line 3 Field 1, , Line 3 Field 3
Line 4 Field 1, , Line 4 Field 3
```

**Comment by renkin777** [comment]
The difference is that I have this line in the configuration:
x.MayContainEOLInData = true;
I cannot remove this setting as it is possible that a field may have a multi-line value.
I attached a sample project for your convenience.
[CsvReaderTest.zip](https://github.com/Cinchoo/ChoETL/files/2992155/CsvReaderTest.zip)

**Comment by Cinchoo** [comment]
Got it, bug was introduced due to recent changes. Close it. Please take the latest nuget and try it. Let me know if you encounter any issues. Thanks for your help.

**Comment by renkin777** [comment]
It is working now. Thank you for the quick fix.
