### ISSUE TITLE
Last field has double quote in its name

### ISSUE THREAD

**Issue by renkin777** [Cinchoo/ChoETL#41]
The latest version appends a double quote into the last field's name. Version 1.0.6.8 does not have this issue. I attached the sample project with the sample file. With v.1.0.6.8 the output will be [Field1] [Field2], with the latest (1.0.9.6) the output will be [Field1] [Field2"].

[CsvReaderTest.zip](https://github.com/Cinchoo/ChoETL/files/2928642/CsvReaderTest.zip)

**Comment by Cinchoo** [comment]
Found the issue, fixed it. Please take the latest package 1.0.9.7 and give it a try. Thanks for reporting.

**Comment by renkin777** [comment]
Hello,
Thank you for the quick fix!
