### ISSUE TITLE
Unable to parse file -- Input string was not in a correct format

### ISSUE THREAD

**Issue by mach37** [Cinchoo/ChoETL#43]
// I am getting a parse error:
[Test File link](https://file.town/download/prwpcq94ihvlemtzg5l3hbyg1)

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

_Stack Trace: 

[FormatException: Input string was not in a correct format.]
   System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) +14510496
   System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt) +172
   ChoETL.ChoLongConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) +282
   ChoETL.ChoConvert.ConvertFrom(Object value, Type targetType, Object sourceObject, Object[] converters, Object[] parameters, CultureInfo culture, String propName) +1187

[ApplicationException: Can't convert 'BACKFLSH' value from 'System.String' type to 'System.Int64' type.]
   ChoETL.ChoConvert.ConvertFrom(Object value, Type targetType, Object sourceObject, Object[] converters, Object[] parameters, CultureInfo culture, String propName) +2938
   ChoETL.ChoETLRecordHelper.ConvertNSetMemberValue(IDictionary`2 dict, String fn, ChoRecordFieldConfiguration fieldConfig, Object& fieldValue, CultureInfo culture) +321
   ChoETL.ChoCSVRecordReader.FillRecord(Object rec, Tuple`2 pair) +1060

[ChoReaderException: Failed to parse 'BACKFLSH' value for 'Emp_Nbr' field.]
   ChoETL.ChoCSVRecordReader.FillRecord(Object rec, Tuple`2 pair) +3439
   ChoETL.ChoCSVRecordReader.LoadLine(Tuple`2 pair, Object& rec) +905
   ChoETL.<AsEnumerable>d__20.MoveNext() +2004
   ChoETL.<BuildEnumerable>d__0`1.MoveNext() +261
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +504_

________________

                var choReader = new StreamReader(choStream);
                var choParser = new ChoCSVReader(choReader).WithFirstLineHeader();
                var id = 1;
                using (var recrodsChoReader = new ChoCSVReader(choReader)
                    .WithFirstLineHeader()              
                {                
                    foreach (IDictionary<string, object> rec in recrodsChoReader.Take(1))
                    {
                        foreach (var kvp in rec)
                        {

                            ColumnDefinition colDef = recrodsChoReader.Configuration[kvp.Key].FieldType.DefinitionsForType(id, kvp.Key, false);                           
                            id++;
                        }
                    }

**Comment by Cinchoo** [comment]
Test File link is broken.

**Comment by mach37** [comment]
https://file.town/download/y9aag2vr5k39vqkfxvqb02juk try that

**Comment by Cinchoo** [comment]
Looks like you may be old version of Cinchoo ETL. It auto discover the field types from first few record lines. In this case, `Emp_Nbr` field is discovered as number from the discovery operation. But it actually holding text values as well. Couple of ways you can fix it. 

1. Update to latest version.
2. set max scan rows to 0 with  `WithMaxScanRows(0)`

Hope it helps.

**Comment by mach37** [comment]
Hi @Cinchoo , I like the discover feature in your lib its awesome  👍  

_I updated to increase accuracy to 6 rows, because with scanrows 0, it sometimes considers integers for boolean, since it never came across a number greater than 1._

Option 2 did not work: `.WithMaxScanRows(6))`   _the error did not go away, it still remains, if you set a break point you will see more detail on how its failing_ I think there is a deeper problem here.

Option 1: I also updated to ChoETL 1.1 from 1.9 I am trying this as well (testing)

**Comment by Cinchoo** [comment]
Looked over the input file. Found out that the `Emp_Nbr` field comes with `BACKFLSH` at line 1444.

FYI, with new binary, it defaults all field types to `string` type. You will have to opt-in for the field type discovery using `WithMaxScanRows()`.

**Comment by mach37** [comment]
Ok, thanks. 

- [ ] How can I get the Number of total rows before I start parsing, for e.g. 
```
var NumberRowsToScan= 10;
If (NumberRowsToScan < ChoETL.File.GetTotalRows)
   WithMaxScanRows(NumberRowsToScan)
Else WithMaxScanRows(ChoETL.File.GetTotalRows - 1) // if less than 10 rows in file
```

- [ ] Is there an option to fallback to less restrictive data type while parsing. Or skip that row

- [ ] How to opt-in for the field type, I am using your lib right now, and before I upgrade, what should I change please? code snippet _requested_

**Comment by Cinchoo** [comment]
1. How can I get the Number of total rows before I start parsing

Based on your sample, there is no need to find the total rows before calling `WithMaxScanRows`. Lib will scan the rows <= max. 

Say, if set the `WithMaxScanRows(10)` and file contains only 5 rows, lib scan those 5 rows and returns objects.

2. Is there an option to fallback to less restrictive data type while parsing. Or skip that row

I'm not clear on your questions. I'll try to answer my best of knowledge. 

If you want change the field type of some of the fields after field type discovery, you can subscribe to `RecordFieldTypeAssessment` event and change the field type there.


3.  How to opt-in for the field type, I am using your lib right now, and before I upgrade, what should I change please? 

You can use one of the `WithField` overloads to set the field types there.

```
using (var cr = new ChoCSVReader("sample.csv")
    .WithFirstLineHeader()
    .WithField("firstName", defaultValue)
    .WithField("lastName")
    .WithField("salary", defaultValue: 100, fieldType: typeof(double))
    )
)
{
    foreach (var x in cr)
        Console.WriteLine(ChoUtility.Dump(x));
}
```

**Comment by mach37** [comment]
thanks you rock
