### ISSUE TITLE
Error System.EntryPointNotFoundException

### ISSUE THREAD

**Issue by D-sense** [Cinchoo/ChoETL#45]
Hi,

I am getting this error in my script.

1) Exception Information
*********************************************
Exception Type: System.EntryPointNotFoundException
Message: SetConsoleCtrlHandler
TypeName: 
Data: System.Collections.ListDictionaryInternal
TargetSite: NULL
HelpLink: NULL
Source: NULL
HResult: -2146233053

StackTrace Information
*********************************************
  at (wrapper managed-to-native) ChoETL.ChoETLFramework.SetConsoleCtrlHandler(ChoETL.ConsoleCtrlMessageHandler,bool)
  at ChoETL.ChoETLFramework.RegisterConsoleControlHandler () [0x0001b] in <859501fe10ae4398bca6219fbdd4f60a>:0 
  at ChoETL.ChoETLFramework._Initialize () [0x00098] in <859501fe10ae4398bca6219fbdd4f60a>:0 
_______________________________________________

**Comment by Cinchoo** [comment]
Is your project is .NET core or .NET framework app?

**Comment by D-sense** [comment]
Hi @Cinchoo, 
Thank you for the reply. It's a .NET framework app.

**Comment by Cinchoo** [comment]
Don't know why it is failing. You can turn this feature off by settings `TurnOnConsoleCtrlHandler` in app.config

`
  <appSettings>
    <add key="TurnOnConsoleCtrlHandler" value="false"/>
  </appSettings>
`
Hope this resolves the issue.

**Comment by D-sense** [comment]
> Don't know why it is failing. You can turn this feature off by settings `TurnOnConsoleCtrlHandler` in app.config
> 
> `<appSettings> <add key="TurnOnConsoleCtrlHandler" value="false"/> </appSettings>`
> Hope this resolves the issue.

But there is no such file in a Console App (specifically, .NET Framework)

**Comment by Cinchoo** [comment]
Add app.config file to your project. There is template available. Pls google if you need help with it.

**Comment by D-sense** [comment]
> Add app.config file to your project. There is a template available. Pls google if you need help with it.

Thank you for the support. That fixed the issue. Although at the end of the script, a CSV is created but does not contain any of the data. (I can view the data by just displaying them on the console, so the endpoint I am contacting works well). So I am thinking the issue may be from the package. This is part of the code:
          `            
           customers = await response.Content.ReadAsAsync<IEnumerable<Customer>>();

            var bucket = new List<ExpandoObject>();
            dynamic record = new ExpandoObject();
            
            foreach (var customer in customers)
            {
                record.DateOfBirth = customer.DateOfBirth;
                record.Email = customer.Email;
                record.FirstName = customer.FirstName;
                record.FundDeposits = customer.FundDeposits;            
                record.LastName = customer.LastName;
                record.PhoneNumber = customer.PhoneNumber;
                record.Source = customer.Source;
                record.State = customer.State;
                bucket.Add(record);
            }
          
            using (var parser = new ChoCSVWriter("customers.csv"))
            {
                parser.Write(bucket);

                ProcessCompletedAlert();
            }`

**Comment by Cinchoo** [comment]
Can u check the `bucket` variable? Does it contain values? Just check the count in the debugger.

**Comment by D-sense** [comment]
> Can u check the `bucket` variable? Does it contain values? Just check the count in the debugger.

Thank you very much for your support. Apology for the late reply (it was out of my control). I've been able to fix it.
