### ISSUE TITLE
Read CSV File With Static Column Not In File

### ISSUE THREAD

**Issue by bbakermmc** [Cinchoo/ChoETL#46]
Is there a way to add a column that isnt in a CSV file, but is needed when writing to the table in SQL.  I dont want to put it to a datatable as these files are >5gb and millions of rows,  When we get a file in we give it a unique ID, then when we load to the table, we reference the ID the data came in on.  I thought I could just give it a default value but it tells me its missing, is there an override or something I might of missed?

```c#
 var config = new ChoCSVRecordConfiguration
                                                   {
                                                       FileHeaderConfiguration =
                                                       {
                                                           HasHeaderRecord = true
                                                       }, Delimiter = "|", AutoDiscoverColumns = false, AutoDiscoverFieldTypes =  false, IsDynamicObject = true, ThrowAndStopOnMissingField = false
                                                   };

                
                config.CSVRecordFieldConfigurations.Add(new ChoCSVRecordFieldConfiguration("FileLogId", 0){DefaultValue = fileLogId, FallbackValue = fileLogId});
                
                
                foreach (var field in fileDefinitionFields.Where(x => x.FieldOrder > 0))
                {
                    config.CSVRecordFieldConfigurations.Add(new ChoCSVRecordFieldConfiguration(field.ColumnName, field.FieldOrder));
                }
                

                dynamic row;
                
                            using (var parser = new ChoCSVReader(blobFile.OpenRead(), config).AsDataReader())
                            {
                                bulkCopy.WriteToServer(parser);
                            }
```

**Comment by Cinchoo** [comment]
Well, there are many ways you can accomplish it. 

Here is one approach, using Linq to Object, you can add extra column to it.


```
            using (var parser = new ChoCSVReader(blobFile.OpenRead())
                .Select(row =>
                {
                    row.FileLogId = 0;
                    return row;
                })
                .AsDataReader())
            {
                bulkCopy.WriteToServer(parser);
            }
```
Hope it helps.

**Comment by bbakermmc** [comment]
@Cinchoo Thanks, are the other ways documented some where :P ?

**Comment by Cinchoo** [comment]
you can read https://www.codeproject.com/Articles/1145337/Cinchoo-ETL-CSV-Reader article

**Comment by bbakermmc** [comment]
How about dynamic mapping by position?  IE have table with columns 1-10.  Have csv with cols 1-20.  We have our own table where we store col1 = col1,  col2 = col4, col3= col 5. Etc. basically we ignore headers and currently just make a data table and do the mapping ourselves not using the framework, was hoping to convert into using the framework using our existing mapping table to tell what cols to map, we don’t make models for this. It’s all dynamic.  I see in the dox you say you can do by position but there is no example.

**Comment by Cinchoo** [comment]
You can use `WithField` overload to specify the position. Hope it helps.
