### ISSUE TITLE
ChoCSVReader not properly closing .csv file?

### ISSUE THREAD

**Issue by Alex-Harttree** [Cinchoo/ChoETL#48]
Before I begin, I should say I am very very very new to C#.

I am writing a program that will spit out a .csv file with a lot of information, then directly after I call the following convertFile method using ChoETL:

        public void convertFile(string inputFile, string outputFile)
        {
            using (var writer = new StreamWriter(outputFile))
            {
                int row = 0;
                writer.Write("[\r\n");

                foreach (var e in new ChoCSVReader(inputFile).WithHeaderLineAt())
                {
                    writer.Write((row > 0 ? ",\r\n" : "") + e.DumpAsJson());
                    writer.Flush();
                    row++;
                }
                writer.Write("]");
                writer.Flush();
                writer.Close();
      
            }
            
        }
    }

My program creates a csv file and json file, then appends each every 5 minutes. However I am unable to do this because I get "The process cannot access the file "csv file" because it is being used by another process." I have narrowed this down to ChoETL because if I remove the convertFile method at the end of my main, it will work just fine and append the csv file every 5 minutes without creating the json.  Any help?

**Comment by Cinchoo** [comment]
You must instantiate ChoCSVReader object and use it in the for loop as shown below to close the file after read CSV file...

        public void convertFile(string inputFile, string outputFile)
        {
            using (var writer = new StreamWriter(outputFile))
            {
                int row = 0;
                writer.Write("[\r\n");

                using (var p = new ChoCSVReader(inputFile).WithHeaderLineAt())
                {
                    foreach (var e in p)
                    {
                        writer.Write((row > 0 ? ",\r\n" : "") + e.DumpAsJson());
                        writer.Flush();
                        row++;
                    }
                }
                writer.Write("]");
                writer.Flush();
                writer.Close();
            }
        }

Hope it helps.

**Comment by Cinchoo** [comment]
I'm putting a fix for this issue, to close the file after foreach look completes. Will push the new package shortly.

In the mean time, you can use the above code to overcome this issue.

**Comment by Cinchoo** [comment]
version 1.1.0.4 pushed to nuget for the fix. Get it and try it. Let me know.

**Comment by Alex-Harttree** [comment]
Thank you for the fix :) The code you posted worked and I'l test out the new fix.
