### ISSUE TITLE
Configuration is not considered

### ISSUE THREAD

**Issue by deghaies** [Cinchoo/ChoETL#49]
Some configurations are not considered during the CSV file reading:
- IgnoreDuplicateFields
- IgnoreEmptyLine

			

			using (var reader = new ChoCSVReader<Class1>(filePath)
				.Configure(c => c.IgnoreDuplicateFields = true)
				.Configure(c => c.IgnoreEmptyLine = true)
				.WithFirstLineHeader())
			{
				csvFileAsDataTable = reader.AsDataTable();
			}

Data example could be found in attachment:
[CsvFile.txt](https://github.com/Cinchoo/ChoETL/files/3378227/CsvFile.txt)

**Comment by Cinchoo** [comment]
I'm little confused with your question. 

From sample CSV file

```
CustomerNo,Name,Email
10130,Company1,example1@example.com
,,
10130,Company1,example1@example.com
```

The line 3 is is not considered `Empty` line. It is a valid CSV line with empty CSV values. `IgnoreEmptyLine' eliminates only blank lines.

`IgnoreDuplicateFields' - it flag means to ignore duplicate CSV columns (field names). In your sample, there is no duplicate CSV columns (`CustomerNo,Name,Email`). 

I hope this helps.

**Comment by deghaies** [comment]
**Point 1:** with reference to the documentation:

> IgnoreEmptyLine - A flag to let the reader know if a record should be skipped when reading if it's empty. A record is considered empty if all fields are empty.

That's why I expect that a line composed of empty fields separated by the delimiter is considered as empty line. I just test it with empty line (not delimiter) and it works.

**Point 2:** I confused duplicate fields with duplicate rows!

Thanks for your quick support!
