### ISSUE TITLE
'ChoETL.ChoDynamicObject' does not contain a definition for 'ToStringEx'

### ISSUE THREAD

**Issue by vibs2006** [Cinchoo/ChoETL#5]
I'm facing this error in my application. 

I have simply started an empty asp.net 4.6.1 web application project and have installed nuget package. 

Following is my code. 
```cs
public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            StringBuilder bldr = new StringBuilder();
            foreach (var e in new ChoCSVReader("Emp.csv"))
                //Console.WriteLine(e.ToStringEx());
                bldr.AppendLine(e.ToStringEx());

            return Content(bldr.ToString());
        }
    }
```
But I'm facing error below
![image](https://user-images.githubusercontent.com/18658498/37813334-b7efce3c-2e8a-11e8-8a41-ce726fa941be.png)

@Cinchoo can you pl guide?

**Comment by vibs2006** [comment]
I would like to add that following code is running on my system _without the extension function_ **ToStringEx**
```cs
 public ActionResult GetStringFromCSVFileDynamicTyped()
 {
            StringBuilder bldr = new StringBuilder();
            foreach (dynamic e in new ChoCSVReader("Emp.csv").WithFirstLineHeader())
                bldr.AppendLine("Id: " + e.Id + " Name: " + e.Name);
            return Content(bldr.ToString());
 }
```

**Comment by Cinchoo** [comment]
In .net, dynamic object doesn't support extensions. You must use explicit ToStringEx() method as below

`ChoUtility.ToStringEx(e);`


Alternatively you can use these methods on them to print the dynamic object contents

```
e.Dump()
e.DumpAsJson();

```
