### ISSUE TITLE
WithEOLDelimiter not showing up

### ISSUE THREAD

**Issue by adeelasghar1001** [Cinchoo/ChoETL#50]
It's not showing up in the CSVWriter

**Comment by adeelasghar1001** [comment]
How should I install this fixed version?

**Comment by Cinchoo** [comment]
pls get the nuget package version 1.1.0.5-alpha

**Comment by adeelasghar1001** [comment]
Where do I download that? Visual Studio only shows up to 1.1.0.4

**Comment by Cinchoo** [comment]
will take sometime to index it.

**Comment by Cinchoo** [comment]
Index done. You should see them now. Make sure you checked `Include Prerelease` checkbox.
