### ISSUE TITLE
Remove Byte Order Mark when generating fixed length ACH

### ISSUE THREAD

**Issue by DevCodex** [Cinchoo/ChoETL#51]
I am using ChoNACHAWriter to generate ACH files, however they are including a Byte Order Mark that the bank is having trouble with.  How can I generate the file without a Byte Order Mark?

Also, it seems this question has been asked on SO but without a concrete answer:
https://stackoverflow.com/questions/53606446/ach-processing-adding-special-characters-in-file

**Comment by Cinchoo** [comment]
This was addressed some time ago. Was reported by someone in the past and take care of.

https://github.com/Cinchoo/ChoETL.NACHA/issues/22

Please post the version of ChoETL you are currently using?

**Comment by DevCodex** [comment]
Excellent, thanks for the quick reply.  I was on 1.0.7.3
