### ISSUE TITLE
DumpAsJson Does Not Preserve Original Headers

### ISSUE THREAD

**Issue by maembe** [Cinchoo/ChoETL#54]
When reading column headers, the csv reader converts spaces to underscores internally ("my header" becomes "my_header") while still allowing access via the original string.

However when converting to json, it loses the original header, even though spaces are valid json keys.   It seems like it should preserve the original headers when serializing the json.  If not, is there a way to override this behavior for a file with unknown headers?

Example:

"my header", "otherheader"
"test","123"

`foreach (var line in reader)
 {
                string json = line.DumpAsJson(); 
                // json == {"my_header":"test","otherheader":"123"}
}
`

**Comment by Cinchoo** [comment]
Hi, have you tried latest package. Looks like this is addressed some time ago. Please spell the version of the library you were using to reproduce it.

**Comment by maembe** [comment]
This is in the latest .NetStandard version, 1.104

**Comment by Cinchoo** [comment]
Pushed new version, please try and let me know.
