### ISSUE TITLE
System.IO.IOException in ChoCSVReader when file locked (especially Excel)

### ISSUE THREAD

**Issue by neuli1980** [Cinchoo/ChoETL#58]
Loading data from a file opened in excel with ChoCSVReader throws an System.IO.IOException.

Reason: File (and FileStream) open without usage of FileShare-parameter.
See the following description of this parameter:
https://www.it-swarm.net/de/.net/wie-oeffne-ich-eine-bereits-geoeffnete-datei-mit-einem-.net-streamreader/957535848/amp/
https://docs.microsoft.com/en-us/dotnet/api/system.io.fileshare?redirectedfrom=MSDN&view=netframework-4.8
https://docs.microsoft.com/de-de/windows/win32/api/fileapi/nf-fileapi-createfilea?redirectedfrom=MSDN

Solution: (at least 2 changes required)

ChoFile::GetEncodingFromFile(string fileName)
using overloaded function with 4 parameters. The forth parameter should be FileShare.ReadWrite

ChoCSVReader::ChoCSVReader(string filePath, ChoCSVRecordConfiguration configuration = null)
instead of 
            _textReader = new StreamReader(ChoPath.GetFullPath(filePath), Configuration.GetEncoding(filePath), false, Configuration.BufferSize);
use
            _textReader = new StreamReader(new FileStream(ChoPath.GetFullPath(filePath),FileMode.Open,FileAccess.Read,FileShare.ReadWrite), Configuration.GetEncoding(filePath), false, Configuration.BufferSize);
because StreamReader has no overloaded method with appropriate FileShare-parameter.

Better solution:
Change constructur against
public ChoCSVReader(string filePath, ChoCSVRecordConfiguration configuration = null):this(new FileStream(ChoPath.GetFullPath(filePath),FileMode.Open,FileAccess.Read,FileShare.ReadWrite),configuration) { }
because there is a constructur with Stream parameter!

Additionally the other reader should also implement these consideration.

**Comment by Cinchoo** [comment]
Use the ChoCSVReader overload to open such file

`var csv = new ChoCSVReader(new FileStream("sample.csv", FileMode.OpenOrCreate, FileAccess.ReadWrite));`

**Comment by neuli1980** [comment]
Hi Cinchoo.

Have you tried your code?
Have you read the links?

It does not what I want because you have to supply the parameter for FileShare!

OK, it is possible to use this code
`var csv = new ChoCSVReader(new FileStream("sample.csv", FileMode.Open, FileAccess.Read, FileShare.ReadWrite));`
but most of people use the overload with filePath parameter and this can fail with the exception.

If you insist, there should be a updated documentation, that this could happen and the solution, but my code change is more robust!

**Comment by Cinchoo** [comment]
Can't expose all the parameters that FileStream supports through CSVReader. Thats why the library exposes Stream parameter, where by you can construct the way you want and pass it to CSVReader. Hence this request is not valid. I'm closing it.
