### ISSUE TITLE
Get Headers/JSON Scheme

### ISSUE THREAD

**Issue by bbakermmc** [Cinchoo/ChoETL#62]
Is there a method to get a list of the headers from a CSV if it has them, or the Schema from JSON? 

This is what Im working with.  It reads in the data fine, but I then also need to create a json scheme out put so I can pass to some other Azure functions that require a schema mapping etc.  So it would nice if could just call .GetHeaders or .GetProperties and then I can make my "propertyName" : "string" json that I need.
```C#
using (var csv = new ChoCSVReader(new StringReader(reqParams.Data), csvRecordConfiguration))
            {
                using (var json = new ChoJSONWriter(new StringWriter(output), jsonRecordConfiguration))
                {
                    json.Write(csv);
                }
            }
```

**Comment by Cinchoo** [comment]
Well there is a way, you can pull these information. Note, this will be available after the first record read in case of dynamic mode.

CSVReader:

`csvRecordConfiguration.CSVRecordFieldConfigurations`

JSONReader:

`jsonRecordConfiguration.JSONRecordFieldConfigurations`

Hope it helps.
