### ISSUE TITLE
Large Xml to csv is tooo slow(Json to csv)

### ISSUE THREAD

**Issue by Kunjahamed-P** [Cinchoo/ChoETL#66]
when try with large xml to csv or json to csv it take more time.
code is
```

  StringBuilder csvData = new StringBuilder();
            using (var r = new ChoJSONReader(Json))
            {
                using (var w = new ChoCSVWriter(csvData).WithFirstLineHeader())
                {
                    w.Write(r);
                }
            }

or

            StringBuilder sb = new StringBuilder();
            using (var p = ChoXmlReader.LoadText(doc.InnerXml))
            {
                using (var w = new ChoCSVWriter(sb).WithFirstLineHeader())
                    w.Write(p);
            }
```

**Comment by Cinchoo** [comment]
Would be nice if you can post working example with sample input. It help to investigate it. Thanks.

**Comment by Kunjahamed-P** [comment]
the code is
```
JObject caqhJson = JObject.Parse(File.ReadAllText(@"path/JSON2CSV/rows.json"));

            StringBuilder csvData = new StringBuilder();
            using (var r = new ChoJSONReader(caqhJson))
            {
                using (var w = new ChoCSVWriter(csvData).WithFirstLineHeader())
                {
                    w.Write(r);
                }
            }
```

the actual data is cannot be share, u can use these json file [https://data.ct.gov/api/views/rybz-nyjw/rows.json?accessType=DOWNLOAD](url)
the result is same

**Comment by Cinchoo** [comment]
found the issue, fixed and pushed new package. Please take the latest and try it. 

Thanks for reporting it.

**Comment by Kunjahamed-P** [comment]
i try  json to csv  with latest ChoETL.JSON.NETStandard but still issue exist.
![image](https://user-images.githubusercontent.com/42990066/71612750-65d2f880-2bc8-11ea-9bca-13f9d3476fba.png)

**Comment by Cinchoo** [comment]
Please try installing prerelease packages. try.

```
Install-Package ChoETL.NETStandard -Version 1.1.0.5-alpha8
Install-Package ChoETL.JSON.NETStandard -Version 1.1.0.5-alpha8
```

**Comment by Kunjahamed-P** [comment]
its working fine, thank you so much. hopefully new stable version will update soon

**Comment by Kunjahamed-P** [comment]
its working fine, thank you so much. hopefully new stable version will update soon...

**Comment by neuli1980** [comment]
> found the issue, fixed and pushed new package. Please take the latest and try it.
> 
> Thanks for reporting it.

Where is the source for this fix?
There is no new commit for this issue.
