### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by johnwpowell** [Cinchoo/ChoETL#7]
Hey love your framework but I need some help to achieve something.

I have a large dataset and need to use AsDataReader() and send the reader to SQL Bulk Copy.  

Each data file is different and so we will be using a varchar max field to hold the columns read in as JSON.
I need to transform each record to a custom object.  I have been through all the samples, even trying the before record read event/interface to change the source, but haven't had any luck.

The POCO object will look like this: (it an alternately be a DataRow object with same properties)

class ImportRow
{
int ImportId {get;set;}
int RowIndex {get;set;}
string fields {get;set;}
}

So if the data comes in like this:
"acme" "1" "1/1/2015"
"contoso" "34" "1/2/2018"

We should get the following objects when calling read()

{
ImportId:42
RowIndex:0
Fields "{[{value:"acme"}, {value:"1"}, {value:"1/1/2015"}]}"
},
{
ImportId:42
RowIndex:1
Fields "{[{value:"contoso"}, {value:"34"}, {value:"1/2/2018"}]}"
}

Please help!

**Comment by Cinchoo** [comment]
This is how you can do to get the DataReader from your input file for sqlbulkcopy

```
string csv = @"""acme"" ""1"" ""1 / 1 / 2015""
""contoso"" ""34"" ""1/2/2018""
";

using (var p = new ChoCSVReader(new StringReader(csv))
	.WithDelimiter(" ")
	)
{
	int rowIndex = 0;

	var dr = new ChoEnumerableDataReader(p.Select(r => new ImportRow
		{
			ImportId = 42,
			RowIndex = rowIndex++,
			fields = JsonConvert.SerializeObject(((ChoDynamicObject)r).Values.Select(r1 => new ValueObject { value = r1.ToNString() }))
		}
	));
	
	//Pass the datareader to SqlBulkCopy
}
```

Let me know if this helps.

**Comment by johnwpowell** [comment]
Close, but not working.  Here's the actual implementation I have.  The 

`using (var fileReader = new ChoCSVReader(stream).WithDelimiter("\t"))
                {
                    var lineIndex = 0;

                    var dataReader = new ChoEnumerableDataReader(fileReader.Select(x =>
                    {
                        var fields = new List<ImportField>();
                        var fieldIndex = 0;
                        foreach (var value in x.Values)
                        {
                            fields.Add(
                                new ImportField
                                {
                                    FieldIndex = fieldIndex++,
                                    OriginalValue = value.ToNString()
                                });
                        }

                        var row = NewRow();
                        row["ImportFileId"] = importResult.ImportFileId;
                        row["LineIndex"] = lineIndex++;
                        row["Fields"] = JsonConvert.SerializeObject(fields, jsonSerializerSettings);

                        importResult.TotalRows++;

                        return row;

                    }));

                    using (var bulkCopy = new SqlBulkCopy(connectionstring))
                    {
                        bulkCopy.DestinationTableName = "dbo.ImportRow";
                        bulkCopy.ColumnMappings.Add("ImportFileId", "ImportFileId");
                        bulkCopy.ColumnMappings.Add("LineIndex", "LineIndex");
                        bulkCopy.ColumnMappings.Add("Fields", "Fields");
                        bulkCopy.BatchSize = batchSize;
                        bulkCopy.EnableStreaming = true;
                        bulkCopy.BulkCopyTimeout = 0;
                        bulkCopy.WriteToServer(dataReader);
                    }
                }`

The enumerable data reader select is not being called.  

As a workaround, I have implemented a custom IDataReader to wrap the ChoseCSVReader.AsDataReader() reader.

**Comment by Cinchoo** [comment]
Noted, Will make it to the next release.

**Comment by johnwpowell** [comment]
THANK YOU for being so responsive and helpful.

**Comment by bbakermmc** [comment]
@johnwpowell Did Cinchoo ever implement the read override?
