### ISSUE TITLE
Discovery does not work latest Nuget

### ISSUE THREAD

**Issue by papyr** [Cinchoo/ChoETL#74]
Hello, in the latest version some of the type discovery/get fields does not work if I update nuget.

Is there another function that will give me the type.

    foreach (IDictionary<string, object> rec in recrodsChoReader.Take(1))
                
        foreach (var kvp in rec)                 
             ColumnDefinition colDef = recrodsChoReader.Configuration[kvp.Key].FieldType..

**Comment by Cinchoo** [comment]
Is this something related to #73

**Comment by papyr** [comment]
Yes and no.


- One issue, is that when you change scan depth, the types are wrong.

- Second issues, is that when there are empty or null values, it shows DataTypes as String
