### ISSUE TITLE
Padded zeros do not display correctly in Excel

### ISSUE THREAD

**Issue by donnyv** [Cinchoo/ChoETL#78]
My property is a string type with the value "0234". But when I open it in Excel it shows as 234. If I edit the csv file manually and change the value to ="0234" it keeps the zero in Excel.

Is there a configuration to do this?

**Comment by Cinchoo** [comment]
Excel treat them as number. To fix it, you surround them with quotes.

You can quote all fields by using `QuoteAllFields`
Or you can quote specific field using `QuoteField`

**Comment by donnyv** [comment]
I tried that. It adds the quotes but doesn't add the "=". So excel still ignores the "0".

**Comment by Cinchoo** [comment]
if you want to add '=' before the value, you can use `valueConverter` to prefix '='

```
using (var w = new ChoCSVWriter(msg)
    .WithFirstLineHeader()
    .WithField("Id")
    .WithField("Name")
    .WithField("Years", fieldType: typeof(string), valueConverter: o => $"={o}")
    )
{
    w.Write(rec);
}
```

**Comment by donnyv** [comment]
Still doesn't work. That code will produce this value in the csv file. =0234 which still doesn't show the 0. I then added the quoteField and that didn't work either because it adds the quotes around the whole value. I get "=0234" 

I need the value to be  ="0234" in the csv, so that Excel keeps that 0.

**Comment by Cinchoo** [comment]
Well, this is how you can do it to get the value as ="0234"

```
using (var w = new ChoCSVWriter(msg)
    .WithFirstLineHeader()
    .WithField("Id")
    .WithField("Name")
    .WithField("Years", fieldType: typeof(string), valueConverter: o => $"=\"{o}\"")
    )
{
    w.Write(rec);
}
```

**Comment by donnyv** [comment]
Nope, didn't work. The value in the csv looks like this with that change. "=""""0234"""""
Looks like something in ChoETL is escaping the value at the very end of the pipeline.

**Comment by Cinchoo** [comment]
Got it, it escaping the quotes as `double quote` is the default quote char. I make it work, tell the writer to use different quote char using `Configure(c => c.QuoteChar = '\'')`

```
using (var w = new ChoCSVWriter(@"C:\temp\x.csv")
    .Configure(c => c.QuoteChar = '\'')
    .WithFirstLineHeader()
    .WithField("Id")
    .WithField("Name")
    .WithField("Years", fieldType: typeof(string), valueConverter: o => $"=\"{o}\"")
    )
{
    w.Write(rec);
}
```


**Output:**
```
Id,Name,Years
1,Mark,="010"
```

**Comment by donnyv** [comment]
Hurray!! Thanks so much.
