### ISSUE TITLE
ChoETL.JSON.NetStandard 1.1.0.5 is cycle detected

### ISSUE THREAD

**Issue by elky84** [Cinchoo/ChoETL#80]
![image](https://user-images.githubusercontent.com/4001940/77507677-3cb2c300-6eac-11ea-9404-b547981cfd1e.png)

1.1.0.5 version is cycle detected.

1.1.0.4 version is not occured.

check please. 

thanks regard.

**Comment by Cinchoo** [comment]
Disabled v1.1.0.5. Released v1.1.0.6 with fix.

Thanks for reporting.

**Comment by elky84** [comment]
king regard!

thanks.
