### ISSUE TITLE
CSV to JSON: Unclear how to name initial JSON array name

### ISSUE THREAD

**Issue by ebptwllc** [Cinchoo/ChoETL#82]
thank you for your time and support!
when converting csv to json, i dont know how to match the API requirement to start with curly brace and preceed array with array name, then square brackets.
--------------------------------
my code
-------------------------------
using (var p = new ChoCSVReader(fileName).WithFirstLineHeader()
                                                                           .Configure(c => c.NestedColumnSeparator = '-'))
                            {

                                using (ChoJSONWriter w = new ChoJSONWriter(csv2json))

                                {

                                    w.Write(p);

                                }
                            }
---------------------
intended output
------------------
{
  "products": [

  ]
}
--------------------
actual output
---------------------
[
 {
  "products": {
    "product": ....

**Comment by Cinchoo** [comment]
Can u post sample csv file?

**Comment by Cinchoo** [comment]
Set `SupportMultipleContent` as `true` to turn it into JSON object

```
using (var w = new ChoJSONWriter(json)
    .Configure(c => c.SupportMultipleContent = true)
    )
{
}
```

**Comment by ebptwllc** [comment]
> Can u post sample csv file?

yes sure. where to send to?

**Comment by Cinchoo** [comment]
paste snippet of csv here

**Comment by ebptwllc** [comment]
after adding the 

> ON object

after setting this, 
the output first 3 lines are as follows.....
{
 {
  "product": "",
------
first 4 lines, expected outcome is 
-----
{
  "products": [
    {
      "product": "{product_path}",
------------------
where/how should I declare the array name ?

**Comment by Cinchoo** [comment]
In order to help you better, need sample code with input csv (in-line), what is expected output and actual output.

Pls format it clearly. Thanks

**Comment by ebptwllc** [comment]
one of the api templates im working on looks like this, where every iteration of object is within the square brackets. any other format and the api will respond 400 error bad request. 
`{
  "products": [
    {
      "product": "my-sku-123",                                             
      "display": {                                                           
        "en": "String"                                                          
      },
      "description": {
        "summary": {
          "en": "String"                                                             },
        "action": {
          "en": "String"                                                        
        },
        "full": {
          "en": "String"                                                       
        }
      },
      "fulfillment": {
        "instructions":{                                                  
          "en":"String",                                                      
          "es":"String"                                                      
        } 
      }, 
      "image": "https://d8y8nchqlnmka.cloudfront.net/NVaGM-nhSpQ/-FooqIP-R84/photio-imac-hero.png",            
      "format": "digital",                                                 
      "sku": "string",                                                       
      "attributes": {                                                           
        "key1": "value1",
        "key2": "value2"
      }, 
      "pricing": {
        "trial": 2,                                                             
        "interval": "month",                                                   
        "intervalLength": 1,                                                  
        "quantityBehavior": "allow",                                       
        "quantityDefault": 1,
        "price": {
          "USD": 14.95,                                                      
          "EUR": 10.99
        },
        "quantityDiscounts": {                                                   
          10: 25.00                                                           
        },
        "discountReason": {
          "en": "The Reason"
        },
        "discountDuration": 1
      }
    }
  ]
}`

i need help to construct a json document like this with nested array support (there are many other api that require some data to be described within square bracket array) with only a CSV, no access to the class model. 

it would be a very very big help to figure out how to set the csvreader and jsonwriter configurations and attributes to achieve this as well as default csv template i can match.

thank you again

**Comment by Cinchoo** [comment]
provide me csv file.

**Comment by ebptwllc** [comment]
`product,display-en,description-summary-en,description-action-en,description-full-en,fulfillment-instructions-en,image,format,sku,attributes-key1,attributes-key2,pricing-trial,pricing-interval,pricing-intervalLength,pricing-quantityBehavior,pricing-quantityDefault,pricing-price-USD,pricing-setupFee-title-en,pricing-setupFee-price-USD,pricing-quantityDiscounts-10,pricing-quantityDiscounts-10-USD,pricing-discountReason-en,pricing-discountDuration
52870tw1pwaap1nentwd0001100326000011,Apple 3.5mm AUX to Lightning Adapter OEM Factory Original iOS Devices iPhone 7/8/X/11/Plus/Ipad P2870TW,Apple 3.5mm AUX to Lightning Adapter OEM Factory Original iOS Devices iPhone 7/8/X/11/Plus/Ipad P2870TW,,,,,,52870TW1PWAAP1NENTWD0001100326000011,0451311752870,,,,,,,330,,,,,,
59890tw1ppbhaoe01kentwd0000500325000008,HANG Black 24H 34000mah Power Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9890TW,HANG Black 24H 34000mah Power Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9890TW,,,,,,59890TW1PPBHAOE01KENTWD0000500325000008,0451311759890,,,,,,,1180,,,,,,
59900tw1ppbhaoe01wentwd0000800325000008,HANG 24H White 34000mah Mobile Power Supply Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9900TW,HANG 24H White 34000mah Mobile Power Supply Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9900TW,,,,,,59900TW1PPBHAOE01WENTWD0000800325000008,0451311759900,,,,,,,1180,,,,,,
59950tw1ppbhapd1wentwd0001300327000012,HANG PD1 White 40000 QC2.0/3.0 6.5V/9V/12V+Type-C(iOS/Samsung/XiaoMi) P9950TW,HANG PD1 White 40000 QC2.0/3.0 6.5V/9V/12V+Type-C(iOS/Samsung/XiaoMi) P9950TW,,,,,,59950TW1PPBHAPD1WENTWD0001300327000012,0451311759950,,,,,,,1300,,,,,,`
using the following code
`using (var p = new ChoCSVReader(fileName).WithFirstLineHeader().Configure(c => c.NestedColumnSeparator = '-'))
                            {
                                using (var w = new ChoJSONWriter(csv2json))

                                { w.Write(p); }
                            }`

produces the following json

`[
 {
  "product": "52870tw1pwaap1nentwd0001100326000011",
  "display": {
    "en": "Apple 3.5mm AUX to Lightning Adapter OEM Factory Original iOS Devices iPhone 7/8/X/11/Plus/Ipad P2870TW"
  },
  "description": {
    "summary": {
      "en": "Apple 3.5mm AUX to Lightning Adapter OEM Factory Original iOS Devices iPhone 7/8/X/11/Plus/Ipad P2870TW"
    },
    "action": {
      "en": null
    },
    "full": {
      "en": null
    }
  },
  "fulfillment": {
    "instructions": {
      "en": null
    }
  },
  "image": null,
  "format": null,
  "sku": "52870TW1PWAAP1NENTWD0001100326000011",
  "attributes": {
    "key1": 451311752870,
    "key2": null
  },
  "pricing": {
    "trial": null,
    "interval": null,
    "intervalLength": null,
    "quantityBehavior": null,
    "quantityDefault": null,
    "price": {
      "USD": 330
    },
    "setupFee": {
      "title": {
        "en": null
      },
      "price": {
        "USD": null
      }
    },
    "quantityDiscounts": {
      "10": null
    },
    "USD": null,
    "discountReason": {
      "en": null
    },
    "discountDuration": null
  }
 },
 {
  "product": "59890tw1ppbhaoe01kentwd0000500325000008",
  "display": {
    "en": "HANG Black 24H 34000mah Power Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9890TW"
  },
  "description": {
    "summary": {
      "en": "HANG Black 24H 34000mah Power Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9890TW"
    },
    "action": {
      "en": null
    },
    "full": {
      "en": null
    }
  },
  "fulfillment": {
    "instructions": {
      "en": null
    }
  },
  "image": null,
  "format": null,
  "sku": "59890TW1PPBHAOE01KENTWD0000500325000008",
  "attributes": {
    "key1": 451311759890,
    "key2": null
  },
  "pricing": {
    "trial": null,
    "interval": null,
    "intervalLength": null,
    "quantityBehavior": null,
    "quantityDefault": null,
    "price": {
      "USD": 1180
    },
    "setupFee": {
      "title": {
        "en": null
      },
      "price": {
        "USD": null
      }
    },
    "quantityDiscounts": {
      "10": null
    },
    "USD": null,
    "discountReason": {
      "en": null
    },
    "discountDuration": null
  }
 },
 {
  "product": "59900tw1ppbhaoe01wentwd0000800325000008",
  "display": {
    "en": "HANG 24H White 34000mah Mobile Power Supply Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9900TW"
  },
  "description": {
    "summary": {
      "en": "HANG 24H White 34000mah Mobile Power Supply Bank 5V/6.5V-XiaoMi/9V-iOS 2.1A QC3.0 P9900TW"
    },
    "action": {
      "en": null
    },
    "full": {
      "en": null
    }
  },
  "fulfillment": {
    "instructions": {
      "en": null
    }
  },
  "image": null,
  "format": null,
  "sku": "59900TW1PPBHAOE01WENTWD0000800325000008",
  "attributes": {
    "key1": 451311759900,
    "key2": null
  },
  "pricing": {
    "trial": null,
    "interval": null,
    "intervalLength": null,
    "quantityBehavior": null,
    "quantityDefault": null,
    "price": {
      "USD": 1180
    },
    "setupFee": {
      "title": {
        "en": null
      },
      "price": {
        "USD": null
      }
    },
    "quantityDiscounts": {
      "10": null
    },
    "USD": null,
    "discountReason": {
      "en": null
    },
    "discountDuration": null
  }
 },
 {
  "product": "59950tw1ppbhapd1wentwd0001300327000012",
  "display": {
    "en": "HANG PD1 White 40000 QC2.0/3.0 6.5V/9V/12V+Type-C(iOS/Samsung/XiaoMi) P9950TW"
  },
  "description": {
    "summary": {
      "en": "HANG PD1 White 40000 QC2.0/3.0 6.5V/9V/12V+Type-C(iOS/Samsung/XiaoMi) P9950TW"
    },
    "action": {
      "en": null
    },
    "full": {
      "en": null
    }
  },
  "fulfillment": {
    "instructions": {
      "en": null
    }
  },
  "image": null,
  "format": null,
  "sku": "59950TW1PPBHAPD1WENTWD0001300327000012",
  "attributes": {
    "key1": 451311759950,
    "key2": null
  },
  "pricing": {
    "trial": null,
    "interval": null,
    "intervalLength": null,
    "quantityBehavior": null,
    "quantityDefault": null,
    "price": {
      "USD": 1300
    },
    "setupFee": {
      "title": {
        "en": null
      },
      "price": {
        "USD": null
      }
    },
    "quantityDiscounts": {
      "10": null
    },
    "USD": null,
    "discountReason": {
      "en": null
    },
    "discountDuration": null
  }
 }
]`

**Comment by Cinchoo** [comment]
Well, based on your input, i believe you want to produce JSON from CSV in the below format. 

```
{
  "products": [
    {
      "product": "my-sku-123",
     .......
    }
  ]
}
```

Here is the sample helps to you to meet the needs

```
            using (var r = new ChoCSVReader("*** YOUR CSV FILE ***")
                .WithFirstLineHeader()
                )
            {
                using (var w = new ChoJSONWriter(json)
                    .Configure(c => c.SupportMultipleContent = true)
                    )
                {
                    w.Write(new { products = r.ToArray() });
                }
            }
```

If you are thinking about customizing individual data points, you must go through defining each one of them according to your needs/specs. I'll leave that to you. 

Hope this helps.

**Comment by ebptwllc** [comment]
its perfect. 
you're awesome. 
thank you SOOOOOOO MUCH
wish i could buy you lunch.
