### ISSUE TITLE
RE: JSON Writer - Possibly support nested arrays?

### ISSUE THREAD

**Issue by ebptwllc** [Cinchoo/ChoETL#83]
.Configure(c => c.NestedColumnSeparator = '-')) works great, but what about nested arrays?
I originally assumed that .Configure(c => c.ArrayIndexSeparator = '_') would be the way to go but it didn't work as intended.

in my CSV file, I have a section that has multiple fulfillment methods, distinguished by numbered suffix 
(for example _1 _2 at the end of the field)

I just started looking over the code these few days, maybe there is something already that covers this that I missed. 

thanks again

**Comment by ebptwllc** [comment]
I saw this description:
22.38. How to read CSV to Collection / Array members?
Cinchoo handles loading of CSV into array/collection members of a specific type. Just define the class structure with mapping CSV column to each members.

For a sample CSV file, where CreId_0, CreName_0, CreId_1, CreName_2 are values to be loaded into collection objects
------------------
in my application, the CSV model is designed by the user at run time so it would be ideal if there was a setting where this can be assigned by a configuration attribute.

**Comment by Cinchoo** [comment]
pls post sample code with sample csv here.

**Comment by ebptwllc** [comment]
for example, this article...
how do i convert the csv back to json exactly like the article?
https://www.c-sharpcorner.com/article/complexnested-json-to-csv-using-choetl/


name,binomial name,major_producers_0,major_producers_1,major_producers_2,nutrition_carbohydrates,nutrition_fat,nutrition_protein  
Apple,Malus domestica,China,United States,Turkey,13.81g,0.17g,0.26g  
Orange,Citrus x sinensis,Brazil,United States,India,11.75g,0.12g,0.94g  

is there a way to set JSON path in attribute or via header field character?

**Comment by Cinchoo** [comment]
Let me take a look.

**Comment by Cinchoo** [comment]
Here is the way to convert from CSV to JSON

```
        public class Fruit
        {
            [DisplayName("name")]
            public string Name { get; set; }
            [DisplayName("binomial name")]
            public string BinomialName { get; set; }
            [Range(0, 2)]
            [DisplayName("major_producers")]
            public List<string> MajorProducers { get; set; }
            public Nutrition Nutrition { get; set; }
        }

        public class Nutrition
        {
            [DisplayName("nutrition_carbohydrates")]
            public string Carbohydrates { get; set; }
            [DisplayName("nutrition_fat")]
            public string Fat { get; set; }
            [DisplayName("nutrition_protein")]
            public string Protein { get; set; }
        }

        static void CSV2JSON2()
        {
            string csv = @"name,binomial name,major_producers_0,major_producers_1,major_producers_2,nutrition_carbohydrates,nutrition_fat,nutrition_protein
Apple,Malus domestica,China,United States,Turkey,13.81g,0.17g,0.26g
Orange,Citrus x sinensis,Brazil,United States,India,11.75g,0.12g,0.94g";

            StringBuilder json = new StringBuilder();
            using (var r = ChoCSVReader<Fruit>.LoadText(csv)
                .WithFirstLineHeader()
                )
            {
                using (var w = new ChoJSONWriter(json)
                    .Configure(c => c.SupportMultipleContent = true)
                    )
                {
                    w.Write(new { Fruits = r.FirstOrDefault() });
                }
            }
            Console.WriteLine(json.ToString());
        }
```

**Output:**
```
{
 "Fruits": {
   "Name": "Apple",
   "BinomialName": "Malus domestica",
   "MajorProducers": [
     "China",
     "United States",
     "Turkey"
   ],
   "Nutrition": {
     "Carbohydrates": "13.81g",
     "Fat": "0.17g",
     "Protein": "0.26g"
   }
 }
}
```

**Comment by ebptwllc** [comment]
one last thing.... 

is it possible to give me an example how to declare the range of nested array with only CSV?

my use cases have specific instructions to have no access to original class data. 

(im making a chrome extension)

**Comment by Cinchoo** [comment]
can you be more specific with samples?

**Comment by ebptwllc** [comment]
sure. 

the above csv is a great example. 
If we can generate a nested array without dependency or relationship to any class, it would be great. 

ideally, CSV2JSON() will generate the JSON document with nested array without dependency on the model class. 

There are many scenarios where there is no model class to work with. 

Enabling array generation directly from CSV without class model dependency is extremely helpful

string csv = @"name,binomial name,major_producers_0,major_producers_1,major_producers_2,nutrition_carbohydrates,nutrition_fat,nutrition_protein
Apple,Malus domestica,China,United States,Turkey,13.81g,0.17g,0.26g
Orange,Citrus x sinensis,Brazil,United States,India,11.75g,0.12g,0.94g";

**Comment by ebptwllc** [comment]
i have been following the codebase and think this framework is amazing. 
thank you again for awesome work.

**Comment by ebptwllc** [comment]
i have updated to the most recent version. 
was wondering if there is a working example yet of this feature.
cheers!

**Comment by Cinchoo** [comment]
here you go

```
            string csv = @"id,name,friends/0,friends/1
1,Tom,Dick,Harry";

            StringBuilder json = new StringBuilder();
            using (var w = new ChoJSONWriter(json)
                .Configure(c => c.SupportMultipleContent = true)
                .Configure(c => c.SingleElement = true)
                )
            {
                using (var r = ChoCSVReader.LoadText(csv).WithFirstLineHeader()
                    .Configure(c => c.AutoArrayDiscovery = true)
                    .Configure(c => c.ArrayIndexSeparator = '/')
                    )
                    w.Write(r);
            }
            Console.WriteLine(json.ToString());
```

Output:

{
  "id": "1",
  "name": "Tom",
  "friends": [
    "Dick",
    "Harry"
  ]
}
