### ISSUE TITLE
"Missing '....' field in CSV file.

### ISSUE THREAD

**Issue by mankyyou** [Cinchoo/ChoETL#84]
I have issue.How to remove header have value is null ? 
my csv is
name,year,filename
test1,2020,
test2,2019,
test3,2019
my code is 
using (var csvReader = ChoCSVReader.LoadText(data)
                    .WithFirstLineHeader()
                    //Get field have value is null
                    .Configure(x => x.NullValue = "")
                    .Configure(x => x.IgnoreEmptyLine = true)
                    .Configure(x=>x.IgnoreIfNoRecordTypeFound = true)
                    .Configure(x => x.FileHeaderConfiguration.IgnoreColumnsWithEmptyHeader = true)
                    .Configure(x=>x.NullValue = "#NULL#")
                    )
                {
                    using (var csvWriter = new ChoJSONWriter(stringBuilderCSV)
                         .Configure(x=>x.NullValue = "")
                         .Configure(X=>X.IgnoreEmptyLine = true)
                        )
                        csvWriter.Write(csvReader);
                }
and Exception is "Missing 'filename' field in CSV file.
Tks u

**Comment by Cinchoo** [comment]
I'm not sure, what is the error you are running into. Took your sample and run it on, no issues

```
string csv = @"name,year,filename
test1,2020,
test2,2019,
test3,2019";

StringBuilder json = new StringBuilder();
using (var csvReader = ChoCSVReader.LoadText(csv)
    .WithFirstLineHeader()
    )
{
    using (var csvWriter = new ChoJSONWriter(json))
        csvWriter.Write(csvReader);
}

Console.WriteLine(json.ToString());
```

Please add more details and version of the package you are using.

**Comment by mankyyou** [comment]
tks u for reply,here is my version in nuget ChoETL -Version 1.2.0
and here is my csv
"CreationTime","Operation","OrganizationId","RecordType","UserType","Workload","ObjectId","UserId","ClientIP","CorrelationId","EventSource","Id","ItemType","ListId","ListItemUniqueId","MessageTime","O365LogContentCreated","O365LogContentType","PartitionKey","Policy","Site","SiteUrl","SourceFileExtension","SourceFileName","SourceRelativeUrl","Timestamp","UserAgent","UserKey","Version","WebId","CustomUniqueId","ApplicationId","EventData","ModifiedProperties","TargetUserOrGroupName","TargetUserOrGroupType"
"4/13/2020 2:21:12 AM","FileAccessed","51abcde6-7de4-48b6-8418-cb3f1234f80b","6","0","TestPoint","https://test.TestPoint.com/sites/Test1010/HeroGraphic/download.jfif","admin@test.gmail.com","40.115.253.28","4038489f-a098-b000-8271-1ee73772c3a2","TestPoint","3a56bd4d-6e5f-4e3a-a7d5-08d7df5155c0","File","eafd7d29-a7e6-4899-8609-aed5dd3f4dff","07aaf062-cd4d-44a7-9346-b4b92dfde804","1/1/0001 12:00:00 AM","4/13/2020 2:25:09 AM","Audit.TestPoint","2020","0","abcdef","https://test.TestPoint.com/sites/Test1010/","jfif","download.jfif","HeroGraphic","1/1/0001 12:00:00 AM +00:00","NONISV|TestPointPnP|PnPCore/3.18.2002.0","i:0h.f|membership|100300008d844fb9@live.com","1","4123wqe-9e10-1a90-9b50-2999f6d76e10",
"4/13/2020 2:21:11 AM","FileAccessed","51abcde6-7de4-48b6-8418-cb3f1234f80b","6","0","TestPoint","https://test.TestPoint.com/sites/Test1010/HeroGraphic/crab-icon-fun-crab.jpg","admin@test.gmail.com","40.115.253.28","4038489f-008a-b000-8271-19e9fdfa17e5","TestPoint","123456789","File","eafd7d29-a7e6-4899-8609-aed5dd3f4dff","94802df0-dbc3-440f-ae8f-90d8bd918609","1/1/0001 12:00:00 AM","4/13/2020 2:25:09 AM","Audit.TestPoint","2020","0","abcdef","https://test.TestPoint.com/sites/Test1010/","jpg","crab-icon-fun-crab.jpg","HeroGraphic","1/1/0001 12:00:00 AM +00:00","NONISV|TestPointPnP|PnPCore/3.18.2002.0","i:0h.f|membership|100300008d844fb9@live.com","1","4123wqe-9e10-1a90-9b50-2999f6d76e10"

and and Exception is "Missing 'ApplicationId' field in CSV file.

**Comment by Cinchoo** [comment]
Got it, some field values are missing from csv. In order to ignore these errors, you must turn off missing value check constraint this feature using `ThrowAndStopOnMissingField`

Here is working sample

```
StringBuilder stringBuilderCSV = new StringBuilder();
using (var csvReader = new ChoCSVReader(@"C:\Projects\GitHub\ChoETL\src\Test\ChoCSVReaderTest\Sample8.csv")
.WithFirstLineHeader()
.ThrowAndStopOnMissingField(false)
.QuoteAllFields(true)
.WithMaxScanRows(10)
)
{
    //foreach (var rec in csvReader)
    //    Console.WriteLine(rec.Dump());
    using (var csvWriter = new ChoJSONWriter(stringBuilderCSV)
    )
        csvWriter.Write(csvReader);
}

Console.WriteLine(stringBuilderCSV.ToString());

```

**Comment by mankyyou** [comment]
tks u,I will try it in Monday

**Comment by mankyyou** [comment]
tks u for help.

**Comment by Karthigeyan14** [comment]
Actually, I'm facing an issue while converting JSON to a CSV file. I deserialized it with a dynamic object, but the problem is that the headers are generated based on the first set of data. If the next set of data differs from the first, any missing data is not included in the CSV file. Do you have any suggestions...?
