### ISSUE TITLE
How to set maxLineSize other than default for ReadLines method?

### ISSUE THREAD

**Issue by zzzare** [Cinchoo/ChoETL#86]
I am using configuration MayContainEOLInData = true since some cells can have EOL inside string.
When I turn this on, I get exception **Large line found. Check and correct the end of line delimiter**.

I can see that this happens because there is a maxLineSize which apparently gets exceeded.

Is there any way to increase this?

**Comment by Cinchoo** [comment]
currently this parameter is exposed through configuration. It is control mechanism to avoid out of memory exception.

**Comment by Cinchoo** [comment]
Will be adding configuration parameter to override it. Will update.

**Comment by Cinchoo** [comment]
On the next version, added MaxLineSize property to configuration.

Default 32768. Allowed to set bigger than the default value.

**Comment by Cinchoo** [comment]
new package v1.2.0.2 released. pls try and let me know. thx
