### ISSUE TITLE
Simple 3 Column CSV - POCO 3 String Fields - Field Names in Attribute - Reader All Fields Null

### ISSUE THREAD

**Issue by jeffreywstevens** [Cinchoo/ChoETL#89]
Dynamic read works fine.  Trying to use POCO decorated with ChoCSVFieldRecordField attribute on POCO properties to make it easier.  Reader failed until field names correctly assigned in ChoCSVRecordField( FieldName=.  However, all string fields in the POCO record return as null.  

Any simple thing to check on this to make it work?

**Comment by jeffreywstevens** [comment]
Created config from attributed POCO and used in constructing ChoCSVReader which resolved this.

**Comment by Cinchoo** [comment]
Can you please post a sample code which breaks the CSV read? Wanted to check on it. appreciate it.
