### ISSUE TITLE
WithHeaderRow causing rows to not be read

### ISSUE THREAD

**Issue by johnwpowell** [Cinchoo/ChoETL#9]
I have an import file with 16632 rows with the first line header.  When I set use .WithFirstLineHeader(), it only reads about 5000 rows.  Am I missing something?

**Comment by Cinchoo** [comment]
There may be rows error out while loading. 

In order to see what is failing, set this statement at the main entry

ChoETLFrxBootstrap.TraceLevel = TraceLevel.Verbose;

This will display all the actions.

**Comment by Cinchoo** [comment]
Subscribe to RecordLoadError event to see any failures

```
            using (var p = ChoCSVReader.LoadText(csv)
                .Setup(s => s.RecordLoadError += (o, e) => Console.WriteLine(e.Exception.Message))
                )
            {
            }
```

**Comment by johnwpowell** [comment]
That's what it is.  When specifying WithFirstLineHeader(), I'm getting 11K errors.  But if I don't use it, it reads all rows successfully.

**Comment by Cinchoo** [comment]
What is the error? Can you share code sample?

**Comment by Cinchoo** [comment]
If you don't care about header, use WithFirstLineHeader(true) overload.

**Comment by johnwpowell** [comment]
[TestMethod]
        public void DelimitedImportReaderChoCsvTest()
        {
            var errors = new List<Exception>();
            var rowCount = 0;

            using (var stream = File.Open(@"MyFile.txt", FileMode.Open))
            {
                using (var reader = new ChoCSVReader<dynamic>(stream).WithDelimiter("\t")/*.WithFirstLineHeader(true)*/)
                {
                    reader.RecordLoadError += (sender, e) =>
                    {
                        errors.Add(e.Exception);
                        e.Handled = true;
                    };

                    var dataReader = reader.AsDataReader();

                    while (dataReader.Read())
                    {
                        rowCount++;
                    }
                }
            }

            Assert.AreEqual(0, errors.Count);
            Assert.AreEqual(16632, rowCount);
        }

**Comment by Cinchoo** [comment]
Code is good. Can you share below details in order to help you on it

1. Error Message
2. a CSV record line which throws errors. 
3. CSV header line

**Comment by johnwpowell** [comment]
[BadFile.txt](https://github.com/Cinchoo/ChoETL/files/1971643/BadFile.txt)

**Comment by Cinchoo** [comment]
Found out the problem. There is build-in algorithm which scans the CSV field values and discover their datatypes. By default, parser uses the very first data row for the datatype discovery process. 

One downside of this approach is, if a field comes with '0' on first row, it will be treated as long type. For the same field, if the value comes as '2.10' on second row, it will try to parse it long value, which eventually fails in your case.

Couple of ways you can handle this situation.

1. If you want to parse and load the field values as in native types, you can set MaxScanRows to 10 (whatever make sense for you). 

```
using (var reader = new ChoCSVReader(stream).WithDelimiter("\t").WithFirstLineHeader()
    .Configure(c => c.MaxScanRows = 10)
    )
```
2. If you don't care about the field types, want to keep all the values as simple text, set MaxScanRows = 0

Hope this helps. Let me know.

**Comment by Cinchoo** [comment]
To avoid this issue from happening, I'm going to turn off this default behavior of discovering field datetypes.

**Comment by johnwpowell** [comment]
Genius!  THANK YOU!
