### ISSUE TITLE
Comma Delimited - Dynamic Double Quotes With Commas  First Column Causing Read Failures

### ISSUE THREAD

**Issue by jeffreywstevens** [Cinchoo/ChoETL#90]
The first column is a name field that can include comma.  When a comma appears in the name data, the field data is wrapped with double quotes.  However, the dynamic reader is determining this as two fields throwing off the reader.  Is there a config value to handle this?  I tried with a POCO and getting errors there too.  

Example:

Short               Name,Cust                Key,Old CIF Key
Fire & Casualty,00000000000001,AAA  FIR CA 00
"Doe, John",00000000000008,JDOEPD.0J5J.00
Legal Research &,00000000000009,AALE RES WR 00
Indoor Advertisi Llc,00000000000011,CO MA L00

**Comment by Cinchoo** [comment]
You must call `QuoteAllFields` on the reader to handle this situation. Here is the working sample

```
string csv = @"Short Name,Cust Key,Old CIF Key
Fire & Casualty,00000000000001,AAA FIR CA 00
""Doe, John"",00000000000008,JDOEPD.0J5J.00
Legal Research &,00000000000009,AALE RES WR 00
Indoor Advertisi Llc,00000000000011,CO MA L00";

using (var r = ChoCSVReader.LoadText(csv)
    .WithFirstLineHeader()
    .QuoteAllFields())
{
    foreach (var rec in r)
        Console.WriteLine(rec.Dump());
}
```

Hope it helps.

**Comment by jeffreywstevens** [comment]
You rock!  30 minutes ago and I may have made it to a dinner party.  You probably saved me from covid!

**Comment by Cinchoo** [comment]
You welcome, In case, you want to approach this using POCO, here is the working sample

POCO class

```
[ChoCSVFileHeader]
[ChoCSVRecordObject(QuoteAllFields = true)]
public class Insurance
{
    [ChoCSVRecordField(FieldName = "Short Name")]
    public string ShortName { get; set; }

    [ChoCSVRecordField(FieldName = "Cust Key")]
    public string CustKey { get; set; }

    [ChoCSVRecordField(FieldName = "Old CIF Key")]
    public string OldCIFKey { get; set; }
}
```

Reader code

```
string csv = @"Short Name,Cust Key,Old CIF Key
Fire & Casualty,00000000000001,AAA FIR CA 00
""Doe, John"",00000000000008,JDOEPD.0J5J.00
Legal Research &,00000000000009,AALE RES WR 00
Indoor Advertisi Llc,00000000000011,CO MA L00";

using (var r = ChoCSVReader<Insurance>.LoadText(csv)
    )
{
    foreach (var rec in r)
        Console.WriteLine(rec.Dump());
}
```
