### ISSUE TITLE
CultureInfo ( ga-IE) not supported

### ISSUE THREAD

**Issue by taraok** [Cinchoo/ChoETL#92]
Using ChoCSVReader to read a CSV file and I am trying to set the culture on it to ga-IE but it does not appear to be supported. The fada, a diacritic mark in the language, is not getting converted.

var reader = new ChoCSVReader<County>(filename, null)
                .WithDelimiter("\t")
                .Configure(c => c.Culture = new System.Globalization.CultureInfo("ga-IE"));

var dt = reader.AsDataTable();

**Comment by Cinchoo** [comment]
Can you please provide sample CSV file?

**Comment by taraok** [comment]
Renamed the file from .csv to .txt as .csv uploads are not supported. The delimiter in the file is \t.

[COUNTY.txt](https://github.com/Cinchoo/ChoETL/files/4814528/COUNTY.txt)

**Comment by Cinchoo** [comment]
Thanks for the sample. Can you please brief more info what is actual result and expected result should be? Screenshot helps.

**Comment by Cinchoo** [comment]
looks like it is not a culture issue, may be encoding issue

Try this and let me know

```
            using (var reader = new ChoCSVReader(new StreamReader("COUNTY.csv", Encoding.GetEncoding("iso-8859-1")))
                    .WithFirstLineHeader()
                    .WithDelimiter("\t")
                    )
            {
                var dt = reader.AsDataTable();
            }
```

**Comment by taraok** [comment]
Hi there,

The code above works. Didn't consider the encoding.

Many thanks for your help.
