### ISSUE TITLE
Produce Array of Json Objects from a DataReader - missing closing ]

### ISSUE THREAD

**Issue by StuartFergusonVme** [Cinchoo/ChoETL#93]
I am attempting to use the library as follows to produce a Json Array from a data reader:

```
StringBuilder builder = new StringBuilder();

var jsonWriter = new ChoJSONWriter(builder);

jsonWriter.Write(dataReader); //The data reader is populated from an SQL command and has 2 records in it
```

When I do the .ToString() on the StringBuilder I get back Json data as expected apart from one thing the array of json objects does not have a terminating ].

Here is the json output I get:

```
[
  {
    "Code": "V118860                             ",
    "Rate": 20,
    "Name": "Standard VAT   ",
    "VatCode": 2,
  },
  {
    "Code": "V118861                             ",
    "Rate": 20,
    "Name": "Standard VAT   ",
    "VatCode": 2,
  }
```

Is there a setting I need to set in the Writer's configuration to get the closing ] to be written on the Json output?

**Comment by Cinchoo** [comment]
Can you pls tell me the version of the library you are using? Make sure it is latest.

**Comment by StuartFergusonVme** [comment]
<PackageReference Include="ChoETL" Version="1.2.0.5" />
<PackageReference Include="ChoETL.JSON" Version="1.2.0.5" />

**Comment by Cinchoo** [comment]
You will need to close the writer. call `jsonWriter.Dispose()`

Better yet always use `using` statement on reader / writer.

**Comment by StuartFergusonVme** [comment]
Perfect that worked, thanks for your help.
