### ISSUE TITLE
Cannot load DLL at runtime

### ISSUE THREAD

**Issue by JeremyCaron** [Cinchoo/ChoETL#95]
Hello,

I tried using ChoETL in a dotnet core project via installing it with:

dotnet add package ChoETL.JSON --version 1.2.0.6

This caused the appropriate entry to be added to my csproj and DLLs came down when I ran a restore.  However, checking the properties on these DLLs, the version numbers all show as 1.1.0.4, not 1.2.0.6.  At runtime, dotnet core refuses to load the DLL because the metadata on it doesn't match what's in the csproj file.  Changing my csproj reference to 1.1.0.4 and rebuilding seems to solve the problem however and the DLL then loads at runtime.  This effectively pins me to an older version I'd rather not be on! :)

Thanks for writing this - saved me a lot of time!

**Comment by JeremyCaron** [comment]
Here's the actual error, verbatim as I see it:

Could not load file or assembly 'ChoETL.Core, Version=1.2.0.6, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
System.IO.FileLoadException: Could not load file or assembly 'ChoETL.Core, Version=1.2.0.6, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'ChoETL.Core, Version=1.2.0.6, Culture=neutral, PublicKeyToken=null'

Here's what I see when examining the DLL on disk:

./exiftool /frb/ascent/ascent-api/Ascent.Api/bin/Debug/netcoreapp3.1/ChoETL.Core.dll
ExifTool Version Number         : 12.01
File Name                       : ChoETL.Core.dll
Directory                       : /frb/ascent/ascent-api/Ascent.Api/bin/Debug/netcoreapp3.1
File Size                       : 868 kB
File Modification Date/Time     : 2019:06:29 13:36:58-04:00
File Access Date/Time           : 2020:07:13 16:48:10-04:00
File Inode Change Date/Time     : 2020:07:14 13:59:16-04:00
File Permissions                : rwxr--r--
File Type                       : Win32 DLL
File Type Extension             : dll
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2054:04:23 13:53:26-04:00
Image File Characteristics      : Executable, Large address aware, DLL
PE Type                         : PE32
Linker Version                  : 48.0
Code Size                       : 886272
Initialized Data Size           : 1536
Uninitialized Data Size         : 0
Entry Point                     : 0xda4c2
OS Version                      : 4.0
Image Version                   : 0.0
Subsystem Version               : 4.0
Subsystem                       : Windows command line
File Version Number             : 1.1.0.4
Product Version Number          : 1.1.0.4
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Win32
Object File Type                : Dynamic link library
File Subtype                    : 0
Language Code                   : Neutral
Character Set                   : Unicode
Comments                        : ETL Framework for .NET
Company Name                    : Cinchoo Inc.
File Description                : ChoETL.Core
File Version                    : 1.1.0.4
Internal Name                   : ChoETL.Core.dll
Legal Copyright                 : Copyright Cinchoo Inc.
Original File Name              : ChoETL.Core.dll
Product Name                    : ChoETL.NETStandard
Product Version                 : 1.1.0.4
Assembly Version                : 1.1.0.4

**Comment by JeremyCaron** [comment]
For what it's worth, I also saw the same issue if I tried 1.2.0.5.

**Comment by Cinchoo** [comment]
Yes, I noticed it too. I've have to fix the nuget and republish the package.

In the mean time, can you please install `ChoETL` explicitly, see if that works.

> install-package ChoETL

**Comment by Cinchoo** [comment]
or you can use .net core package 

> install-package ChoETL.JSON.NETStandard

**Comment by JeremyCaron** [comment]
Switching to the .net core package did the trick, thanks!  I'm now seeing a difference in behavior between 1.1.0.4 and 1.2.0.6 I don't yet understand, but I'll follow-up on that separately.
