### ISSUE TITLE
CSV Validation 

### ISSUE THREAD

**Issue by jwomackgsa** [Cinchoo/ChoETL#98]
Hi,

I am using the CSV reader (1.2.0.7) component of the .net standard library and just had a question on what if any validations are in place.  My usage is a POCO with each property using the ChoCSVRecordField attribute.  I am then just using the reader of that type load in.  
`var reader = new ChoCSVReader<myObject>(csvData, etlConfig).WithFirstLineHeader();`

In some testing with CSV data, I have been seeing some weird handling.  For example, if my headers don't match the POCO I don't get an error.  If headers are fine, but first data row has incomplete elements, it still loads data but into a partial object.  At this point I am just looking for information on what situations I should expect the reader to throw csv errors so I can addon on further validation that I might need for my use case.  I have updated the library several times over the development and I recall it being a lot picker about the CSV, but now I can't seem to replicate some of those error.

**Comment by Cinchoo** [comment]
Well, in both cases, you will need to subscribe to `RecordLoadError` event and handled them.

Here is the working sample.

```
string csv = @"Id, Name1
1, Tom
2, Mark";

using (var r = ChoCSVReader< EmployeeZ>.LoadText(csv)
    .WithFirstLineHeader()
    .Setup(s => s.RecordLoadError += (o, e) => 
    {
        Console.WriteLine(e.Exception.Message);
        if (e.Exception is ChoMissingRecordFieldException)
            e.Handled = false;
        else
            e.Handled = true;
    })
    )
{
    foreach (var rec in r)
        Console.WriteLine(rec.Dump());
}
```

**Comment by jwomackgsa** [comment]
Ok so here is what I have seeing replicated on your example.  In the csv the second row is missing the Status value.  The load still happens because it keeps the previous records value and just adds to the new object.

Employee.cs
```
public class Employee
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }

    }
```

```
static void Main(string[] args)
        {
            string csv = @"Id, Name, Status
1, Tom, Active
2, Mark";

            using var r = ChoCSVReader<Employee>.LoadText(csv)
                .WithFirstLineHeader()
                .Setup(s => s.RecordLoadError += (o, e) =>
                {
                    Console.WriteLine(e.Exception.Message);
                    if (e.Exception is ChoMissingRecordFieldException)
                        e.Handled = false;
                    else
                        e.Handled = true;
                });
            foreach (var rec in r)
                Console.WriteLine(rec.Dump());
        }
```

Output

-- CSVTester.Employee State -- 
        id: 1
        Name: Tom
        Status: Active


-- CSVTester.Employee State -- 
        id: 2
        Name: Mark
        Status: Active

**Comment by Cinchoo** [comment]
It is a bug, I'm looking into it. Thanks for reporting.

**Comment by Cinchoo** [comment]
Put a fix, released new package. Pls give it a try, let me know. Thx

**Comment by jwomackgsa** [comment]
Thanks for the quick turnaround.  I will run it through some tests.  I was wondering is there a way to get the record line # from the record error stream?

**Comment by Cinchoo** [comment]
`Index` property on the callback event argument provides you the line no.

**Comment by jwomackgsa** [comment]
This issue looks resolved.  Thanks
