### ISSUE TITLE
NestedColumnSeparator gives error

### ISSUE THREAD

**Issue by Miecjel** [Cinchoo/ChoETL#99]
Hello,

I have  nested object and using given example:

`using (var csv = new ChoCSVReader("nested.csv").WithFirstLineHeader().Configure(c => c.NestedColumnSeparator = '/'))
{
    foreach (var x in csv) 
         Console.WriteLine(x.DumpAsJson());
}`

I'm getting this error:

>  Type 'ChoETL.ChoDynamicObject' with data contract name 'ArrayOfKeyValueOfstringanyType:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

V1.2.0.8 (tried older versions)
Net Core 3.1 (also tried with .Net 4.7.2)

**Comment by Cinchoo** [comment]
There is issue with `DumpAsJson` helper method printing the dynamic.  You can use `Dump` instead.

I'll be putting a fix on next release.

**Comment by Miecjel** [comment]
Ok, thnx!
